gasCosts/gasCosts.js
helpers/test-data-generator.js

Updates gas cost tests with what is a near complete task lifecycle implementation. Calculates the simplest task on chain costs.

Update gas cost checks

---

contracts/ColonyTask.sol
test/colony.js

Implemented refunding task budget to domain part of #22

Return funds when a task is cancelled

---

contracts/ColonyTask.sol
test/colony-funding.js
test/reputation-update.js

Implements worker payout logic based on rating part for #24 
- Setting the worker payout to 0 if work rating is less or equal to 2.

24 Task completion and rating

---

.gitignore
circle.yml
contracts/ColonyFunding.sol
contracts/ColonyNetwork.sol
contracts/ColonyTask.sol
contracts/IColony.sol
contracts/IColonyNetwork.sol

Documents the main contract interfaces used by clients: `IColonyNetwork` and `IColony` using [natspec comments](https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format).
Also upgrades `yarn` to 1.5.1

Document interfaces

---

package.json
yarn.lock

chore(package): update solidity-coverage to version 0.5.4

---

.gitignore
.solcover.js
helpers/test-helper.js
scripts/start-blockchain-client.sh

To be consistent with our trufflepig docs and the docs for colonyJS (and hence the hackathon starter repo) I renamed the ganache accounts file to `ganache-accounts.json`

Rename ganache accounts file

---

docs/README.md
docs/_Docs_GetStarted.md
docs/_Docs_MetaColony.md
docs/_Docs_NetworkOverview.md
docs/_Docs_ReputationMining.md

Add Reputation Mining doc.

---

.circleci/config.yml
contracts/ColonyFunding.sol
migrations/2_deploy_contracts.js
package.json
scripts/start-blockchain-client.sh
test/colony-network-mining.js
truffle.js

Block gas limit was set to just over `6700000` so lowering our `truffle` defaults to match that.

Update ganache-cli to 6.1.3

---

contracts/ColonyFunding.sol
test/colony-funding.js

Closes #239 
Allow removal of money from a task pot if either:
1. Task is cancelled (therefore no restrictions), or
2. Remaining funds are >= sum of current payouts
This is to prevent a task owner from defunding an ongoing task without worker/evaluator input, since ostensibly the worker is working on a task in part because of their confidence that payment is available and secure.
If funds need to be removed in excess of the budget, first the budget must be changed (which requires approval of the worker/evaluator), and then funds can be removed.

Restrict defunding pot below task budget

---

truffle.js

Closes #261 
https://mochajs.org/#-s---slow-ms
Set mocha slowness cutoff to 1000ms (from the current 100ms).

Add slow=1000 mocha config

---

contracts/ColonyStorage.sol
contracts/Token.sol
test/meta-colony.js

Sync Token with updated implementation in `colonyToken` repo
Remove storage slots following agreement on no upgrade requirements

Switch token props to the correct types as per ERC20

---

contracts/ColonyNetwork.sol
contracts/IColonyNetwork.sol
helpers/test-data-generator.js
helpers/test-helper.js
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/test/MaliciousReputationMinerExtraRep.js
test/colony-network-mining.js
test/meta-colony.js

Closes #282 
Not much to say here, parent fetching implemented transparently as a internal recursive function. No interface has changed.

Fix parent skill fetching

---

.soliumrc.json
contracts/EtherRouter.sol
contracts/ReputationMiningCycle.sol
package.json
yarn.lock

Updated Solium to 1.1.8

---

docs/_Docs_DomainsSkills.md
docs/_Docs_MetaColony.md
docs/_Docs_NetworkOverview.md
docs/_Docs_Pots.md
docs/_Docs_Reputation.md
docs/_Docs_Tasks.md
docs/_Docs_Upgrades.md

I opened this to fix a couple of issues with the current docs.
So far:
This is stil a WIP.

Doc fixes collection

---

package.json
yarn.lock

Update eslint-config-prettier to version 3.0.1

---

contracts/ReputationMiningCycle.sol
gasCosts/gasCosts.js
helpers/test-helper.js
packages/reputation-miner/ReputationMiner.js
test/colony-network-mining.js

Fix TODOs for reputation mining submission windows

---

contracts/ColonyFunding.sol
test/colony-funding.js

Check 'from' pot exists when sending funds

---

contracts/ReputationMiningCycle.sol

Closes #347 
Reduces the gas cost of `submitJustificationRootHash` by nearly 7000 gas (comparing the relevant outputs from [this build](https://circleci.com/gh/JoinColony/colonyNetwork/4072?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack) and a [recent build on develop](https://circleci.com/gh/JoinColony/colonyNetwork/4048)

Reduce external calls in submitJustificationRootHash

---

contracts/ColonyFunding.sol
contracts/ColonyStorage.sol
contracts/IColony.sol

Move all remaining uint256 roles to uint8

---

docs/README.md

This pull request updates the Gitter badge and adds the Discourse badge.
This pull request also deceases the width of the banner image and centers the image and badges.

Update readme badges and svg banner

---

contracts/ReputationMiningCycle.sol
contracts/ReputationMiningCycleRespond.sol
gasCosts/gasCosts.js
helpers/constants.js
helpers/test-helper.js
packages/reputation-miner/ReputationMiner.js
test/colony-funding.js
test/colony-network-mining.js
test/colony-network-recovery.js
test/token-locking.js

Closes #356
- Use constants to refer to mining cycle duration and matching decay rate
- Update decay numerator from `999679150010888` to `992327946262944`

24hr Mining Cycle

---

docs/README.md
docs/_Bug-bounty_BugBounty.md
docs/_bug_rules.md
docs/_bug_terms.md

Bug Bounty rules SLA, and terms&conditions

---

contracts/ITokenLocking.sol
contracts/ReputationMiningCycle.sol
contracts/TokenLocking.sol
test/colony-network-mining.js
test/token-locking.js

Follow-on to #397 which reduces lost stake to MIN_STAKE (instead of entire stake)

Reduce lost miner stake to MIN_STAKE

---

contracts/Token.sol
test/colony.js

Emit Transfer event when minting tokens

---

contracts/SafeMath.sol

Correctly handle multiplication with MIN_INT256

---

package.json
scripts/check-recovery.js
yarn.lock

Greenkeeper/prettier 1.15.2

---

contracts/ColonyTask.sol
test/colony-task-work-rating.js

Fix for empty rating submissions

---

test/colony-funding.js
test/colony-network-mining.js
test/colony-network-recovery.js
test/colony-network.js
test/colony-recovery.js
test/colony-task.js
test/colony.js
test/meta-colony.js
test/router-resolver.js
test/token-locking.js

Closes #382
- Update lib/dappsys to include error messages.
- Update tests to expect new error strings.

Update lib/dappsys to include error messages

---

test/colony.js

Closes #414 
Pretty straightforward. Add some more checks to ensure we're testing what we think we're testing.

Ensure we are testing the correct function signature

---

test/reputation-update.js

I messed up this test, I apologize :(

Fix incomplete test

---

contracts/Colony.sol
contracts/ColonyAuthority.sol
contracts/ColonyDataTypes.sol
contracts/ColonyNetwork.sol
contracts/IColony.sol
test/colony-recovery.js
test/colony.js

Remove the ability to change token on Colony once initialised

---

contracts/Colony.sol
contracts/ColonyAuthority.sol
contracts/ColonyDataTypes.sol
contracts/ColonyFunding.sol
contracts/ColonyNetworkStorage.sol
contracts/ColonyStorage.sol
contracts/ColonyTask.sol
contracts/CommonStorage.sol
contracts/IColony.sol
contracts/ReputationMiningCycleStorage.sol
test/colony-network-recovery.js

Optimise contract storage layout

---

.gitignore
docs/_Docs_GetStarted.md
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/bin/index.js
packages/reputation-miner/package.json

This pull request updates the "Get Started" instructions in the colonyNetwork documentation and the miner durations. It also requires babel in the reputation miner script so that the miner can be run with node using es6 syntax.

Update "Get Started" and reputation miner

---

contracts/ColonyNetwork.sol
contracts/ColonyTask.sol
test/reputation-update.js

Closes #354 
Implemented at the `ColonyNetwork` level rather than the `ColonyTask` level for generality.

Do not append zero-valued reputation updates to the log

---

.eslintrc
helpers/test-helper.js
helpers/upgradable-contracts.js
packages/reputation-miner/.eslintrc
test/colony-network-mining.js
test/colony-network-recovery.js
test/colony-task.js

Implements part of #317 
Disable `no-await-in-loop` rule and remove all one-off disabling comments.

Disable no-await-in-loop rule

---

test/colony-network-mining.js

Implements part of #317 
I noticed we initialized quite a few redundant mining clients. Why waste the cycles? Also, I reworked some variable names to take advantage of javascript destructuring in function calls and make the miner invocations more succinct.

Remove redundant mining client initializations

---

contracts/ColonyNetwork.sol
contracts/ColonyNetworkDataTypes.sol
contracts/ColonyNetworkMining.sol
contracts/IColonyNetwork.sol
contracts/IReputationMiningCycle.sol
contracts/ReputationMiningCycle.sol
contracts/ReputationMiningCycleDataTypes.sol
contracts/ReputationMiningCycleRespond.sol
test/colony-network-recovery.js

Closes #496
Implements required a part for #496
Changed data-type of elements in struct ReputationLogEntry. nUpdates & nPreviousUpdates from uint256 to uint128 thus effectively reducing gas costs by 20k.

Changed data-type of element in struct of nUpdates & nPreviousUpdates from uint256 to uint128

---

test/reputation-mining/basic-functionality.js
test/reputation-mining/client-core-functionality.js
test/reputation-mining/client-sync-functionality.js
test/reputation-mining/dispute-resolution-misbehaviour.js
test/reputation-mining/disputes-over-child-reputation.js
test/reputation-mining/happy-paths.js
test/reputation-mining/root-hash-submissions.js
test/reputation-mining/types-of-disagreement.js

Closes #305 
Same same as #515, except for the reputation mining tests.

Upgrade reputation-mining tests to bn-chai

---

helpers/test-helper.js
package.json
yarn.lock

Upgrade ethereumjs-utils and fix breaking changes

---

.solcover.js
package.json
test/colony-network-auction.js
yarn.lock

Bump `solidity-coverage` version.

Use new solidity-coverage

---

contracts/ColonyTask.sol
test/reputation-update.js

Do not penalise worker's skill awarded 

---

package.json
yarn.lock

Closes #589 
This is all greenkeeper, don't blame me for anything that's wrong...

Greenkeeper/eslint plugin import 2.17.2

---

docs/_Docs_Overview.md
docs/_Intro_Welcome.md

Fixed some grammar and added links

---

docs/_Intro_Welcome.md

Hmm, this is a messy workflow for really tiny docs updates. It would be nice, however, to figure out a way to streamline tiny changes to docs like this, that might come from external contributors. 
colonyJS doesn't really have this problem because it moves so fast, but for the network it seems preferable to keep a running branch of typos and fixes to the docs that doesn't waste circleci resources, and doesn't require such thorough checking before making it into `develop`

Fix broken link to whitepaper

---

.gitignore
.solcover.js
contracts/ColonyTask.sol
contracts/IColony.sol
contracts/extensions/OneTxPayment.sol
docs/_Interface_IColony.md
package.json
test/contracts-network/colony-network-auction.js
test/contracts-network/colony-task-work-rating.js
test/contracts-network/colony-task.js
test/contracts-network/meta-colony.js
test/extensions/one-tx-payment.js

Update the `colonyToken` git submodule commit.
Also re-include the extension contract tests under `test:contracts` oops
Also add a handful of missing tests. This helps get coverage over the 95% threshold for branches we set ourselves for Q2.

Update submodule add improve test coverage

---

contracts/Colony.sol
contracts/ColonyAuthority.sol
contracts/ColonyNetwork.sol
contracts/IColony.sol
docs/_Interface_IColony.md
test/contracts-network/colony-permissions.js

Reverts JoinColony/colonyNetwork#630
Given that we're prepping for a mainnet launch these changes are going to have to wait until later...

Revert "Arbitration Role in IColony"

---

.eslintrc
.soliumrc.json
contracts/ColonyFunding.sol
contracts/ColonyNetwork.sol
contracts/ColonyNetworkAuction.sol
contracts/ColonyNetworkDataTypes.sol
contracts/ColonyNetworkStorage.sol
contracts/EtherRouter.sol
contracts/IColony.sol
contracts/PatriciaTree/IPatriciaTree.sol
contracts/ReputationMiningCycleDataTypes.sol
contracts/ReputationMiningCycleRespond.sol
contracts/extensions/OldRolesFactory.sol
contracts/extensions/OneTxPaymentFactory.sol
contracts/testHelpers/TaskSkillEditing.sol
docs/_Interface_IColony.md
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/test/MaliciousReputationMinerWrongResponse.js

💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪💪
Definitely the most reasonable way to handle this.

Add trailing-whitespace rules to eslint and solium

---

package.json
test/contracts-network/colony-network-auction.js
yarn.lock

Greenkeeper/prettier 1.18.0

---

contracts/Colony.sol
contracts/ColonyAuthority.sol
contracts/ColonyNetwork.sol
contracts/IColony.sol
contracts/extensions/OldRoles.sol
docs/_Interface_IColony.md
test/contracts-network/colony-permissions.js

#630 and #646 weren't quite right; 3rd time's the charm!
This PR is the cherry-picked changes approved in #630 but reverted in #632, (and incorrectly restored in #646)

Revert Reverted Arbitration role (the correct way)

---

package.json
scripts/check-auth.js
yarn.lock

Closes #653 
Fixes a [breaking change](https://github.com/federicobond/solidity-parser-antlr/blob/master/CHANGES.md#044) in the solidity parser.

Greenkeeper/solidity parser antlr 0.4.5

---

contracts/ColonyTask.sol
contracts/TokenLocking.sol

Playing catch up with MythX rules engine here

Fix nightly build

---

package.json
yarn.lock

chore(package): update eslint-plugin-flowtype to version 3.11.1

---

docs/_TLDR_Reputation.md

Fixes grammatical error in the reputation docs.

corrected a small typo

---

contracts/Colony.sol
contracts/IColony.sol
docs/_Interface_IColony.md
test/contracts-network/colony-permissions.js
yarn.lock

Add ability to get all domain roles of a user

---

package.json
yarn.lock

Closes #688. Not sure what the issue there was, ultimately - the coverage tests seemed to run three times, and never time out? Going to chalk it up to circle weirdness for now.

Greenkeeper/eth gas reporter 0.2.8

---

package.json
packages/reputation-miner/ReputationMiner.js
yarn.lock

Bump ganache-cli to 6.7.0

---

package.json
yarn.lock

Greenkeeper/eslint plugin flowtype 4.5.2

---

package.json
yarn.lock

Greenkeeper/eth gas reporter 0.2.14

---

contracts/ColonyTask.sol
test/contracts-network/colony-task-work-rating.js
test/contracts-network/reputation-update.js

Closes #753 
Not much to see here.

Change default rating from 3 to 2

---

package.json
yarn.lock

Closes #734 
Yeeeeeeeee!!!!!!!!
One million thanks @CruzMolina!

Greenkeeper/truffle 5.1.4

---

package.json
yarn.lock

Greenkeeper/truffle 5.1.8

---

package.json

chore(package): update eslint-plugin-prettier to version 3.1.2

---

package.json
yarn.lock

Closes #805. This build only failed / issue was only raised because Raul cancelled the build 😄

Bump eth-gas-reporter version

---

contracts/colony/ColonyFunding.sol
contracts/colony/IColony.sol
contracts/extensions/FundingQueue.sol
contracts/extensions/FundingQueueFactory.sol
docs/_Interface_IColony.md
docs/_Interface_IColonyNetwork.md
scripts/check-recovery.js
scripts/check-storage.js
test/extensions/funding-queue.js

Closes #807, #60, #62, #63, #64, #65, #66, #67, #68, #69, #70, #71, #72

Funding Queues

---

package.json
packages/reputation-miner/TruffleLoader.js
packages/reputation-miner/bin/index.js
packages/reputation-miner/package.json
packages/reputation-miner/patricia-test.js
test-gas-costs/gasCosts.js
test-system/end-to-end.js
test/contracts-network/colony-network-recovery.js
test/contracts-network/colony-reward-payouts.js
test/contracts-network/token-locking.js
test/reputation-system/client-calculations.js
test/reputation-system/client-core-functionality.js
test/reputation-system/client-sync-functionality.js
test/reputation-system/dispute-resolution-misbehaviour.js
test/reputation-system/disputes-over-child-reputation.js
test/reputation-system/happy-paths.js
test/reputation-system/reputation-mining-client/client-auto-functionality.js
test/reputation-system/root-hash-submissions.js
test/reputation-system/types-of-disagreement.js
yarn.lock

This PR removes the `@colony/colony-js-contract-loader-fs` package and factors it in as a file in the reputation miner

Factor in @colony/colony-js-contract-loader-fs

---

truffle.js

I was confused. Please see #860

Add option to disable docker if desired

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/IColony.sol
contracts/extensions/CoinMachine.sol
contracts/extensions/CoinMachineFactory.sol
docs/_Interface_IColony.md
docs/_Interface_IColonyNetwork.md
docs/_Interface_ITokenLocking.md
helpers/test-data-generator.js
helpers/test-helper.js
scripts/check-recovery.js
scripts/check-storage.js
test/extensions/coin-machine.js

Coin Machine is an experimental token-distributing mechanism which came out of a #research brainstorm. 
Essentially, it takes a duration of time, a number of periods, and a target token sale volume, and executes a series of token sales, with the price adjusting as a function of prior sale demand. 
Advantages of this mechanism are: stability of price during the sale period; a straightforward user experience (tokens are either available or "sold out"); the ability to adjust price to the market, albeit with a time delay.
Disadvantages of this mechanism are: periods of potential token unavailability; prices which may substantially lag the market.
Ultimately, we feel that as the originator of these tokens, we can accept the arbitrage costs introduced by price lags, in return for the increase …

Coin Machine

---

contracts/colony/ColonyDataTypes.sol
docs/_Interface_IColony.md

So far, fixes a single spelling error Raul has found in his preparation of the coding challenge, but it's reasonable he'd find more as he works through it, so leaving this open for a day or two in case he does.

Fix spelling error(s?)

---

contracts/colony/Colony.sol
contracts/colony/ColonyFunding.sol
contracts/colony/ColonyStorage.sol
test-smoke/colony-storage-consistent.js

Add tokenLockingAddress to ColonyStorage

---

package.json
yarn.lock

We were too keen with #870! My fix has already been released upstream, so we don't have to use my fork any more.

Move back to mainline solhint

---

contracts/extensions/ColonyExtension.sol
test/extensions/coin-machine.js
test/extensions/funding-queue.js
test/extensions/voting-rep.js

Add missing view to getDeprecated to indicate it is read-only

---

test/extensions/coin-machine.js

Test CoinMachine works if token is locked

---

packages/reputation-miner/bin/index.js
packages/reputation-miner/package.json

At some point, this changed and I didn't catch it.

Stop yargs converting addresses to large numbers

---

contracts/extensions/FundingQueue.sol
test/extensions/coin-machine.js
test/extensions/funding-queue.js
test/extensions/one-tx-payment.js
test/extensions/voting-rep.js

Test extensions function as intended when installed in subdomains only

---

.solcover.js
.solcover.reputation.js
contracts/colony/Colony.sol
contracts/colonyNetwork/ColonyNetworkExtensions.sol
helpers/constants.js
scripts/deployUnmockedColonyVersions.js
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-network-extensions.js

A few PRs need this (#929, #931) so I'm pulling it out as a separate PR.

Remove extension ordering requirement

---

contracts/extensions/CoinMachine.sol
contracts/extensions/FundingQueue.sol
contracts/extensions/TokenSupplier.sol
contracts/extensions/VotingReputation.sol
package.json
scripts/deployOldExtensionVersions.js
scripts/deployUnmockedColonyVersions.js
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-arbitrary-transactions.js
test/extensions/coin-machine.js
test/extensions/token-supplier.js
test/extensions/voting-rep.js
yarn.lock

Partially solves #319
Completes the slither updates by bringing extension code in line with best-practices.
On-hold until the frontend is ready to handle versioned extensions.

Fix slither for extensions

---

package.json
packages/kyc-oracle/.gitignore
packages/kyc-oracle/KycOracle.js
packages/kyc-oracle/TruffleLoader.js
packages/kyc-oracle/bin/index.js
packages/kyc-oracle/package-lock.json
packages/kyc-oracle/package.json
scripts/kyc-bootstrap.js
yarn.lock

Introduce a `KycOracle` service which reads data from an off-chain KYC service (such as Synaps) and writes it on-chain, using the `Whitelist` extension introduced in #931  (and which this is rebased off of).
Still a bit of a WIP since we haven't finished hammering out the Synaps-side flow, but this is basically what I'm thinking.

Create KycOracle package

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
helpers/constants.js
scripts/deployUnmockedColonyVersions.js
test-smoke/colony-storage-consistent.js

As of the last release we adopted a convention that we bump everything as soon as a release is made (as this make life easiest for the front-end team). So here it is! I *think* I got everything...

Bumps / cleanups / updates for next release

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/IColony.sol
contracts/extensions/VotingReputation.sol
contracts/tokenLocking/TokenLocking.sol
contracts/tokenLocking/TokenLockingDataTypes.sol
docs/_Interface_IColony.md
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-arbitrary-transactions.js
test/contracts-network/colony-staking.js
test/extensions/voting-rep.js

We jumped the gun on merging #965, so recreating it. Go read that PR for what this branch adds!

Four minor changes

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/ColonyDataTypes.sol
contracts/colony/ColonyExpenditure.sol
contracts/colony/ColonyStorage.sol
contracts/colony/IColony.sol
docs/_Interface_IColony.md
package.json
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-expenditure.js

Add setDefaultGlobalClaimDelay for Expenditures

---

contracts/extensions/VotingReputation.sol
test-smoke/colony-storage-consistent.js

Need to get better at this somehow...

Bump voting extension version

---

contracts/colonyNetwork/ColonyNetworkMining.sol
contracts/colonyNetwork/ColonyNetworkStorage.sol
contracts/colonyNetwork/IColonyNetwork.sol
contracts/extensions/CoinMachine.sol
contracts/reputationMiningCycle/ReputationMiningCycle.sol
contracts/reputationMiningCycle/ReputationMiningCycleBinarySearch.sol
contracts/reputationMiningCycle/ReputationMiningCycleCommon.sol
contracts/reputationMiningCycle/ReputationMiningCycleRespond.sol
contracts/tokenLocking/TokenLocking.sol
docs/_Interface_IColonyNetwork.md
helpers/test-helper.js
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/test/ReputationMinerTestWrapper.js
test-chainid/chainid-dependent-behaviour.js
test-gas-costs/gasCosts.js
test-smoke/colony-storage-consistent.js
test/contracts-network/reputation-basic-functionality.js
test/extensions/funding-queue.js
test/extensions/voting-rep.js
test/reputation-system/dispute-resolution-misbehaviour.js
test/reputation-system/disputes-over-child-reputation.js
test/reputation-system/happy-paths.js
test/reputation-system/root-hash-submissions.js
test/reputation-system/types-of-disagreement.js

Need to do this again, so that all the delegated mining stuff in the client lines up with other improvements that, as yet, are only in the client on the `develop` branch.

Merge master back in to develop

---

scripts/start-reputation-oracle.js

Turns out, the script needs to be run in the project root to work properly. While I was there I also added the `--processingDelay` flag to make dev turnaround times faster :)

Fix the reputation oracle local dev start script

---

package.json
truffle.js

Some useful changes to `truffle.js` to make the documentation easier to write

Changes to truffle.js for ease of instruction-giving

---

packages/package-utils/updateGasEstimate.js
packages/reputation-miner/ReputationMiner.js

The axios changes are an oversight from #1052, and should have been in there. The other changes are generic miner improvments.

Miner fixes/improvements

---

.gitignore
packages/reputation-miner/ReputationMiner.js
truffle.js

Some minor tweaks to sync the code with the docs, plus a bit more logging

Sync miner code with docs

---

contracts/colony/ColonyFunding.sol
contracts/extensions/CoinMachine.sol
package.json
slither.config.json

I want to come back and properly investigate some of these, but for now we just need our builds green again.

Exclude new mostly inappropriate slither detectors

---

docs/bug-bounty.md

Fix: typos

---

contracts/Migrations.sol
contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/ColonyRoles.sol
contracts/colony/ColonyTask.sol
contracts/colonyNetwork/ColonyNetwork.sol
contracts/colonyNetwork/ColonyNetworkAuction.sol
contracts/colonyNetwork/ColonyNetworkMining.sol
contracts/common/TokenAuthority.sol
contracts/metaTxToken/MetaTxToken.sol
contracts/patriciaTree/PatriciaTreeBase.sol
contracts/patriciaTree/PatriciaTreeProofs.sol
contracts/reputationMiningCycle/ReputationMiningCycle.sol
helpers/constants.js
test-smoke/colony-storage-consistent.js

Fixes issues the newest version of slither raises. This includes reentrancy risks inside loops, variables that could be immutable but weren't, and what I think I agree was an unnecessary external call to `version` in the `upgrade` function. Not convinced I've fixed these in the best possible ways, so open to suggestions.

Slither updates

---

contracts/common/Multicall.sol
test/contracts-network/colony.js

Stop nested multicalls

---

contracts/extensions/votingReputation/IVotingReputation.sol
contracts/testHelpers/VotingReputationMisaligned.sol
docs/interfaces/extensions/votingreputation.md
docs/quick-start.md

This PR fixes some tiny doc issues that I found along the way.

Tiny doc fixes and adjustments

---

contracts/extensions/StagedExpenditure.sol
migrations/9_setup_extensions.js
package-lock.json
scripts/check-recovery.js
scripts/check-storage.js
test-smoke/colony-storage-consistent.js
test/extensions/staged-expenditure.js

Replaces #1131, closes #1129 
~~Still to do: a test that shows a you can make a staged payment via staking~~

Staged expenditure standalone extension

---

contracts/common/BasicMetaTransaction.sol
test/contracts-network/colony.js

Rename argument for consistency

---

packages/package-utils/getFeeData.js

Continuing this saga... (last seen in #1195).
This change adds a floor for `maxPriorityFee`. This was deployed prior to Christmas, but in the rush it didn't get a PR afterwards, so here it is.

Add floor for gas fees in type 2 transactions

---

contracts/extensions/votingReputation/IVotingReputation.sol
contracts/extensions/votingReputation/VotingReputation.sol
docs/interfaces/extensions/votingreputation.md
test-smoke/colony-storage-consistent.js
test/extensions/voting-rep.js

Finalize motions changes to make estimateGas better

---

contracts/colonyNetwork/ColonyNetworkDeployer.sol
contracts/common/EtherRouterCreate3.sol
packages/metatransaction-broadcaster/Dockerfile
packages/package-utils/getFeeData.js
packages/reputation-miner/Dockerfile
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/bin/index.js
test/truffle-fixture.js

Capturing everything post-IMWSS that gets done before our branches are all sorted out.

Post-imwss tweaks

---

.circleci/config.yml
helpers/test-helper.js
packages/kyc-oracle/bin/index.js
packages/metatransaction-broadcaster/Dockerfile
packages/metatransaction-broadcaster/bin/index.js
packages/reputation-miner/Dockerfile
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/bin/index.js
scripts/mockBridgeMonitor.js
scripts/setup-bridging-contracts.js
test/cross-chain/cross-chain.js
test/extensions/voting-rep.js
test/packages/metaTransactionBroadcaster.js
test/reputation-system/reputation-mining-client/client-auto-functionality.js

We keep having issues with `package-lock.json`, this helps guards against this a bit. Note we don't do anything with the resulting images, we just check they build okay.

Try building docker images on CI

---

.solcover.js
hardhat.config.js

Bail on tests on first failure

---

contracts/extensions/StagedExpenditure.sol
test/extensions/staged-expenditure.js
test/extensions/voting-rep.js

Add agent to staged expenditure contract events

---

scripts/deployOldUpgradeableVersion.js
scripts/setupOldUpgradeableVersionHardhat.js

This has been requested for frontend dev in the CDapp. Unfortunately, not a simple copy-paste job, as this is the first version since we moved to `hardhat`.
I've not done a full impelmentation here - only as far as the frontend dev experience required.  The remaining implementation can come as-needed, as far as I am concerned, once we have tests or similar that require a version on hardhat.

Add a function to deploy IMWSS

---

.circleci/config.yml
scripts/deployOldUpgradeableVersion.js

Add nvm/fnm support for deployOldUpgradeableVersion
