JoinColony/colonyNetwork

.eslintrc

We don't use flow, but we want to keep using eslint-config-colony.
So we're disabling it for all javascript files.
Builds weren't broken (this is only a warning), but disabling it stops everyone's client looking like this:

Disable requiring flowtype annotations

---

circle.yml
contracts/Colony.sol
contracts/ColonyFunding.sol
contracts/ColonyNetwork.sol
contracts/ColonyNetworkStaking.sol
contracts/ColonyNetworkStorage.sol
contracts/IColony.sol
contracts/IColonyNetwork.sol
gasCosts/gasCosts.js
helpers/test-data-generator.js
helpers/test-helper.js
helpers/upgradable-contracts.js
migrations/2_deploy_contracts.js
migrations/3_setup_colony_network.js
package.json
test/colony-network-staking.js
test/colony-task-work-rating.js
test/colony.js
test/reputation-update.js
yarn.lock

Closes #56. The functionality removed from #56 can be found in #164. 
Adds the skeleton for #49 and #50 - currently dispute resolution is mocked by a simple function call `invalidateHash`.
* Implements everything, I think, from #47, save for
>  Miners will also be required to have staked their tokens for a few update cycles before they are eligible to submit or support a hash.
* Reimplements some of #43 (see below)
This PR introduces the concept of staking colony tokens, which then allows their owners to take part in the reputation mining process. I include a skeleton of the dispute process, though the disputes are not actually validated - as mentioned, a call to `invalidateHash` is used to 'time out' an opponent.
The first change to existing functionality is that there are now two …

Introduce staking and submission of Reputation Root Hashes, with skeleton of dispute mechanism

---

contracts/ColonyFunding.sol
contracts/ColonyStorage.sol
contracts/ColonyTask.sol
gasCosts/gasCosts.js
helpers/constants.js
helpers/test-data-generator.js
helpers/test-helper.js
helpers/upgradable-contracts.js
migrations/3_setup_colony_network.js
migrations/4_setup_colony_version_resolver.js
test/colony-funding.js
test/colony-network-staking.js
test/colony-network.js
test/colony-task-work-rating.js
test/colony.js
test/common-colony.js
test/reputation-update.js
test/router-resolver.js
test/token.js
upgrade-test/colony-network-upgrade.js
upgrade-test/colony-upgrade.js
upgrade-test/token-upgrade.js

- Moved role constants to ColonyStorage.
- Using es6 exports.
- Passing object instead of list to `setupAssignedTask `, `setupFundedTask `, `setupRatedTask `..

ES6 exports, storage constants, helper functions arguments

---

circle.yml
gasCosts/gasCosts.js
package.json
truffle.js
yarn.lock

Gas cost tests were switched to `ganache-cli` as time forward functionality is not available in parity yet. Additionally private key extraction of test accounts is easier. 
We also make use of  `eth-gas-reporter` to report on gas costs as this provides better reporting (screenshot below) and simplifies our tests. We may consider running it against the entire test suite under `/test`, rather than just the limited `gasCosts` tests in future when the performance is improved. Currently this is prohibitive.

Gas cost tests refactoring to use eth-gas-reporter

---

contracts/ColonyNetwork.sol
contracts/IColonyNetwork.sol
gasCosts/gasCosts.js
migrations/5_setup_common_colony.js
test/colony-funding.js
test/colony-network.js
test/colony-task-work-rating.js
test/colony.js
test/common-colony.js
test/reputation-update.js
upgrade-test/colony-network-upgrade.js
upgrade-test/colony-upgrade.js

Closes #160
- Token is no longer created inside `createColony` function. Token address is passed instead.
Checking if token has ERC20 interface is not implemented in this task.

Allow colonies to be created with existing tokens

---

contracts/ColonyNetworkAuction.sol
contracts/ColonyStorage.sol
contracts/ColonyTask.sol
contracts/IColonyNetwork.sol
helpers/test-helper.js
helpers/upgradable-contracts.js
migrations/2_deploy_contracts.js
migrations/3_setup_colony_network.js
test/colony-network-auction.js
test/colony-network-staking.js
test/colony.js

Closes #97 
Implements Dutch auction model for auctioning tokens earned by the Common Colony in exchange for CLNY. The auction model is inspired by a version of that used at [Raiden](https://github.com/raiden-network/raiden-token/blob/master/contracts/auction.sol) and earlier at [Gnosis](https://github.com/miladmostavi/gnosis-contracts/blob/master/contracts/solidity/DAO/DAODutchAuction.sol) ICOs.
The following auction rules apply:
- A new Auction is started via the `colonyNetwork.startTokenAuction` function which creates a new 
`DutchAuction` instance for a given Token X. Note that **ALL Token X** owned by the ColonyNetwork is transferred to the Auction contract here for selling.
- Auction is explicitly started via the `start` function where the `startTime`, `quantity` of token sold are …

Colony network run Token auctions

---

contracts/ColonyStorage.sol
contracts/ColonyTask.sol
contracts/EtherRouter.sol
contracts/IColony.sol
contracts/Resolver.sol
helpers/test-helper.js
helpers/upgradable-contracts.js
parity-genesis.template.json
test/colony.js
test/common-colony.js
test/router-resolver.js
test/token.js
upgrade-test/colony-network-upgrade.js
upgrade-test/colony-upgrade.js
upgrade-test/token-upgrade.js

- Use `returndatasize` and `returndatacopy` opcodes introduced in Byzantium hard fork which give us access to the size of the return data for a call
http://solidity.readthedocs.io/en/v0.4.21/assembly.html#opcodes 
This also simplifies the `Resolver` requirements as we no longer need to track return data size for functions.
- Byzantium EIPs are allowed in prity config
- Since the above is now possible we've extended the `getTask` function to return the task domains and skills too instead of relying on recursive calls to `getTaskDomain` and `getTaskSkill` both of which have been removed. 
- Task model has been switched to use a single domain only.
- We remove leftover storage variables from `ColonyStorage` related to the old method of reviewing task updates.

Use EtherRouter for functions with dynamic return data size

---

contracts/Colony.sol
contracts/ColonyStorage.sol
contracts/IColony.sol
helpers/test-helper.js
test/colony.js

Closes #40
Added function for bootstrapping the colony.
- Function expects array of addresses and amount of reputation/tokens for every address.
- Function can be called:
- Only by the authorized address
- When the colony is in 'bootstrap phase' i.e. when `taskCount` is `0`.
- Reputation is assigned in the root domain.
- It is assumed that there is enough tokens to be transferred.
***Updated**

Bootstrapping reputation

---

contracts/Authority.sol
contracts/Colony.sol
contracts/ColonyFunding.sol
contracts/ColonyNetwork.sol
contracts/ColonyNetworkAuction.sol
contracts/ColonyNetworkStaking.sol
contracts/ColonyNetworkStorage.sol
contracts/ColonyStorage.sol
contracts/ColonyTask.sol
contracts/ERC20Extended.sol
contracts/EtherRouter.sol
contracts/IColony.sol
contracts/IColonyNetwork.sol
contracts/Migrations.sol
contracts/ReputationMiningCycle.sol
contracts/Resolver.sol
contracts/SafeMath.sol
contracts/Token.sol
package.json
yarn.lock

Upgrades contracts to [`solc 0.4.21`](https://github.com/ethereum/solidity/releases/tag/v0.4.21)
Upgrades related packages: [`truffle`](https://github.com/trufflesuite/truffle/releases/tag/v4.1.5), [`solidity-parser-antlr`](https://github.com/federicobond/solidity-parser-antlr/commit/2dc25a29b4c1f426a300dd57a92800df814aae70), [`solium`] (https://github.com/duaraghav8/Solium/releases/tag/v1.1.6) and `solidity-coverage` to `0.5.0` which move to solc 0.4.21 and add support for new log `emit` keyword in Solidity.
Also https://github.com/trufflesuite/truffle-migrate/pull/18 is fixed by the version upgrade here

Upgrades contracts to solc 0.4.21

---

contracts/ColonyFunding.sol
contracts/ColonyStorage.sol
contracts/IColony.sol
gasCosts/gasCosts.js
helpers/test-helper.js
migrations/2_deploy_contracts.js
test/colony-funding.js

Closes #95 
Storage variables:
- Global reward payout counter - `globalRewardPayoutCount`
- Active reward payouts - `activeRewardPayouts`
- User reward payout counter mapping - `userRewardPayoutCount`
- Reward payout cycles mapping - `rewardPayoutCycles`
Implemented functions for:
- starting the payout cycle - `startNextRewardPayout`
- claiming reward payout - `claimRewardPayout`
- waiving reward - `waiveRewardPayout`
- moving remaining funds after payout - `moveRemainingRewardPayoutFunds`
- getting the info about payout - `getRewardPayoutInfo`
Takes one argument: token address
Saving all the necessary data to `rewardPayoutCycles` (current root hash, current total tokens, reward pot balance, token, current block number).
Incrementing `globalRewardPayoutCount` and using it for mapping key. …

Claiming Rewards from the Reward Pot

---

contracts/ColonyTask.sol
contracts/IColony.sol
gasCosts/gasCosts.js
helpers/test-data-generator.js
helpers/test-helper.js
test/colony.js

While testing the MultiSig implementation @JamesLefrere and I encountered that the ecsign method used in createSignatures (in test-helpers.js) works differently from the ones used by web3 or ethers (or any wallet implementation, really). The latter prepend a prefix `("\x19Ethereum Signed Message:\n" + len(message))` to the message hash which is to sign, while the former does not. The prefix can also be found in the ERC191 specification: https://github.com/ethereum/EIPs/issues/191.
In order to add support across all wallets (including MetaMask and Hardware wallets) we should use this method of signing as it's the only one those support.
The proposed change fixes the MultiSig (executeTaskChange) for us when using it in the browser (with an ethers wallet), although it breaks a whole lot of …

Sign messages in a way that real-world wallets expect

---

contracts/ColonyFunding.sol
contracts/ColonyTask.sol
contracts/IColony.sol
helpers/test-data-generator.js
test/colony-funding.js
test/colony-network-staking.js
test/reputation-update.js

Closes #193 
Changes include:
- Due to stack depth error, removed `taskExists ` modifier.
- Updating reputation in task domain skill id instead of domain id, and changed the tests accordingly.
- Improved variable names in tests for reward payouts.
- By changing the skill id for the reputation update, one more reputation key was added in client. This will result changing [this](https://github.com/JoinColony/colonyNetwork/pull/202/files#diff-9e591fc7c2149015d27fb59bfd304eacR1359) line from 4 (manager, worker, evaluator, last log for disputes) to 5 (manager, worker **skill** and **domain**, evaluator, last log for disputes)

Updating reputation in task domain skill id instead of domain id

---

contracts/Colony.sol
contracts/ColonyFunding.sol
contracts/ColonyNetwork.sol
contracts/ColonyNetworkAuction.sol
contracts/ColonyNetworkStaking.sol
contracts/ColonyNetworkStorage.sol
contracts/IColony.sol
contracts/IColonyNetwork.sol
gasCosts/gasCosts.js
helpers/test-data-generator.js
migrations/5_setup_meta_colony.js
test/colony-funding.js
test/colony-network-auction.js
test/colony-network-staking.js
test/colony-network.js
test/colony-task-work-rating.js
test/colony.js
test/meta-colony.js
test/reputation-update.js
test/router-resolver.js
upgrade-test/colony-network-upgrade.js
upgrade-test/colony-upgrade.js
yarn.lock

Here we remove 1 of the 3 mappings of colony addresses in storage which held a colony bytes32 "key" mapping. This has been depreciated as a legacy feature in favour of the colony index which can be used instead to uniquely identify a colony, similarly to the task index.
Additionally the "Common Colony" has been renamed to "Meta Colony" to make clearer its purpose.
Also I've slipped in an update to the lockfile which I forgot in https://github.com/JoinColony/colonyNetwork/pull/204/

Remove Colony name from storage and rename "Common Colony" to "Meta Colony"

---

.gitmodules

For [various](https://github.com/gflags/gflags/issues/112) [reasons](https://github.com/ESROCOS/ilk-generator/issues/1) people have trouble to setup a project properly with the submodule remote url being defined using the ssh method.
This was the initial issue in the gitter chat: https://gitter.im/JoinColony/colonyNetwork?at=5b0e1c2ec712f56125428daf
This change should not have any negative effect and help people in "hostile" environments or beginners to be able to set up this project.
As discussed with @area.

Switch to https for dappsys submodule

---

contracts/ColonyNetworkStaking.sol
contracts/ColonyTask.sol
contracts/PatriciaTree/Data.sol
contracts/PatriciaTree/PatriciaTreeProofs.sol
contracts/ReputationMiningCycle.sol
contracts/Resolver.sol
package.json
yarn.lock

As well as preparing us further for solidity 0.5.0, I believe this fixes the issues with Truffle being not very talkative when tests fail.

Upgrade truffle to 0.4.11

---

contracts/ReputationMiningCycle.sol
helpers/test-data-generator.js
packages/reputation-miner/ReputationMiner.js
test/colony-network-mining.js

If a user fails a task, the reputation they lose could exceed the reputation they have. Their reputation is not meant to become negative, but instead become zero and no lower. This PR introduces this behaviour, where previously the client would attempt to mine a negative reputation and fail.
Similarly, if a user had a lot of reputation (or received a very large payout), their reputation could overflow. This caps their reputation at `2**256 - 1`, which is the largest value able to be represented in `uint256`.

Prevent reputation overflows or underflows

---

contracts/Colony.sol
contracts/ColonyTask.sol
packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/bin/index.js
test/colony.js
test/meta-colony.js

If there's going to be a public instance of the network anywhere, we need to make sure that people can't mess it up. This adds permissions to 
* `addGlobalSkill` (colony owner only, and only works from metaColony, so effectively only the metaColony's owner)
* `addDomain` (colony owner only)
* `setTaskRoleUser`, `setTaskDomain`, `setTaskSkill` are now restricted to the manager of the task.
I also took the opportunity to fix a couple of issues floating around in the reputation miner that I needed fixed.

Add a few permissions and fix oracle server errors

---

packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js

Not sure anyone cares about these changes other than me... everything works as before, we're just a bit more accommodating of the real world.
Context for the one meaningful change: sometimes, when using Infura, the 'confirm' tx would error with 'replacement transaction too cheap' or similar error message. That suggests that it's using the same nonce for both the 'confirm' and the previous 'submit' transaction, which in turn I hypothesize is because the relevant block hasn't broadcast to all of infura's nodes yet, and we happen to query a node that hasn't seen the block with the 'submit' transaction in yet.
Not really something we can test, but my best guess for now. I will continue to keep an eye on the reputation miner.

Minor miner changes because the world is imperfect

---

contracts/ColonyFunding.sol
contracts/ColonyTask.sol
contracts/IColony.sol
test/colony.js

This PR relates to #188. Increasing the amounts of events emitted during the task workflow allows for increased granularity of the whole process and enables further integrations with the contracts, especially in regard to the following use cases:
* Live updates of changes on tasks in the Colony dApp, e.g., if the worker's payout changed.
* Further integrations when using the JavaScript client, [`colonyJS`](https://github.com/JoinColony/colonyJS). This comes in handy when having the upcoming [Colony hackathon](https://colony.io/hackathon/) in mind. Participants could easily integrate third-party services and have data synchronized in real-time.
I added 8 events to `ColonyTask` and `ColonyFunding` that give updates within a worker's perspective:
* `TaskBriefChanged(uint256 indexed id, …

Add events for more granularity during task changes

---

contracts/ColonyStorage.sol
contracts/ColonyTask.sol
contracts/IColony.sol
gasCosts/gasCosts.js
helpers/test-data-generator.js
helpers/test-helper.js
test/colony.js

Closes #192 
There is still the limitation that there can only be 1 ongoing change per task as there is one _current_ nonce per task.
In addition here we implement logic to support task changes signed by one reviewer only for cases where:
1) second reviewer role user has not been assigned yet. e.g. a worker hasn't been assigned and the manager wants to change the task brief or due date
2) The same user is assigned to both roles, i.e. evaluator and manager are the same person 
We have also aligned the implementation with the original to depreciate `.call` as a result of https://github.com/ethereum/solidity/issues/2884 https://github.com/christianlundkvist/simple-multisig/commit/e010fbbe67c1237f574f1edbfdb64388cff0de24

Task change nonce becomes task specific

---

helpers/constants.js
test/colony.js
upgrade-test/colony-upgrade.js

Replaces sample IPFS hashes with examples matching the expected format.
e.g. the `base58` decoded, `bytes32` converted `hex` value of a sample ipfs hash `QmNSUYVKDSvPUnRLKmuxk9diJ6yS96r1TrAXzjTiBcCLAL` is `0x017dfd85d4f6cb4dcd715a88101f7b1f06cd1e009b2327a0809d01eb9c91f231`

Use actual bytes32 hex encoded ipfs hash in tests

---

contracts/ColonyStorage.sol
contracts/ColonyTask.sol
contracts/IColony.sol
helpers/constants.js
test/colony-funding.js
test/colony-network-mining.js
test/colony-task-work-rating.js
test/reputation-update.js

Closes #154 
- Switch to 3-point scale with corresponding [-1, 1, 1.5] reputation boost.
- Evaluator receives Satisfactory rating by default.
- Scale implemented as enum, meaning `role.rated` boolean is no longer needed.
- **However, we repurpose the storage slot to `role.rateFail`**, set to `true` if the user does not rate their counterpart (set in `assignWorkRating`).
- Reputation calculation moved into a separate (internal, pure) function of `(payout, rating, rateFail)`.
- Update tests to specify ratings on the 1-3 point scale.
- Update tests to conform to usage of `TaskRatings` enum and `rateFail` boolean.
- Update tests with new rating and reputation values.

Implement three-point ratings

---

docs/_Docs_GetStarted.md

This adds the colonyNetwork-relevant instructions for running the usable mining client for local development to the 'Get Started' doc page. 
Needed for colonyJS#177

Add content for running the usable reputation mining client.

---

.eslintignore
packages/colony-js-contract-loader-network/package.json
packages/colony-js-contract-loader-network/src/NetworkLoader.js
packages/colony-js-contract-loader-network/src/__tests__/NetworkLoader.test.js
yarn.lock

This PR makes a small change to the loader so that the selected networkId (set in the loader instance) is supplied to the transform function. This makes it possible to find the address for the selected network automatically when loading the contract.

Supply the selected network ID to the loader (`colony-network-contract-loader` package)

---

contracts/ColonyFunding.sol
contracts/ColonyStorage.sol
contracts/ColonyTask.sol
contracts/IColony.sol
test/colony-funding.js
test/colony-task-work-rating.js
test/colony.js

Closes #232 
- If a user has done Unsatisfactory work, `claimPayout` will be a no-op (instead of raising an exception).
- Ratings for all users are guaranteed to be set after `finalizeTask` has been called. The rating for the evaluator will not be set before then.
- The `task.totalPayouts` field is deprecated and replaced by the `getTotalTaskPayout()` function which calculates the total payout dynamically based on the individual role payouts. This eliminates the need to synchronize two variables (and avoids paying the SSTORE gas cost of setting a redundant variable). Instead, we pay the price for a ~relatively cheap loop.

Improve payout accounting

---

contracts/Colony.sol
contracts/ColonyStorage.sol
contracts/ColonyTask.sol
contracts/IColony.sol
helpers/test-data-generator.js
helpers/test-helper.js
test/colony.js

Closes #243
This PR consolidates the new domain/pot logic into a private function `initialiseColony(skillId)` and adds `DomainAdded` and `PotAdded` events. 
It also adds some test coverage for initialising the root domain for a new Colony, and a new test helper (`expectAllEvents`).

Add DomainAdded/PotAdded events

---

contracts/Authority.sol
contracts/Colony.sol
contracts/ColonyFunding.sol
contracts/ColonyNetwork.sol
contracts/ColonyStorage.sol
contracts/ColonyTask.sol
contracts/IColony.sol
contracts/IColonyNetwork.sol
gasCosts/gasCosts.js
helpers/test-data-generator.js
helpers/test-helper.js
test/colony-funding.js
test/colony-network.js
test/colony.js
test/meta-colony.js
upgrade-test/colony-upgrade.js

- `ownerRole` - One person. Creator of the colony. Can call `setToken`, `bootstrapColony`, `mintTokens`, `addGlobalSkill`, `removeAdminRole`, plus all functions that admin can call.
- `adminRole` - has permission to call `setAdmin`, `moveFundsBetweenPots`, `addDomain`, `makeTask`, `cancelTask`, `startNextRewardPayout`.
- Member - can only call public functions that don't require auth.
Task level permission (as discussed with Pat, we should be the one to decide what those should be):
- `setTaskSkill` - Since worker is going to receive the reputation in this skill, should be agreed with manager and worker.
- `setTaskDomain` - Manager.
- `setTaskBrief` - Agreed between manager and worker.
- `setTaskDueDate` - Agreed between manager and worker.
- `finalizeTask` - Can only be called by a …

Roles and permissions

---

.circleci/config.yml
contracts/PatriciaTree/Data.sol
contracts/PatriciaTree/PatriciaTree.sol
helpers/patricia.js
package.json
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/patricia-test.js
packages/reputation-miner/patricia.js
test/colony-network-mining.js

Closes #246 
- Create a Solidity-equivalent Patricia tree in Javascript.
- Add `useJsTree` to ReputationMiner config to decide which implementation to use.
- Set tests to use the Javascript equivalent by default.

Create Solidity-equivalent PatriciaJs

---

contracts/ColonyTask.sol
contracts/IColony.sol
test/colony-task-work-rating.js
test/colony.js

This PR extends the work done in #216, and addresses the changes discussed in #188.
I propose two new events for tasks: `TaskDeliverableSubmitted` and `TaskWorkRatingRevealed`. Each is covered with tests. Having these events implemented allows for keeping track of the whole task lifecycle, whereas #216 focused more on change in (meta) data and finalization.

Add contract events for deliverable submission and rating revelation

---

contracts/ColonyNetwork.sol
contracts/ColonyNetworkStaking.sol
contracts/IReputationMiningCycle.sol
contracts/ReputationMiningCycle.sol
gasCosts/gasCosts.js
migrations/5_setup_meta_colony.js
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/test/MaliciousReputationMinerWrongNewestReputation.js
packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
test/colony-network-mining.js
test/colony-network.js
test/meta-colony.js
test/reputation-update.js

I guess this is part of #51, though the description there is woefully out of date (Patricia/Merkle)
This PR adds colony-wide reputation totals to the reputation state tree, as well as updating all parent reputations (both colony-wide totals of the parent reputations, and for the user's reputation) as appropriate. It also tests that disputes in these reputations are resolved successfully.
It also adds a special 'mining skill' to the metacolony. This is a little unusual for a skill, as it is a local skill that is not associated with a domain, but... I think that's most appropriate? Open to discussion on that. Otherwise, my implementation to date meant that this was pretty straightforward to add!
The same will not be true for child reputation updates...

Add parent reputations and colony-wide reputations to reputation state tree

---

contracts/ColonyFunding.sol
contracts/IColony.sol
gasCosts/gasCosts.js
helpers/test-helper.js
test/colony-funding.js

Fixed a bug where user was able to pass denominator smaller than the correct value, therefore maximizing his reward and draining reward pot.

Fix denominator constraint

---

.eslintrc
.soliumrc.json
contracts/Authority.sol
contracts/Colony.sol
contracts/ColonyFunding.sol
contracts/ColonyNetwork.sol
contracts/ColonyNetworkAuction.sol
contracts/ColonyNetworkStaking.sol
contracts/ColonyNetworkStorage.sol
contracts/ColonyStorage.sol
contracts/ColonyTask.sol
contracts/IColony.sol
contracts/IReputationMiningCycle.sol
contracts/PatriciaTree/IPatriciaTree.sol
contracts/PatriciaTree/PatriciaTreeProofs.sol
contracts/ReputationMiningCycle.sol
packages/reputation-miner/patricia.js

Changes include:
- Refactored Authority contract to avoid stack depth error
- Removed unused imports
- Fixed compile and solium warnings such as:
- line length
- formating of more than 5 function arguments
- unused function arguments
- etc.
There are solium warnings for experimental features, im not sure if its safe to remove these.
Solc warnings for external libraries will unfortunately stay: https://github.com/ethereum/solidity/issues/2675

Compile warnings

---

contracts/IColony.sol
contracts/IColonyNetwork.sol
contracts/IReputationMiningCycle.sol
contracts/ITokenLocking.sol
contracts/PatriciaTree/IPatriciaTree.sol

This PR makes some alterations to the interface contracts in order to specify the names of all function returns. One benefit of this is that the ABI now receives the return variable names, which makes making sense of returned values simpler.
The difference in the truffle artifact generated looks like this:
**Other changes**
* NatSpec `@return` entries now reference the relevant variable name
* Remove a NatSpec return variable which does not exist in the underlying function for the interface contract (`getRewardPayoutInfo`)
* `startNextRewardPayout` appears to have no return value; remove this from the interface

Specify return variable names for functions with public interfaces

---

contracts/Colony.sol
contracts/ColonyStorage.sol
contracts/IColony.sol
test/colony.js
test/meta-colony.js

Closes #266 
Also fixes a test issue using invalid skill id https://github.com/JoinColony/colonyNetwork/blob/develop/test/meta-colony.js#L372

Improve adding domains

---

contracts/ColonyNetworkAuction.sol
contracts/ColonyNetworkStorage.sol
test/colony-network-auction.js

Closes #185 
- Make auction start immediately upon creation
- Only allow auctions to be started at most once a month (per token)

Only allow auctions to be started at most once a month per token

---

.circleci/config.yml

Continuing attempts to make GK update the package lockfile in its PRs. This time we're potentially fixing the issue of GK requirement that it is the first job to be run and exiting before successful lockfile upload with `Only running on first push of a new branch` , example in  https://circleci.com/gh/JoinColony/colonyNetwork/2411
To ensure it is the first job to be run, we isolate the GreenKeeper updates using [sequential job execution](https://circleci.com/docs/2.0/workflows/#sequential-job-execution-example) to ensure the job that runs `greenkeeper-lockfile` is always executed first.
Solution inspired by https://github.com/greenkeeperio/greenkeeper-lockfile/issues/50
Resulting workflow build https://circleci.com/workflow-run/2cf9a44a-b22a-450c-a8a5-81114a67098a
Additionally we make …

Make GreenKeeper lockfile updates strictly execute first in CI

---

package.json
yarn.lock

The GK lockfile update saga continues.. 
Now `greenkeeper-lockfile-update` is failing because the pre-commit hooks are not setup on CI and when GK tries to `git commit` the lock file update it fails, see: https://circleci.com/gh/JoinColony/colonyNetwork/2540#build-parameters/containers/0
Here, similarly to how we do pre-commit hooks in other JoinColony repos, we add `husky` which by default does not run pre-commit hooks in CI
https://github.com/typicode/husky/blob/41be7d87497399e8ffec7a1b2d54123b4ca84a70/src/installer/index.ts#L152

Add husky package and move pre commit hooks to that

---

contracts/ColonyNetwork.sol
contracts/ColonyNetworkStorage.sol
contracts/ColonyStorage.sol
contracts/IColonyNetwork.sol
contracts/ReputationMiningCycle.sol
test/colony-network.js
test/meta-colony.js

Closes #249 
Ignore the atrocious branch name 😋 
- Add a `isGlobalSkill` boolean flag as the 3rd return value of `ColonyNetwork.getSkill` so users do not need to make an additional call to `isGlobalSkill`

Return isGlobalSkill boolean flag in ColonyNetwork.getSkill

---

test/colony-network-mining.js

Not sure why we did it like this originally, there was no need, as a CLNY instance is deployed alongside everything already.
However, by doing it like that, if you tried to use `it.only` on a mining test (that used a real client), you'd get errors because `reputationMiningCycle` is now instantiated with the CLNY address, rather than (effectively) looking it up from `ColonyNetwork` every time.
Now, `it.only` will work again with all of the tests in this file.

Use existing CLNY contract at start of mining test

---

docs/CONTRIBUTING.md

Update contributing docs to respect the move from "Colony Network Token Sale MVP Backlog" GH milestone to "Colony Contribute Backlog" GH project as we need to free up the issue milestone field for Zenhub.

Change contributing docs with updates to milestone

---

contracts/IReputationMiningCycle.sol
contracts/ReputationMiningCycle.sol
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/test/MaliciousReputationMinerExtraRep.js
packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
test/colony-network-mining.js

Closes #54. Implements decays element of https://github.com/JoinColony/colonyNetwork/issues/51
An important part of reputation is that it decays over time, by about 0.5 every three months. This is the approximate rate described in the whitepaper, though the constant defined there was based on blocks, and so is not equal to what has been used here (which is the solution to `x**(24*30*4) = 0.5`).
Decays of very large reputations are calculated differently from other reputations to avoid overflows yet maintain as much precision as possible for small overflows.
Decay calculations are done in the order of ascending UID that the reputations have in the reputation state.
The structure of the Reputation Miner has been altered slightly to treat reputation decays and updates from the reputation log …

Introduce reputation decay

---

.circleci/config.yml
.solcover.js
contracts/ColonyStorage.sol
gasCosts/gasCosts.js
helpers/constants.js
helpers/test-data-generator.js
helpers/test-helper.js
helpers/upgradable-contracts.js
migrations/2_deploy_contracts.js
migrations/4_setup_colony_version_resolver.js
migrations/5_setup_token_locking.js
migrations/6_setup_meta_colony.js
migrations/7_setup_ens_registry.js
package.json
parity-genesis.template.json
scripts/start-blockchain-client.sh
test/colony-funding.js
test/colony-network-auction.js
test/colony-network-mining.js
test/colony-network.js
test/colony-task-work-rating.js
test/colony.js
test/meta-colony.js
test/reputation-update.js
test/router-resolver.js
test/token-locking.js
truffle.js
upgrade-test/colony-network-upgrade.js
upgrade-test/colony-upgrade.js
yarn.lock

Choosing to do an early upgrade as that has a number of features we probably can't live without for the production ready mvp of the network including:
- support for revert reason strings - we can watch/test for error reasons 🎉 
- support for function overloads - we can have as many combinations of the `makeTask` function inputs as we like, ref #251 
- choosing the `solc` version to compile with rather that the hard fixed version that truffle gives us. This decoupling gives us a lot of freedom
- `truffle-contract` which is used in testing is upgraded to `web3v1`
Plus a number of other really nice to have updates like docker support for faster tests and events emitter interface and probably more I haven't yet discovered.
Early release notes I am following for this upgrade, kindly provided …

Upgrade to Truffle v5

---

greenkeeper.json
package.json
packages/colony-js-contract-loader-network/package.json
packages/reputation-miner/package.json
yarn.lock

The reason why greenkeeper wasn't updating `@colony/colony-js-contract-loader-fs` is because we set a version `^1.3.0` which would cover everything to version `2.0.0`.
I set the version to be exact, so we will get PR from greenkeeper on every patch update.
Question: Is there any reason why `@colony/colony-js-contract-loader-fs` is not in `devDependencies`?

Updated contract loader to exact version 1.5.4

---

helpers/test-helper.js
package.json
test/colony-network-mining.js
yarn.lock

`next.9` upgrades web3 to `beta.35`. They changed the way the `status` field on the receipt is formatted from hex number to boolean. Just couple places in one of the test helpers where this value is checked directly - have updated those.
And `getNodeInfo` is available so have re-enabled the client check for `forwardTime`.

Upgrade truffle to next.9

---

.circleci/config.yml
package.json
yarn.lock

Closes #310
Also trigger husky install manually due to https://github.com/typicode/husky/issues/227

chore(package): update ganache-cli to version 6.1.8

---

contracts/ColonyNetworkMining.sol
contracts/IColonyNetwork.sol
migrations/6_setup_meta_colony.js
test/colony.js
test/meta-colony.js
test/reputation-update.js

Due to this function starting to run out of block gas limit we've had to split it in two. More details on where the issue was identified first:
https://github.com/JoinColony/colonyNetwork/pull/295#discussion_r208863960

Split `startNextCycle` into two functions

---

package.json
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/package.json
packages/reputation-miner/patricia-test.js
packages/reputation-miner/patricia.js
packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
test/colony-network-mining.js
yarn.lock

This upgrade is required to have access to [the defaultBlock parameter in ethers](https://github.com/ethers-io/ethers.js/issues/226), which in turn I want for #301. While doing this upgrade, I took the time to go through the mining client and excise as many references to vanilla bn.js as possible. Ethers uses a wrapped version of bn.js with limited functionality visible, and passing backwards and forwards between these types resulted in a lot of nested `new BN(x.toString())` all over the place. I have removed as much of that clutter as I can and the majority of the mining client is now a lot clearer to understand. We also no longer have to use e.g. `add` and `addn` - `add` on the ethers BN takes either an ethers BN or a Number.
Remaining things that are not-ideal, but either cannot be …

Upgrade ethers to v4 Beta

---

.soliumrc.json
contracts/Colony.sol
contracts/ColonyFunding.sol
contracts/ColonyNetwork.sol
contracts/ColonyNetworkAuction.sol
contracts/ColonyNetworkMining.sol
contracts/ColonyNetworkRegistrar.sol
contracts/ColonyNetworkStorage.sol
contracts/ColonyStorage.sol
contracts/ColonyTask.sol
contracts/PatriciaTree/Bits.sol
contracts/PatriciaTree/Data.sol
contracts/PatriciaTree/PatriciaTree.sol
contracts/ReputationMiningCycle.sol
contracts/SafeMath.sol
contracts/TokenLocking.sol
contracts/ens/ENSRegistry.sol
helpers/test-helper.js
test/colony-funding.js
test/colony-network-auction.js
test/colony-network-mining.js
test/colony-network.js
test/colony-task-work-rating.js
test/colony.js
test/meta-colony.js
test/reputation-update.js
test/token-locking.js

Closes #201 
Error messages are prefixed with `colony-`, `colony-reputation-mining` and `colony-task` to identify better the error source. 
`solium` rules for missing error messages as well as long lines are switched to errors to force us to use revert errors going forward. It helps avoid false positives in tests and makes debugging much easier.

Add contract and test error messages

---

contracts/Authority.sol
contracts/ColonyFunding.sol
contracts/ColonyTask.sol
contracts/IColony.sol
helpers/test-data-generator.js
test/colony.js

Closes #251 
- Extend `makeTask` to take optional `_skillId` and `_dueDate` arguments. Passing 0 results in a no-op.
- Add `setAllTaskPayouts` to allow manager to set payouts before new evaluator or worker is assigned.
Initial issue asked for all functionality to be available in one go, but there were some limitations:
- Task funding logic lives separately from task creation logic, so you cannot call `setXPayout` functions from within `ColonyTask.sol`.
- Funding can be denominated in many tokens, so may need to call `setAllTaskPayouts` multiple times.
Having a bulk payout setting function alongside an extended `makeTask` seemed like a reasonable way to go.

Convenience methods for setting task properities

---

contracts/ColonyTask.sol
contracts/IColony.sol
gasCosts/gasCosts.js
helpers/test-data-generator.js
test/colony-funding.js
test/colony-network-mining.js
test/colony-task-work-rating.js
test/colony.js
test/meta-colony.js
test/reputation-update.js

Closes #296
SO:
- Automatically assign task creator as both manager and evaluator
- Create `submitTaskDeliverableAndRating` function which wraps `submitTaskDeliverable` and `submitTaskWorkRating`
- Make `assignWorkRating` an internal function and bundle it into a more general `finalizeTask`.
Will not create a combined `reassignTaskXRole` function now since it involves doing something fancy with signatures.

Refactoring task update calls

---

contracts/Authority.sol
contracts/Colony.sol
contracts/ColonyFunding.sol
contracts/ColonyStorage.sol
contracts/IColony.sol
gasCosts/gasCosts.js
packages/reputation-miner/ReputationMiner.js
scripts/generate-test-contracts.sh
test/colony-funding.js
test/colony.js
test/token-locking.js

Unexpected changes include:
- Refactored `claimRewardPayout` to avoid stack depth error
- Proving colony wide reputation inside `startNextRewardPayout` to avoid too many function arguments.

Proving reputation in reward payouts

---

contracts/ColonyNetworkMining.sol
contracts/IColonyNetwork.sol
helpers/test-helper.js
package.json
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/package.json
test/colony-network-mining.js
yarn.lock

Closes #301, adds the functionality that will be used to make the 'ideal' scenario in #302 come to fruition.
This PR add a new event that is emitted when a mining cycle completes: `ReputationMiningCycleComplete(bytes32 hash, uint256 nNodes)`. This event contains the new accepted root hash of the reputation state, and the number of nodes in the tree. In order to sync, the miner requests the history of these events, and replays the logs that existed in the active reputation update log in the block prior to the event being emitted. Note that this log is 'frozen' at this block, and so there is no possibility of another reputation update sneaking in to the block the event was emitted at.
If the client has no state, all logs are replayed. If the client already has some state, the client skips …

Add ability to reputation miner to sync from scratch

---

contracts/ColonyFunding.sol
contracts/ColonyStorage.sol
contracts/ColonyTask.sol
contracts/IColony.sol
helpers/constants.js
helpers/test-data-generator.js
helpers/test-helper.js
test/colony-funding.js
test/colony-task-work-rating.js
test/colony.js
test/meta-colony.js
upgrade-test/colony-upgrade.js

Closes #316.
Instead of adding yet another `bool` to the task property, I have renamed `deliverableTimestamp` to `completionTimestamp`, and if the `completionTimestamp` is zero, then the task is not complete. This timestamp is set to `now` when the task deliverable is submitted or the task is explicitly marked as completed by the manager. The manager is only allowed to do this once the due date is passed. These are the only two ways this timestamp can be set.
A `TaskCompleted(uint256 taskId)` event is fired when a task is completed via either method. Note that when it is completed via the submission of the deliverable, the `TaskDeliverableSubmitted` event is fired also.
Repeating the issue here, but worth reiterating: if the due date is not set, the only way for a task to complete is for …

Add 'task completion' to task workflow; make due date optional

---

.circleci/config.yml
package.json
yarn.lock

Closes #326 
Closes #328 
Updates solidity coverage to 0.5.11 and continue fighting the good fight against `greenkeeper-lockfile-update` errors on uploading yarn lockfiles. Here the idea is to remove the `node_modules` cache for anything but a `package.json` that matches the checksum, meaning cache is not restored for GK PRs which I think is the right behaviour to expect. In addition although `husky` is definitely **not** installing the git pre-commit hooks those are attempted to be run when GK tries to commits the update `yarn.lockfile` so we explicitly remove the git hooks folder in case this is additionally been cached somewhere.

Update solidity coverage to 0.5.11 and changes for lockfile update issues

---

packages/colony-js-contract-loader-network/config.json
packages/colony-js-contract-loader-network/contracts/static/EtherRouter.json
packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/Authority.json
packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/IColony.json
packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/IColonyNetwork.json
packages/colony-js-contract-loader-network/package.json
packages/colony-js-contract-loader-network/src/NetworkLoader.js
packages/colony-js-contract-loader-network/src/__tests__/NetworkLoader.test.js

This PR updates the `@colony/colony-js-contract-loader-network` package in the following ways in order to support the latest deployment of contracts on Rinkeby:
* Update the EtherRouter address (for ColonyNetwork) to `0x6B110832B5673F62B841ee24E60e2b032090D0de`
* Add contract artefacts
* Add a test for loading the contract versions
* Set the latest version to 2
* Fix the logic to set different versions of contracts
* Update the package version to `1.6.0`, in line with the rest of colonyJS

Update contract loader for second Rinkeby contract deployment

---

packages/colony-js-contract-loader-network/contracts/static/EtherRouter.json
packages/colony-js-contract-loader-network/package.json

This is a small fix to use the correct deployed Rinkeby ColonyNetwork address for the network loader package.

Use correct Rinkeby colonyNetwork address

---

packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/Authority.json
packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/IColony.json
packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v2/IColonyNetwork.json
packages/colony-js-contract-loader-network/package.json

This PR updates the contract ABIs in the `@colony/colony-js-network-loader` package so that all of the changes in the contracts are reflected (and that the ABIs match the Rinkeby deployed versions).

Update Rinkeby ABIs

---

contracts/ColonyTask.sol
test/colony-task-work-rating.js
test/colony.js
upgrade-test/colony-upgrade.js

Closes #329 
I am not anticipating this to be a permanent solution; I feel like once disputes are fully fleshed out and begin to be implemented, we can apply them here as one of the first testbeds for them. This is why I have left the 'unset due date' test in, but `skip`ed it. I don't really have much to say here; I was pretty surprised at how straightforward this change ultimately turned out to be.

Make the due date default to 90 days in future

---

packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/bin/index.js
packages/reputation-miner/package.json
test/colony-network-mining.js
yarn.lock

Closes #302 
I have introduced an [SQLite](https://www.sqlite.org/) database to the miner for persisting state. This is an internal SQL instance (i.e. not a separate server) that persists to disk invisibly (i.e. no need to explicitly call a 'save' function on the database instance created. The schema of the database I have used is defined by
```
CREATE TABLE users ( address text NOT NULL UNIQUE );
CREATE TABLE reputation_states ( root_hash text NOT NULL UNIQUE, n_nodes INTEGER NOT NULL );
CREATE TABLE colonies ( address text NOT NULL UNIQUE );
CREATE TABLE skills ( skill_id INTEGER PRIMARY KEY );
CREATE TABLE reputations ( root_hash text NOT NULL, colony_address INTEGER NOT NULL, skill_id INTEGER NOT NULL, user_address INTEGER NOT NULL, value text NOT NULL);
```
Note that each table …

Give miner ability to persist reputation states

---

contracts/ColonyFunding.sol
contracts/ReputationMiningCycle.sol
contracts/ReputationMiningCycleRespond.sol
contracts/ReputationMiningCycleStorage.sol
gasCosts/gasCosts.js
packages/reputation-miner/ReputationMiner.js
test/meta-colony.js

Cleans up `todo`s in code and solves the _easy_ ones. Also adds a `(post CCv1)` note to ones that won't be done for the first version of Colony Contribute.
Closes #350 
Closes #343

Remove obsolete todos

---

.gitignore
packages/reputation-miner/ReputationMiner.js
test/colony-funding.js
test/colony-network-mining.js

Closes #318 
Everything returned by `breakKeyInToElements` is now prefixed by `0x` to make it clear that they are base16, and getKey can now deal with a base 16 string passed to it.

Deal with base issues in mining client cleanly

---

.circleci/config.yml
package.json
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
test/colony-network-mining.js
yarn.lock

Now that the history of all reputation states can be stored in the database, we needed to extend the reputation oracle to be able to return those historical states - showing a user their current reputation is great from a not-actually-doing-anything perspective, but if a reward payout is occurring (or, in the future, a dispute or a vote), the user needs to be able to prove their *historical* reputation to the contract.
This adds an extra parameter `rootHash` to the oracle route. If the root hash is the current root hash, then the reputation and proof is returned easily. If it is not the current root hash, the oracle attempts to  reconstruct that reputation state based on what it has in the database in a new (JS) patricia tree. Upon doing so, it calculates the proof for the requested …

Allow reputation oracle to return historical proofs

---

docs/_Docs_Tasks.md

As a result of answering a question on build.colony.io, I realized that the description in the docs leave it ambiguous whether a task's payout is determined by the ratings, or just the reputation gains/losses. This fixes the issue.

Amend 'ratings' description in docs

---

.circleci/config.yml

Here we remove greenkeeper configuration from Circle builds as the latest Greenkeeper 3 includes [native lockfile support](https://blog.greenkeeper.io/announcing-native-lockfile-support-85381a37a0d0)
This means that all public packages will be automatically updated in both `package.json` and the corresponding lockfile `yarn.lock`
@rdig has already successfully tested this in [`purser`](https://github.com/JoinColony/purser/pull/144/commits)

Remove GreenKeeper config from CI

---

package.json
yarn.lock

This updates us to the newly released v5.beta1. Main improvement here is that before, `truffle` only showed events fired from contracts only when a test failed. With this version you can force it to show them always with `truffle test --show-events` (tested ok for gasCost tests)

Upgrade to truffle5 beta.1

---

contracts/ColonyNetworkAuction.sol
test/colony-network-auction.js

Closes #368 
Pretty straightforward, I think. Only possible subtlety is that no explicit check required for the metacolony to exist, because CLNY address is looked up via the metacolony in `startTokenAuction`, so no auctions are able to be created if it doesn't exist.

CLNY goes to MetaColony, not ColonyNetwork

---

docs/_Docs_Pots.md

Currently colonyNetwork documentation has an invalid link to authority roles documentation due to missing slash in the url.

Fixed link to authority client documentation

---

contracts/ColonyFunding.sol
contracts/ColonyNetworkAuction.sol
test/colony-funding.js
test/colony-network-auction.js

Closes #353
* CLNY used in auctions is burned, not sent to MetaColony
* If an auction of CLNY is attempted to be started, all CLNY held by ColonyNetwork is burned
* Rewards have the network fee applied to them, same as task payouts
My notes are unclear as to whether 'fees being the same on all tokens, including native ones' applies to `claimColonyFunds`, so I have left that unchanged for now but should check with Jack.

Economic tweaks

---

contracts/IReputationMiningCycle.sol
contracts/ReputationMiningCycle.sol
contracts/ReputationMiningCycleRespond.sol
gasCosts/gasCosts.js
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/test/MaliciousReputationMinerClaimNew.js
packages/reputation-miner/test/MaliciousReputationMinerUnsure.js
test/colony-network-mining.js

Closes #348 and maybe some other issues I can't lay my hands on?
Until now, `respondToChallenge` was able to be called repeatedly; this would increase their `nChallengeStepsCompleted` to as high as necessary to 'win' the content.
Now, `nChallengeStepsCompleted` must be within a specific band for `respondToChallenge` to be called. The allowed value is based on jrhNnodes, which is the same for all submissions if they have managed to submit a JRH, which is a requirement for the binary search and all subsequent calls. Once respondToChallenge has been called once, `nChallengeStepsCompleted` moves out of this allowed band.
When the binary search completed, there was no guarantee that the saved `intermediateReputationHash` / `intermediateReputationNNodes` for the hash that responded to the last …

Further mining cycle edge cases and checks

---

helpers/test-helper.js
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/package.json
test/colony-network-mining.js
yarn.lock

Here we move back to the vanilla `ethers` release which [now provides support for making contract calls using the `blockTag` parameter](https://github.com/ethers-io/ethers.js/issues/226), https://github.com/ethers-io/ethers.js/issues/329
This is required functionality for the client syncing logic that was introduced in a custom version of ours of both `ethers` and `ganache-core` back in https://github.com/JoinColony/colonyNetwork/pull/311
Since the `ethers` release has jumped up a major version since then, we include a set of breaking fixes for v3 to v4.
Introducing `checkErrorRevertEthers` - an `ethers` specific helper function to check expected error message is present in the response. This is useful for the revert error checks coming back from the reputation mining client which …

Enable contract error messages on mining client

---

contracts/ColonyNetwork.sol
contracts/ColonyStorage.sol
contracts/ColonyTask.sol
test/colony-task.js
test/meta-colony.js

Closes #422 
Additionally updates the `skillExists` and `domainExists` modifiers similarly to `taskExists` to ensure those don't return `true` falsely as they are 1-based ids.

Fix bad task exists modifier

---

contracts/ColonyFunding.sol
contracts/ColonyNetworkMining.sol
contracts/IColonyNetwork.sol
contracts/IReputationMiningCycle.sol
contracts/ITokenLocking.sol
contracts/ReputationMiningCycle.sol
contracts/TokenLocking.sol
contracts/TokenLockingStorage.sol
test/colony-network-mining.js
test/token-locking.js

Partially addresses #164 
- Variable miner rewards as per WP sec 7.8 equations 3 & 4
- Token staking timestamp updates as average of existing and new stake.
- Currently total reward is **fixed** at 1200 CLNY.

Miner variable rewards I

---

contracts/Colony.sol
contracts/ColonyAuthority.sol
contracts/ColonyNetwork.sol
contracts/ColonyStorage.sol
contracts/ContractRecovery.sol
contracts/IColony.sol
contracts/IColonyNetwork.sol
contracts/IRecovery.sol
scripts/generate-test-contracts.sh
test/colony-network-recovery.js
test/colony-network.js
test/colony-recovery.js
test/colony.js
test/meta-colony.js
upgrade-test/colony-upgrade.js

Closes #369 
Unfortunately `ENS` and `MultiSigWallet` contracts also declare their separate `owner`s, however since those are built in their specifications and they are probably sufficiently detached from the Colony permissions model we've chosen not to refactor it.

Rename Colony owner role to founder

---

contracts/ReputationMiningCycle.sol
helpers/constants.js
helpers/test-data-generator.js
helpers/test-helper.js
test/colony-funding.js
test/colony-network-auction.js
test/colony-network-mining.js
test/colony-network-recovery.js
test/colony-task.js
test/colony.js
test/meta-colony.js
test/reputation-update.js
test/token-locking.js

Partial soln to #317 
- Remove circular dependency between `constants.js` and `test-helper.js`
- Utilize bulk assignment of task properties when generating tasks (10-15% speedup).
- Replace `assert` with `assert.isTrue`.
- Clarify a reputation mining error message re: timeouts.
- Introduce `setupFinalizedTask` to remove recurring boilerplate.
- Introduce `advanceMiningCycleNoContest` and `getActiveRepCycle` to remove recurring boilerplate.

Big Old Test Refactor 1

---

contracts/ColonyFunding.sol
test/colony-funding.js

This pull request adds a requirement to `moveFundsBetweenPots` to disallow funds being moved to/from the same pot. It also adds a corresponding test to ensure this action is not possible.
Resolves #448

Prevent moving tokens to/from the same pot

---

contracts/Colony.sol
contracts/IColony.sol
test/colony.js
upgrade-test/colony-upgrade.js

This PR exposes the `hasUserRole` function from the colony's authority contract on the colony. It also uses the colony to check `hasUserRole` in tests (rather than the authority directly) in tests.
The main motivation for doing this is that it will make interacting with the colony's user permissions via libraries like colonyJS easier.

Expose `ColonyAuthority.hasUserRole` on `Colony`

---

package.json
yarn.lock

We've been trying to keep pace with latest Truffle for a variety of reasons, but a pressing need for ABIv2 is the biggest one. Stock truffle fails intermittently for us since `v5.0.0-next.15`, we believe due to [this](https://github.com/ethereum/web3.js/commit/0c2f5cff795583f7ae824997835078291431bb92) commit at web3 that endeavours to reuse HTTP connections. This PR uses a custom release of truffle, identical to `truffle-next-18`, but with the call to `nodejsSet` removed - so HTTP connections are not reused every time. This appears to resolve the intermittent disconnects.
We will need custom releases with this patched out moving forward until the underlying issue (reported [here](https://github.com/trufflesuite/truffle/issues/1461)) is resolved.
Possibly related: …

Upgrade Truffle to (almost) truffle-next-18

---

.circleci/config.yml

Fixes the download path for `parity` as per https://releases.parity.io/

Fix parity download path

---

package.json
truffle.js
yarn.lock

Looks like the underlying issue that caused #454 to be necessary has been fixed up-up-stream, and we're good to return to the mainline cutting-edge truffle releases.

Move back to mainline Truffle 5.0.0-next releases

---

contracts/Colony.sol
helpers/constants.js
helpers/test-data-generator.js
helpers/test-helper.js
test/colony-funding.js
test/colony-network-auction.js
test/colony-network-mining.js
test/colony-network-recovery.js
test/colony-network.js
test/colony-recovery.js
test/colony-task.js
test/colony.js
test/meta-colony.js
test/reputation-update.js
test/token-locking.js

Partial soln to #317 
- Enable reputation-free CLNY distribution for miners.
- Set default rating for worker to a sensible `2`.
- Consolidate boilerplate in `colony-network-mining`.
- Create consistent usage for `advanceMiningCycleNoContest`.
- General cleaning, refactoring, and making-consistent.
- Introduce `setupRandomColony` and remove frequent setup boilerplate.

Big Old Test Refactor 2

---

docs/README.md

The install instructions doesn't work from scratch; fixed wrong order.

Fixed wrong install order in docs

---

helpers/test-helper.js
packages/reputation-miner/test/MaliciousReputationMinerWrongNNodes.js
test/colony-network-mining.js

This add another `errors` parameter to `accommodateChallengeAndInvalidateHash`, which contains two properties - `client1` and `client2`. Each of these, if it exists, is expected to contain an object that contains one of the properties:
* `confirmJustificationRootHash`
* `respondToBinarySearchForChallenge`
* `confirmBinarySearchResult`
* `respondToChallenge`
If defined, these properties should contain the string of the expected error to be returned. The exception is `respondToBinarySearchForChallenge`, which should contain an array, with each element containing the expected error (if any) for the `nth` call to `respondToBinarySearchForChallenge` for that client - for example, if `error-string` was expected on the third call to `respondToBinarySearchForChallenge` for client 2, a valid …

Add expected errors to accommodateChallengeAndInvalidateHash

---

contracts/ColonyNetworkMining.sol
contracts/ReputationMiningCycle.sol
migrations/8_setup_meta_colony.js
test-gas-costs/gasCosts.js
test/colony-funding.js
test/colony-network-mining.js
test/token-locking.js

Closes #47
Tests in `colony-network-mining.js` now *begin* with `MAIN_ACCOUNT` having `DEFAULT_STAKE` staked. This is to allows `MAIN_ACCOUNT` to mine new mining cycles. For newly-staked accounts to be able to mine, we must advance one mining cycle after staking.

Require that miners stake before the mining cycle begins

---

contracts/Colony.sol
contracts/ColonyDataTypes.sol
contracts/ColonyFunding.sol
contracts/IColony.sol
test/colony.js

Feature request from FE team.
I have taken the liberty of... anticipating another request from the FE team, which is being able to look up the domain a pot is associated with in the case of those pots, and adding a `domainid` property to pots.

Add getPot function

---

scripts/stop-blockchain-client.sh

Currently if metamask is connected to ganache on running tests it will be killed by stop blokchain script. Suggested solution kills only processes that are listening on port 8545 and not killing proccesses that established connection to ganache

Fix stop blockchain script killing browser

---

contracts/ColonyFunding.sol
contracts/TokenLocking.sol
test/colony-funding.js

Closes #437 
Currently, only nonzero deposits are subject to lock restrictions for deposits and withdrawals. As such, an additional restriction is needed to ensure that fresh deposits (in which the balance is increased from 0 after a payout process has begun) do not allow users to claim rewards.
We add a simple timestamp comparison when claiming payouts, to ensure that the deposit was made prior to the reward process being initiated:
```
require(userDepositTimestamp <= payout.blockTimestamp, "colony-reward-payout-deposit-too-recent");
```
Alternative implementations based on using lock restrictions for zero-valued deposits were not used here, on the grounds that such an implementation would require new depositors to "waive" all past payout cycles (to bring their deposit lock up to speed); …

Add better error when trying to claim a payout for a too-recent deposit

---

contracts/ColonyFunding.sol
test-gas-costs/gasCosts.js
test/colony-funding.js

Follow-on to #472. First time around I made the conditional `<=`, which could allow a malicious miner to pad a single block (same timestamp) with multiple withdrawals. A strict inequality will prevent this by requiring the deposit to be in a previous block.

Fix bug with deposit timestamp in claimRewardPayout

---

contracts/ColonyTask.sol
helpers/test-data-generator.js
test/colony-task.js
test/meta-colony.js

Closes #473 
Require `skillId > 0` before assigning worker.

Require task skill before assigning worker

---

helpers/test-helper.js
test/colony-network-mining.js

I was surprised when my changes in #464 to this test passed first time when I did them, and thought I was just having a good day down in the coding mines. It turns out, when CLNY funding of addresses was changed to not use tasks in #453, this test silently broke and was (mostly) passing without issue.
What was happening was all clients were submitting the same hash, because they were told to get updates 7-15 wrong, but there were now only four updates in the log. Then, what I *think* was happening was the `confirmNewHash` call was being called before all the transactions generated by `submitAndForwardTimeToDispute` were mined. This could happen because the promises generated there resolve once the transaction is submitted, not mined. If that happened, then the first `submitRootHash` call …

(Maybe) fix flickery test

---

contracts/ColonyNetwork.sol

Closes #341 
Using `finalizeTask` gas cost to measure gains (as that's where `appendReputationUpdateLog` is called most often with both positive and negative amounts).
Baseline: [637,698](https://circleci.com/gh/JoinColony/colonyNetwork/5737)
Without setting nChildren for positive updates: [636,926](https://circleci.com/gh/JoinColony/colonyNetwork/5749)

In reputation update log set nChildren to 0 for positive updates

---

contracts/Colony.sol
contracts/ColonyFunding.sol
contracts/ColonyStorage.sol
contracts/ColonyTask.sol

Following the discussion from #colony-network channel in Slack we decided to keep storage variables that hold contract addresses of type `address` rather than the type of the contract they store. This is for clarity and consistency.

Consistent contract references in storage

---

test/reputation-mining/happy-paths.js

Implements part of #317
As the ColonyNetwork is not re-deployed within reputation mining test files, all global skills created in these tests persist for the duration of the file. As such, global skill definitions really should occur in the first `before` block only to avoid creating hidden dependencies between test blocks. This was a bigger issue before @elenadimitrova's #501 , now it only crops up in one test so that's good :)
Specifically here, the calls to `addGlobalSkill` which we remove were actually doing nothing -- the skills we are testing are created in the first `before` block.

Remove redundant global skill creation

---

.circleci/config.yml
contracts/ColonyNetwork.sol
package.json
yarn.lock

Part of #319 
Here we run [mythril security analysis tool](https://github.com/ConsenSys/mythril-classic) against our codebase. We're using the dev version of it until the next release due to https://github.com/ConsenSys/mythril-classic/issues/873
The configuration in `docker` run in CI had to be a bit odd as it is not possible to mount the contracts' build folder to the `mythril` docker image as described in the [Circle documentation](https://circleci.com/docs/2.0/building-docker-images/#mounting-folders). The workaround there was applied and working in our solution. 
All contracts except interfaces (which contain no logic) are analysed. For reference, here are the registry of codes `mythril` reports https://smartcontractsecurity.github.io/SWC-registry/
One of the reported issues was …

Enable mythril nightly run

---

packages/reputation-miner/ReputationMiner.js
test/reputation-mining/root-hash-submissions.js

Implements part of #317 
Currently, an insufficient stake leads the miner to `return` an Error in `submitRootHash`, due to the loop not finding a valid index. This leads to an odd behavior where the actual error which appears to the developer is a `missing method for tx.wait()`; and further, the return value for `miner.submitRootHash` is ambiguous (an Error or a Tx). We should throw the error so that the miner knows what's gone wrong, and so the method always returns a Tx.

Throw error for insufficient miner stake

---

.circleci/config.yml

The nightly didn't run, and we think it's because we got the indentation wrong in the circle.yml, [judging from the docs](https://circleci.com/docs/2.0/workflows/#nightly-example). Let's take another crack at it!

Enable mythril nightlies

---

contracts/IReputationMiningCycle.sol
contracts/ReputationMiningCycleRespond.sol
helpers/test-helper.js
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/test/MaliciousReputationMinerAddNewReputation.js
packages/reputation-miner/test/MaliciousReputationMinerClaimNew.js
packages/reputation-miner/test/MaliciousReputationMinerClaimNoOriginReputation.js
packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
test/reputation-mining/dispute-resolution-misbehaviour.js
test/reputation-mining/disputes-over-child-reputation.js
test/reputation-mining/types-of-disagreement.js

Closes #420.
Consider a reputation tree that looks like the following as the `lastAgreeState` in a dispute
```
.
/ \
.   C
/ \
A   B
```
The two `firstDisagreeStates` could be
```
.                           .
/ \                         / \  
.    .                      .    .      
/ \  / \                    / \  / \                         
A  B  D  C                  A' B  D  C             
```
Let's assume the first one is correct. The client that submits the second one has inserted `D` correctly, but modified `A` to `A'` simultaneously. Without this PR, both miners can prove the same things about their new reputation state (i.e. nothing about D in `lastAgreeState` because it doesn't exist, that `D` is in their `firstDisagreeState`, as well as the ID assigned to `D` being correct …

Prevent reputation being changed during insertion of new one

---

contracts/IReputationMiningCycle.sol
contracts/ReputationMiningCycleRespond.sol
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/test/MaliciousReputationMinerClaimNoOriginReputation.js
packages/reputation-miner/test/MaliciousReputationMinerGlobalOriginNotChildOrigin.js
packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
test/reputation-mining/dispute-resolution-misbehaviour.js
test/reputation-mining/disputes-over-child-reputation.js

We had, at some point, implicitly assumed that `originReputationValue` could be either the colony-wide origin reputation, or the user-specific origin reputation, and tried to accommodate that in the `checkOriginReputation` function. However, we ultimately only use the origin reputation around [this line](https://github.com/JoinColony/colonyNetwork/blob/f8d7721a29bdd6519a3449be2fdd0efb9aab5f48/contracts/ReputationMiningCycleRespond.sol#L595), where it must be the user origin reputation.
The reputation miner correctly [only ever supplies the user's origin reputation](https://github.com/JoinColony/colonyNetwork/blob/f8d7721a29bdd6519a3449be2fdd0efb9aab5f48/packages/reputation-miner/ReputationMiner.js#L266). However, a malicious miner could instead use the colony-wide origin reputation in its …

Fix issue around origin reputation

---

contracts/ReputationMiningCycleRespond.sol
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
test/colony-reward-payouts.js
test/reputation-mining/client-calculations.js
test/reputation-mining/disputes-over-child-reputation.js
test/reputation-mining/happy-paths.js

Closes #519 
Includes tests to explicitly check the miner is getting the answers we expect (at last!), plus some refactoring of the `require`s in `ReputationMiningCycleRespond` to try and simplify that logic.

Correctly cap reputation changes when log value zeros user reputation

---

contracts/Colony.sol
test-gas-costs/gasCosts.js
test/colony-network-recovery.js
test/colony-reward-payouts.js
test/colony.js
test/token-locking.js

Closes #502 
Implemented the fix suggested, which was that tokens distributed during bootstrapping have to come from the claimed funds pot. Strictly, we don't need the `not-enough-tokens` require and could just let `sub` error with `ds-math-sub-underflow`, but I thought it better to have a more explicit error.

Take bootstrapped tokens from claimed funds only

---

contracts/Colony.sol
contracts/ColonyDataTypes.sol
contracts/ColonyFunding.sol
contracts/ColonyStorage.sol
contracts/ColonyTask.sol
contracts/IColony.sol
helpers/test-data-generator.js
test/colony-funding.js
test/colony-network.js
test/colony-task.js
test/colony.js
test/meta-colony.js

This terminology has been bothering me for a year and the time has come to make it better. `FundingPot` better demonstrates the concept intention behind the fund pools these manage and is additionally aligned with white-paper terminology.
I've tried to not be too invasive with the rename so there are still test variables called `pot` but these can be refactored along in time if we want to be perfectly aligned. For now the contracts and natspec comments suffices I think.

Rename Pot to FundingPot

---

contracts/ColonyFunding.sol
test/colony-funding.js
test/colony-reward-payouts.js
test/colony-task.js

Implements part of #527
- Remove `require` which allows anyone to call `claimPayout` on behalf of the user (funds go to the user still!).
- Update tests to de-specify the address when calling `claimPayout`. 
- Add guard against sending funds to the null address.

Allow anyone to claim payout on Task Role's behalf

---

.circleci/config.yml

Following the [latest `mythril` release 0.20.0](https://github.com/ConsenSys/mythril-classic/releases/tag/v0.20.0) we can now move away from the dev image we were using. This should also fix the nightly build.

Move to mythril release

---

contracts/Colony.sol
contracts/ColonyDataTypes.sol
contracts/ColonyFunding.sol
contracts/ColonyTask.sol
contracts/IColony.sol
migrations/2_deploy_contracts.js
test-gas-costs/gasCosts.js
test/colony-funding.js
test/colony-reward-payouts.js
test/colony-task.js
test/colony-token-integrations.js
test/colony.js
test/meta-colony.js

We improve the `FundingPot` model to allow for better extensibility and data consistency by introducing a `FundingPotAssociatedType` property and merging `domainId` and `taskId` pointers into a single `associatedTypeId` property which stores the foreign key reference of the respective type, i.e. if the `FundingPotAssociatedType` is `Task`, `associatedTypeId` will be a `taskId` reference, if the type is a `Domain` it will be a `domainId` reference and we are free to add another identifier type as needed.
Additionally we resolve an issue with the `moveFundsBetweenPots` function which executes on all types of funding pots yet some of the Task specific functionality is run on domain pots. 
We also fix a problem with missing check ensuring a task is funded before it can finalize.

Improvements of the FundingPot model

---

packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/bin/index.js
packages/reputation-miner/package.json

- Add babel polyfill to reputation client (It appears I broke that with the babel upgrade and reconfiguration work from #510 )
- Sets the local `minerAddress` property when private key is used (as well as when an actual minerAddress is used directly)
- Remove the obsoleted startup options `file` and `seed`
- Allows all Infura supported networks to be used not just `rinkeby`

Reputation mining client fixes and improvements

---

packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/bin/index.js

We removed that in #540 but it appears we need to be able to control where the db is stored. This is related to kubernetes and storing it on a drive that can persist between reboots.

Restore dbPath option in the client

---

helpers/test-helper.js
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/test/MaliciousReputationMinerWrongNNodes.js
test/colony-network-recovery.js
test/reputation-mining/dispute-resolution-misbehaviour.js
test/reputation-mining/disputes-over-child-reputation.js
test/reputation-mining/happy-paths.js
test/reputation-mining/root-hash-submissions.js
test/reputation-mining/types-of-disagreement.js

Following a call to `submitAndForwardTimeToDispute` for a set of clients, we'd normally perform a check that the submitted hashes are different as to establish valid dispute conditions. Here we consolidate these checks in the helper function itself to check consistently and eliminate repeating lines in tests.

Consolidate root hash submission checks

---

contracts/ReputationMiningCycleRespond.sol
packages/reputation-miner/test/MaliciousReputationMinerClaimNoOriginReputation.js
packages/reputation-miner/test/MaliciousReputationMinerClaimNoUserChildReputation.js
test/reputation-mining/disputes-over-child-reputation.js
test/reputation-mining/types-of-disagreement.js

Closes #410... but not in a very satisfying way?
Firstly, some background. The reason this issue existed was fundamentally because there were two states that could be submitted that had a plausible numerical calculation done - a bad actor could assume a reputation didn't exist, and use a value of zero when doing the calculation, adding a new node. If a good actor proved the reputation existed, and then did the calculation correctly, we would have two submissions that successfully passed, and so had to use a tiebreak to decide between them, which was done with the additional increment of `challengeStepsCompleted` in the case of the submission that proved the reputation already existed. By responding on behalf of the good actor and skipping this proof (and thus the additional increment), …

Prevent bad actors responding on behalf of good

---

package.json
packages/reputation-miner/package.json
yarn.lock

Closes #513 
Confirmed that [the fix](https://github.com/ethers-io/ethers.js/issues/411) that was blocking us to use stock `ethers` is now resolved. Although we experienced significant performance degradation after the upgrade which led to https://github.com/ethers-io/ethers.js/issues/424 and subsequently another minor version upgrade to include that fix.

Upgrade to vanilla ethers@4.0.26

---

.circleci/config.yml
package.json
test-system/end-to-end.js
test/reputation-mining/types-of-disagreement.js

Implements running an end-to-end network test as part of #319. The test sets up 100 funded colonies with 5 domains each. Also 9 tasks across 3 colonies and mines and checks the reputation earned is correct.
I wanted to add a larger set of global skills and tasks however the client had some performance issues processing an update of a node with ~500 child skill updates. For now there's a todo left in code for this to come back to.

Extends nightly build to run further system tests

---

contracts/IReputationMiningCycle.sol
contracts/ReputationMiningCycleRespond.sol
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/test/MaliciousReputationMinerClaimNoOriginReputation.js
packages/reputation-miner/test/MaliciousReputationMinerClaimNoUserChildReputation.js
packages/reputation-miner/test/MaliciousReputationMinerClaimWrongChildReputation.js
packages/reputation-miner/test/MaliciousReputationMinerClaimWrongOriginReputation.js
packages/reputation-miner/test/MaliciousReputationMinerWrongNewestReputation.js
packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
packages/reputation-miner/test/MaliciousReputationMinerWrongResponse.js
test/reputation-mining/dispute-resolution-misbehaviour.js
test/reputation-mining/disputes-over-child-reputation.js

This extends the logic used in #506 and the idea of an 'adjacent' reputation being used to prove that a reputation doesn't already exist in the tree. We incremented `challengeStepCompleted` if a response in `respondToChallenge` was able to prove a reputation existed in the `lastAgreeState`. The alternative was that if they were claiming a value of 0, then we allowed them to do this with an invalid proof (in case the reputation didn't exist in the tree).
In principle, this was okay but it did lead to issues that ended up being incrementally patched (e.g. #410). This PR removes all of these 'optional' skips; the intention is that only the submission that has done the calculation being disputed correctly is able to call `respondToChallenge` without it throwing.
Instead, with this PR, if a …

Remove extra increments of challengeStepCompleted in respondToChallenge

---

contracts/ColonyNetwork.sol
test/colony-recovery.js

Give `msg.sender` the recovery role when creating a new Colony.

Give Colony founder recovery role by default

---

.gitmodules
helpers/test-data-generator.js
migrations/8_setup_meta_colony.js

Aligns the network with the updated `TokenAuthority` implementation (which now uses 7 constructor parameters) and switches the `colonyToken` git submodule to use the `master` branch.

Fix token authority instantiation in migrations

---

contracts/ReputationMiningCycleStorage.sol

Follow-on from #553 , looking into whether the `DSAuth` in `ReputationMiningCycleStorage.sol` is redundant.
After doing some investigation, I have found that `DSAuth` is both redundant _and_ not redundant. `DSAuth` is **redundant** because no functions in `ReputationMiningCycle` use the `auth` modifier. However, it is **not redundant** because under-the-hood, we generate a new `EtherRouter` contract and _cast it to_ `ReputationMiningCycle` before use. In that sense, the actual contract has `owner` and `authority` variables from `EtherRouter`, and so we need to reserve the first two storage variables in `ReputationMiningCycle` so that the storage lines up.
My solution is to _remove_ the DSAuth dependency but to _keep_ the `owner` and `authority` storage variables (although to rename them …

Remove redundant auth from ReputationMiningCycleStorage

---

package.json
yarn.lock

I got a bit overzealous with `yarn upgrade --latest`. Sorry!
Double-check the gas reporter part of the build before merging.

Downgrade eth-gas-reporter

---

contracts/Colony.sol
contracts/ColonyAuthority.sol
contracts/ColonyDataTypes.sol
contracts/ColonyFunding.sol
contracts/ColonyNetwork.sol
contracts/ColonyPayment.sol
contracts/ColonyStorage.sol
contracts/ColonyTask.sol
contracts/IColony.sol
contracts/IColonyNetwork.sol
contracts/extensions/OneTxPayment.sol
helpers/test-data-generator.js
helpers/upgradable-contracts.js
migrations/4_setup_colony_version_resolver.js
scripts/check-recovery.js
test-gas-costs/gasCosts.js
test-upgrade/colony-upgrade.js
test/colony-funding.js
test/colony-payment.js
test/colony-reward-payouts.js
test/colony-task.js
test/colony.js
test/extensions/one-tx-payment.js
test/meta-colony.js
test/reputation-update.js

Closes #527 
The `Payment` flow (aka 4tx flow) is:
1. Create new payment: 
`addPayment(address recipient,  address token,  uint256 amount, uint256 domainId,  uint256 skillId)` 
2. Fund the payment (same as for Tasks using `moveFundsBetweenPots`).
3. Finalize the payment. When the payment becomes fully funded admins can call `finalizePayment` which marks it finalised and awards reputation.
3. Claim the payment via `claimPayment` (can be called by anyone on behalf of the recipient)
Amending the different elements of a payment can be done via: `setPaymentRecipient`, `setPaymentDomain`, `setPaymentSkill` or `setPayout`. These functions are restricted to the colony admins as is creating a payment. Note that once created any admin can manage any payment in the colony. Payments cannot be amended …

Payments implementation

---

helpers/test-helper.js
test/reputation-mining/client-calculations.js
test/reputation-mining/dispute-resolution-misbehaviour.js
test/reputation-mining/disputes-over-child-reputation.js
test/reputation-mining/happy-paths.js
test/reputation-mining/root-hash-submissions.js
test/reputation-mining/types-of-disagreement.js

Moved the logic of `before` block into a function `newNetworkInstance`, if we ever reached to a point from where we can't untangle the disputed states, we will call this function which will reset the network completely. 
Closes #524

Fixed Restore good state in reputation mining test.

---

contracts/IReputationMiningCycle.sol
contracts/ReputationMiningCycle.sol
contracts/ReputationMiningCycleRespond.sol
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
packages/reputation-miner/test/MaliciousReputationMinerWrongResponse.js
test/reputation-mining/dispute-resolution-misbehaviour.js
test/reputation-mining/disputes-over-child-reputation.js

Closes #393. Partly done with an eye on #569, but after further exploration (see that issue), we have iceboxed #569.
~~This also currently includes necessary upgrades to move to the `petersburg` hardfork, which means it is treading on the toes of #574. Happy for that to be merged first and then rebase this. I am therefore marking this as 'ready-to-review', but should also not be merged yet 😄~~

Refactor bytes[5] to bytes32[8] in respondToChallenge

---

.circleci/config.yml
package.json
truffle.js
yarn.lock

The `--truffle` option [was depreciated](https://github.com/ConsenSys/mythril-classic/releases/tag/v0.20.1) in `mythril-classicv0.20.1`. It in being replaced by [`truffle-security` package](https://github.com/ConsenSys/truffle-security) which uses the `truffle` plugin architecture to connect.
[This issue](https://github.com/ConsenSys/truffle-security/issues/145) stops us from being able to compile with `docker` so we have to switch that off when `truffle-security` runs.
Although this has possibly been fixed (as per @area 's comment below) in the next version `1.3.2` that upgrade introduced yet another problem reported [here](https://github.com/ConsenSys/truffle-security/issues/157). For now we are pinned to v1.3.1 until it is reliably resolved.
For the purposes of safely storing the keys …

Fix nightly security analysis job

---

contracts/IReputationMiningCycle.sol
contracts/ReputationMiningCycle.sol
contracts/ReputationMiningCycleDataTypes.sol
contracts/ReputationMiningCycleRespond.sol
contracts/ReputationMiningCycleStorage.sol
helpers/test-helper.js
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
packages/reputation-miner/test/MaliciousReputationMinerWrongResponse.js
test/reputation-mining/dispute-resolution-misbehaviour.js
test/reputation-mining/disputes-over-child-reputation.js
test/reputation-mining/happy-paths.js
test/reputation-mining/root-hash-submissions.js
test/reputation-mining/types-of-disagreement.js

Currently both `disputeRounds` and `reputationHashSubmissions` store the entire `Submission` struct. Where `reputationHashSubmissions` is only interested in the `proposedNewRootHash`, `nNodes`, `jrh`, `jrhNNodes` properties of that while `disputeRounds` manages the remainder of the properties through the dispute resolution process.
Here we introduce a `DisputedEntry` struct which is used only for dispute resolution properties while `Submission` is used for miner root hash submissions.

Split dispute resolution properties away from the Submission struct

---

contracts/Colony.sol
contracts/ColonyAuthority.sol
contracts/ColonyNetwork.sol
contracts/ColonyNetworkDataTypes.sol
contracts/ColonyPayment.sol
contracts/ColonyStorage.sol
contracts/ColonyTask.sol
contracts/IColonyNetwork.sol
contracts/IMetaColony.sol
contracts/ReputationMiningCycleRespond.sol
contracts/testHelpers/NoLimitSubdomains.sol
test/colony-network.js
test/colony-payment.js
test/extensions/one-tx-payment.js
test/meta-colony.js

Closes #573 
Adds a `deprecateGlobalSkill` function on the Meta colony available to Root permission users. This marks a global skill as deprecated which stops it from being added to new Payments and Tasks. Reputation earned in the skill decays away while we keep the skill itself for historical purposes.

Allow deprecation of global skills

---

.gitmodules
helpers/test-data-generator.js
helpers/test-helper.js
migrations/8_setup_meta_colony.js
test/colony-reward-payouts.js
test/token-locking.js

Integrate the refactored `TokenAuthority` from https://github.com/JoinColony/colonyToken/pull/16 which allows the colony `transfer` permissions on a locked Token.
Also update the `setupRandomColony` helper to generate a locked token instance. This works across our tests except for token locking and rewards functionality which is out of scope for the Colony Contribute dApp release. 
Merge order (as always with combined Token work) is to merge colonyToken#16 , change the `.gitsubmodules` branch back to `master` here and then merge this.

Provision default permissions for locked Token

---

contracts/extensions/ExtensionFactory.sol
contracts/extensions/OldRolesFactory.sol
contracts/extensions/OneTxPaymentFactory.sol
migrations/2_deploy_contracts.js
scripts/check-recovery.js
scripts/check-storage.js
test/extensions/old-roles.js
test/extensions/one-tx-payment.js

After talking to Chris about what would be useful to exist on-chain regarding extension contracts, we've arrived at this middle ground. In short, there needs to be a way for the dapp to work out if a supported extension is installed on a colony. We could have modified the extensions to be singletons on-chain that all colonies used, but establishing that precedent could prove dangerous if more complicated extensions were developed in the future, as the singleton would potentially have very many permissions across very many colonies, and so a bug in one could prove catastrophic.
The alternative we went for was to create a factory for each of the supported extensions. These provide a way to easily deploy an extension for a colony (just call the `deployExtension` function), as well as an easy …

Add factories for extension contracts

---

contracts/IReputationMiningCycle.sol
contracts/ReputationMiningCycle.sol
contracts/ReputationMiningCycleRespond.sol
contracts/ReputationMiningCycleStorage.sol
helpers/test-helper.js
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/test/MaliciousReputationMinerWrongProofLogEntry.js
packages/reputation-miner/test/MaliciousReputationMinerWrongResponse.js
test/reputation-mining/basic-functionality.js
test/reputation-mining/dispute-resolution-misbehaviour.js
test/reputation-mining/disputes-over-child-reputation.js
test/reputation-mining/happy-paths.js
test/reputation-mining/root-hash-submissions.js
test/reputation-mining/types-of-disagreement.js

Fixes two issues I've spotted in reputation mining:
1. People backing a submission after a dispute had started would prevent further defense of the submission
2. Incorrectly allowing a bye to be awarded in the first round to a submission that does not (yet) have an opponent.
Also adds additional read-only functions we've discovered we needed during #596, and adjusts the mining client to not have inelegant try-catches in two places (which also requires additional getters).

Fix reputation mining issues

---

packages/reputation-miner/bin/index.js

Adds `goerli` to the list of supported Infura networks in the mining client.

Add Goerli to supported Infura networks

---

contracts/Colony.sol
contracts/ColonyDataTypes.sol
contracts/ContractRecovery.sol

1. Adds `domainId` as argument to role-change events.
2. Make the role-change event generic and add the `uint8(ColonyRole)`.
3. Introduce `RecoveryRoleSet` event for recovery role changes.

Update role change events to include domainId

---

.circleci/config.yml
helpers/test-data-generator.js
package.json
test-gas-costs/gasCosts.js
test-upgrade/colony-network-upgrade.js
test-upgrade/colony-upgrade.js
test/colony-funding.js
test/colony-network-auction.js
test/colony-network.js
test/colony-payment.js
test/colony-reward-payouts.js
test/colony-task.js
test/colony.js
test/reputation-update.js
test/token-locking.js
truffle.js

Also due to https://github.com/dapphub/ds-note/issues/4 removed `DSToken` from tests and instead use instances of our own `Token`

Upgrade to latest solc 0.5.8

---

packages/reputation-miner/viz/repCycle.html

- This morning I realized that using the block timestamp to figure out the remaining time in the mining cycle is probably more relevant than the system timestamp. Not a big change but improves the semantics slightly.
- Changed the denomination of the reputation amount in the cycle visualizers from Ether to Wei, to match the tree visualizer.
- Realized I could drop the URI host/port and make requests locally by default (so requests are port-agnostic).
- Finally, I figured out how to cleanly bring up the active cycle on load. 💪

RepCycle Visualizer Improvements

---

contracts/IReputationMiningCycle.sol
contracts/ReputationMiningCycle.sol
contracts/ReputationMiningCycleDataTypes.sol
contracts/ReputationMiningCycleRespond.sol
helpers/test-helper.js
package.json
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/bin/index.js
packages/reputation-miner/test/ReputationMinerTestWrapper.js
test/reputation-mining-client/client-auto-functionality.js
test/reputation-system/reputation-mining-client/client-auto-functionality.js

Implements the following parts of #211 
- Submits a root hash as soon as it is able to, (rather than wait for the end of the submission period which isn't feasible when working with multiple submissions). It does so by checking at every block if there are less than 12 submissions of the current hash/nNodes/jrh and submits if there's still room
- Confirms the last hash after the mining window closes
- Implements a listener for `ReputationMiningCycleComplete` event for when a mining cycle completes so it processes the new update log

Real world mining client

---

contracts/Colony.sol
contracts/ColonyAuthority.sol
contracts/ColonyNetwork.sol
contracts/IColony.sol
docs/_Interface_IColony.md
test/contracts-network/colony-permissions.js

This PR would add a `setArbitrationRole` function to a colony, allowing users to assign the role even though there are no functions in the current glider release that make use of the ARBITRATION role. 
There are reasons. First, the arbitration role is described as a "placeholder" for dispute resolution. When voting or disputes are implemented, these changes will need to be put in anyways. Not exposing a flaccid function is an understandable design decision, but it leaves the arbitration role in a weird state of being in principle useful on lower levels, but inaccessible. 
More importantly (and more generally), developers working on extensions might want to utilize a colony's permissions system separately with other contracts that are related to the colony (read: as a module). Checking …

Arbitration Role in IColony

---

contracts/Colony.sol
contracts/ColonyNetwork.sol
contracts/IColonyNetwork.sol
docs/_Interface_IColonyNetwork.md
helpers/test-data-generator.js
migrations/4_setup_colony_version_resolver.js
test/contracts-network/colony-network.js

Bumps the `version()` a colony will report with the latest resolver to 2. This was already done on Goerli, just not included in the codebase. This PR also allows us to initialise ColonyNetwork with any version as the latest version. This is required because we wish to align versions between Goerli and Mainnet

Bump Colony version to 2

---

docs/_Docs_ReputationMining.md
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/bin/index.js

@gichiba recently drew my attention to the fact that the current [mining docs](https://docs.colony.io/colonynetwork/docs-reputation-mining-client) don't include instructions for Goerli. After the merge of #596 I figured I'd try and spin up the minimum viable mining client. After a few stumbles I figured it out and have updated the docs with new instructions, as well as added a bit more logging.
At first I thought it would be nice to have the miner sync from block 1 by default, but unfortunately a quirk with event logging means that the first `ReputationMiningCycleComplete` event is emitted before the first mining cycle is deployed, meaning that either an exception is raised for the missing mining cycle, or we ignore something that should really raise an exception, which would be asking …

Update mining docs for Goerli, better errors and logging for miner

---

package.json
truffle.js

For the purposes of easier working with the `truffle` console and `ganache-cli` forks here we add truffle network configurations for forks of `goerli` and `mainnet`. Additionally 2 commands for starting a respective fork 
`yarn run fork:goerli`
`yarn run fork:mainnet`
Network configuration for mainnet is also added to truffle.

Add network configurations and fork setup

---

docs/_Docs_ReputationMining.md

Update documentation with instance details of the production oracle serving reputation queries on `goerli` and `mainnet`. Also updated the example with an actual one people can try. Also add note on how to get colony-wide reputation instead of user-specific one.

Update reputation oracle documentation

---

contracts/extensions/OneTxPayment.sol
test/extensions/one-tx-payment.js

In an attempt to actually get the Dapp down to one tx everywhere, this PR makes a modification to the OneTransaction contract. In the Dapp, there is no way to move funds in to a subdomain yet, and so trying to do a single transaction payout from a subdomain would fail. One proposed solution is to have colonyJs handle the funding prior to calling the method, but that takes us up to two transactions - a lot more than one, and not much less than three (the number of transactions required if you're not using the extension at all). This takes an alternative approach i.e. to supply the functionality the dApp team thought they were getting.
Not deployed on mainnet yet, so no issues there, but it is deployed on Goerli and the old version is installed on some colonies. We don't have a method in …

Subdomain single tx payment funds can be from root

---

packages/reputation-miner/viz/repTree.html

Closes #652 
Updated the URI for requesting the reputation data from an absolute path (`localhost:3000/reputations`) to a relative path (`reputations`), which allows the visualizer to fetch data from miners running remotely.
Tested locally by checking that the relative URI fetched data from my local miner (i.e. that D3 supports relative URIs).

Fix URI for reputation tree visualizer data

---

contracts/Colony.sol
contracts/ColonyAuthority.sol
test-upgrade/2to3/2to3.js

Adds two missing steps in upgrading a colony from v2 to v3 for adding the newly introduced `Arbitration` role permissions to colonies that upgrade.

Add Arbitration role setup in colony upgrade

---

package.json
packages/reputation-miner/package.json
yarn.lock

Closes #675 
Build initially failed due to a timeout, but re-running the build passed. Figure why not upgrade out of the beta version while we're here.

Upgrade web3-utils to 1.0.0

---

.circleci/config.yml

Hilariously, the gas diff report is somehow [already broken](https://github.com/JoinColony/colonyNetwork/pull/673/checks?check_run_id=171769254). Will investigate, I suspect that [this commit](https://github.com/JoinColony/colonyNetwork/commit/1462e63fdcb44b85b266d6267a9f3866fbca4d5e) is the culprit, perhaps codechecks must be run immediately after the gas report is generated (rather than arbitrarily after).
Update: seems my guess was correct. I'm updating the invocation so that the gas tests and diff report are done in the same step.

Debug codechecks

---

contracts/testHelpers/TransferTest.sol
scripts/check-recovery.js
test/contracts-network/colony.js

There was some confusion over whether this was possible with the EtherRouter pattern, so added a test to demonstrate that it works and to check that we don't break it in the future.

Add test using `.transfer` from another contract

---

contracts/ColonyDataTypes.sol
helpers/constants.js

Following discussion [here](https://joincolony.slack.com/archives/C0YNG3M8B/p1567677619111500), we would like to reduce the maximum possible payout from the current `UINT254_MAX` to `UINT128_MAX`, or 340,282,366,920,938,463,463 WADs.
The rationale for the previous maximum was that we needed to reserve some range to account for the sign bit when emitting a reputation update (which accepts `int256`s), and some additional range to allow for the penalty/boost calculations when completing a task. After some analysis, I concluded that saving the two most significant bits would allow enough room for these operations.
Looking more, it seems like making payouts as big as they can possibly be given our _current_ constraints seems unnecessary, especially since `UINT254_MAX` is already such a …

Drop maximum payout to UINT128_MAX

---

contracts/Colony.sol
contracts/ColonyAuthority.sol
contracts/ColonyDataTypes.sol
contracts/ColonyPayment.sol
contracts/ColonyTask.sol
contracts/IColony.sol
docs/_Interface_IColony.md
test/contracts-network/colony-payment.js
test/contracts-network/colony-task.js
test/contracts-network/meta-colony.js

Closes #707 
Not much to say, this PR removes both `setTaskDomain` and `setPaymentDomain` functionality. As a best practice we also remove the `setPaymentDomain` function from our `authority`, freeing up some storage (and getting a sweet gas refund).

Immutable domains

---

contracts/PatriciaTree/Data.sol
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/package.json
packages/reputation-miner/test/MaliciousReputationMinerAddNewReputation.js
packages/reputation-miner/test/MaliciousReputationMinerWrongJRH.js
test/reputation-system/happy-paths.js
yarn.lock

Three tests failed to work with `useJsTree=false`. That raised red flags for me, because discrepancies between the solidity tree and the javascript tree is a pretty good way for reputation mining to break and good actors to lose their stakes. They now all work (though the test suite only now runs one test with the Solidity tree for coverage reasons).
This was broken under the solidity tree because of [this line](https://github.com/JoinColony/colonyNetwork/compare/maintenance/solidityPatriciaTree?expand=1#diff-13b43924d190294c4dbac0236f12b004L96). Because we are not hashing the keys, we see keys that are different in the very last bit, surfacing this bug (which I believe should allow a suffix length of 1). Frustratingly, when I realised this in the JS tree ten months ago and fixed it as …

Fix tests to work with Solidity Patricia Tree

---

package.json
yarn.lock

Latest truffle includes https://github.com/trufflesuite/truffle/pull/2433 , which was preventing us from upgrading.

Upgrade to latest truffle

---

.eslintrc
contracts/IReputationMiningCycle.sol
contracts/ReputationMiningCycle.sol
docs/_Interface_IReputationMiningCycle.md
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/test/MaliciousReputationMinerWrongJRH.js
packages/reputation-miner/test/MaliciousReputationMinerWrongJRHRightNNodes.js
test/reputation-system/dispute-resolution-misbehaviour.js
test/reputation-system/happy-paths.js
test/reputation-system/types-of-disagreement.js

While working through the whitepaper updates around dispute resolution, I realised it was possible to confirm a justification root hash where RH_N was not the last leaf in the tree, but the tree had N leaves still. The correct justification tree would look like:
```
/ \
/\ /\
A B C D
```
And an incorrect one could look like:
```
/ \
/\ /\
A B D E
```
The proofs for A and D would still have the same number of siblings, which was all we were checking during the confirmation. Such a submission would ultimately be found out, because the submitter would find themselves unable to respond during the search for the first key where there was a disagreement - either when the missing key was asked for as a `targetNode` during the search, or when a proof of the missing key was asked for during …

Do not use user-supplied branchmasks if possible

---

.eslintrc
helpers/test-helper.js
packages/reputation-miner/Dockerfile
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/adapters/console.js
packages/reputation-miner/adapters/slack.js
packages/reputation-miner/bin/index.js
packages/reputation-miner/package.json
packages/reputation-miner/test/MaliciousReputationMinerWrongJRHRightNNodes.js
test/reputation-system/reputation-mining-client/client-auto-functionality.js
yarn.lock

- Add try/catch-es in mining client
- On restart, recover any submissions made
- Add test resuming submissions after making some
- Save historical states after syncing the client

Polish off the mining client and make it more resillient

---

.eslintrc
package.json
scripts/check-auth.js
scripts/check-recovery.js
test/reputation-system/dispute-resolution-misbehaviour.js
yarn.lock

Closes #735 
The new version of prettier throws some new errors, which have been fixed. Most wide-reaching is disabling the `eslint-comments/no-unlimited-disable` rule. Other changes involved removing redundant parenthesis in two booleans statements in our build scripts and changing spacing and indentation in a reputation miner test. 
Also, it seems like the issue we were having where greenkeeper corrupted `yarn.lock` has gone away? This one looks fine.

Greenkeeper/prettier 1.19.1

---

package.json
yarn.lock

Closes #740, which appears to have just been a flickery test on build of the dependencies - can see the green rebuilds [here](https://circleci.com/gh/JoinColony/colonyNetwork/tree/greenkeeper%2Fhusky-3.1.0) from before the rebase.

Greenkeeper/husky 3.1.0

---

packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
test/reputation-system/client-core-functionality.js

Adds an API endpoint `/:rootHash/:colonyAddress/:skillId/` that returns 
```
{ addresses: [] }
```
Where the array contains a list of addresses that have the skill `skillId` in `colonyAddress` in the reputation state represented with the root `rootHash`.
As part of this, I've also sanitised user inputs for this and the proof endpoint, rather than just passing the user-supplied parameters in to the SQL query. Nothing ever went wrong doing that, right? 😓 
Marking this as draft for now so some discussion with the dapp team can occur as to what they might like changed.

Add endpoint to reputation oracle to list addresses with skill in a colony

---

contracts/ColonyFunding.sol
contracts/ColonyStorage.sol
test/contracts-network/colony-reward-payouts.js

Closes #763 
The fix here is arguably controversial, which hinges on changing
```  
mapping (address => bool) activeRewardPayouts;
```
to
```
mapping (address => uint256) activeRewardPayouts;
```
This is a cardinal sin of upgradable contracts, after all, so how is this justifiable? It's because no-one has started a reward payout yet, and the functionality is disabled on the deployed versions - so we know that this mapping will be empty for all colonies that have not upgraded to this version. Changing it from a `bool` to a `uint256` therefore is fine, as far as I am aware.
The token lock count is a network-wide lock count for the colony's token, which means payouts in `rewardPayoutCycles` will not necessarily share adjacent keys. That lock count is …

Prevent 'finalisation' of old reward payouts

---

helpers/test-helper.js
packages/reputation-miner/ReputationMinerClient.js
test/reputation-system/reputation-mining-client/client-auto-functionality.js

When I split up the oracle and the mining client, I failed to do it correctly. Even if we're not mining, we still need to follow updates as they happen and update our local state. So this rearranges a few things so that `--no-auto` just disables the mining, but still follows updates as they happen.
EDIT: Marking this as `in-progress` because I'm still testing with the goerli side, but I think the changes are done and would appreciate a review anyway to see if there's something obvious I've missed, just not a merge yet.

Make --no-auto function correctly

---

contracts/ColonyFunding.sol
contracts/IColony.sol
docs/_Interface_IColony.md

An early user was having difficulty claiming rewards payouts, and part of the reason is that he believed that the relevant user token balance is their _entire_ balance, rather than the amount deposited in `tokenLocking`. This PR clarifies which balance is relevant.

Update documentation for claimRewardPayout

---

contracts/ColonyNetwork.sol
contracts/IColonyNetwork.sol
docs/_Interface_IColonyNetwork.md
test/contracts-network/colony-network.js

Closes #783 
I've overloaded `createColony` rather than replacing it here (to aid our how-to-upgrade-everything process until we have it down pat), but otherwise, fairly straightforward. There are no limits here other than 'the version exists'; it's possible that in the future we'd have a minimum-supported version (especially as the app evolves) but for now this seems sufficient.

Allow creation of colonies with earlier version

---

packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
test/contracts-network/colony-task.js
test/reputation-system/dispute-resolution-misbehaviour.js
yarn.lock

Closes #798, closes #797, closes #795, closes #794, closes #793, closes #792, closes #789, closes #788, closes #787, closes #785, closes #777, closes #775 which I'm going to claim as some sort of record. No-one correct me.
The only one of these issues that was real was around the ganache upgrade, which required several changes. 
- The Istanbul hard fork (and the changed gas cost for certain opcodes therein) causes the maximum number of skills able to be on a task and still closed in the block limit to be reduced from 45 to 42.
- The new ganache seems to be slightly slower under coverage (or circle machines are slower now), so I had to add interstitial output to a particularly long-running test to get it to pass reliably.
- It would seem the new ganache is bad at gas estimation again, so …

Bring all dev dependencies up to date

---

contracts/ColonyNetwork.sol
contracts/IColonyNetwork.sol
docs/_Interface_IColonyNetwork.md
helpers/test-data-generator.js
scripts/docgen.js
test-gas-costs/gasCosts.js
test/contracts-network/colony-network.js
test/contracts-network/colony-reward-payouts.js
test/contracts-network/colony-token-integrations.js
test/contracts-network/router-resolver.js

Closes #607 
NOTE: this PR complements #714 and should be coordinated with that one, although it is not strictly a dependency.
This PR introduces the following overload function, allowing users to choose their version, set an ENS name, or configure the Extension Manager when creating their colonies:
```
function createColony(
address _tokenAddress,
uint256 _version,
string memory _colonyName,
string memory _orbitdb,
bool _useExtensionManager
) public stoppable returns (address)
```
When combined with the Extension Manager, the colony creation flow can be reduced to between 3-5 tx, [depending on when](https://joincolony.slack.com/archives/C0YNG3M8B/p1569268565092900) the Token Authority is deployed:
1. deploy Token
2. create Colony with ENS name and Extension Manager
3. install …

Colony setup bundle

---

contracts/ColonyNetwork.sol
contracts/IColonyNetwork.sol
docs/_Interface_IColonyNetwork.md
migrations/8_setup_meta_colony.js

Part of #811, pins the version used for new colonies to 3 when created using the now-deprecated `createColony`.
This makes it possible for ColonyJS + (d)app to work with the upgraded network without needing to be upgraded themselves.

Pin deprecated createColony version to 3

---

contracts/Colony.sol
contracts/ColonyAuthority.sol
contracts/ColonyExpenditure.sol
contracts/ColonyNetwork.sol
contracts/IColony.sol
docs/_Interface_IColony.md
docs/_Interface_IColonyNetwork.md
test/contracts-network/colony-expenditure.js

Remove the `transferExpenditure` overload and introduce `transferExpenditureViaArbitration`.
Also update the implementation of the deprecated `createColony` to explicitly call into the multi-argument overload.
Also that doc inversion thing happened again but I'm still not worried about it.

Remove transferExpenditure overload

---

contracts/ColonyDataTypes.sol

This isn't the clever solution, but it is the easiest one, I believe.
To be honest, I'm not 100% sure of the consequences of what's going on here, or what the clever solution would look like. Even though adding the index doesn't change the signature, it does change how the 'parsed' event looks to tools higher up the stack which is causing grief, because this event is fired by (and in the interface for) `OneTxPayment` which is not getting upgraded on chain. Events support overloads in general, but because this change doesn't change the signature, if we made _only_ this change, we couldn't put both in the interface to be parsed by tools. If we added the `recipient` field as we did originally, we could have both via an overload and everything would work on the contract level, but there'd …

Revert PayoutClaimed event totally

---

scripts/stop-blockchain-client.sh

I was always getting an error like this when running tests.
```
npm ERR! code ELIFECYCLE
npm ERR! errno 143
npm ERR! @colony.io/colony-network-contracts@1.0.0 start:blockchain:client: `bash ./scripts/start-blockchain-client.sh`
npm ERR! Exit status 143
```
These changes fixes it.

Fix blockchain start script error on process termination

---

contracts/colony/Colony.sol

Now that v4 (`burgundy-glider`) is released, we can clear out the `finishUpgrade` logic and give ourselves a clean workspace for any changes needed for upgrading from v4 to v5.

Reset finishUpgrade for v4

---

contracts/colony/ColonyFunding.sol
docs/_Interface_IColonyNetwork.md
test/contracts-network/colony-reward-payouts.js

We stupidly didn't account for this properly (i.e. at all) in the event that people are manually moving funds in to their reward pots. The only consequence is that it becomes difficult to `claim`, thankfully - this isn't accounting that would put funds at risk, as far as I can tell.

Fix accounting of nonRewardPotsTotal

---

contracts/extensions/OneTxPayment.sol
test-gas-costs/gasCosts.js
test/extensions/one-tx-payment.js

Closes #[806]
Implements expenditure for multiple token payments in one-tx-payment extension for #806
See https://github.com/JoinColony/colonyNetwork/pull/817

Use expenditure to handle multiple token payments

---

contracts/colony/ColonyFunding.sol
contracts/colonyNetwork/ColonyNetworkDataTypes.sol
contracts/colonyNetwork/ColonyNetworkMining.sol
contracts/colonyNetwork/ColonyNetworkStorage.sol
contracts/colonyNetwork/IColonyNetwork.sol
contracts/reputationMiningCycle/ReputationMiningCycle.sol
contracts/tokenLocking/ITokenLocking.sol
contracts/tokenLocking/TokenLocking.sol
contracts/tokenLocking/TokenLockingDataTypes.sol
helpers/test-data-generator.js
migrations/8_setup_meta_colony.js
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
test-gas-costs/gasCosts.js
test/contracts-network/colony-network.js
test/contracts-network/colony-reward-payouts.js
test/contracts-network/reputation-basic-functionality.js
test/contracts-network/token-locking.js
test/reputation-system/root-hash-submissions.js

With staking merged, it makes sense to use it wherever it's appropriate - and a big place where it would be appropriate and is not currently used is reputation mining. 
This PR moves all 'knowledge' of mining up to the `ColonyNetwork` contract which is much better than having that on `TokenLocking`. So to mine, you obligate CLNY through `ColonyNetwork`, and otherwise everything is the same as before. Instead of not being allowed to withdraw during mining if you've submitted, you're not allowed to unstake if you've submitted. 
The only thing I'm not happy with here is the timestamp stuff; are we planning on using that anywhere other than with mining? If not, it should just be elevated to `ColonyNetwork` as well, specific to staking for mining.
I've taken the liberty of adding `getApproval` …

Use staking functionality for mining

---

contracts/ReputationMiningCycleCommon.sol
contracts/colonyNetwork/ColonyNetworkDataTypes.sol
contracts/colonyNetwork/ColonyNetworkMining.sol
contracts/colonyNetwork/ColonyNetworkStorage.sol
contracts/colonyNetwork/IColonyNetwork.sol
contracts/reputationMiningCycle/IReputationMiningCycle.sol
contracts/reputationMiningCycle/ReputationMiningCycle.sol
contracts/reputationMiningCycle/ReputationMiningCycleCommon.sol
contracts/reputationMiningCycle/ReputationMiningCycleRespond.sol
contracts/reputationMiningCycle/ReputationMiningCycleStorage.sol
contracts/tokenLocking/ITokenLocking.sol
contracts/tokenLocking/TokenLocking.sol
docs/_Interface_IColonyNetwork.md
docs/_Interface_IReputationMiningCycle.md
docs/_Interface_ITokenLocking.md
helpers/constants.js
scripts/generate-test-contracts.sh
test/contracts-network/colony-network.js
test/contracts-network/colony-staking.js
test/contracts-network/reputation-basic-functionality.js
test/contracts-network/token-locking.js
test/reputation-system/dispute-resolution-misbehaviour.js
test/reputation-system/happy-paths.js
test/reputation-system/reputation-mining-client/client-auto-functionality.js
test/reputation-system/root-hash-submissions.js

Okay, this has been long enough coming! First off, this is based on #810, so marking as draft until then is merged - it is probably otherwise ready for review.
Before this PR, none of the calls during dispute resolution provided rewards, so there was going to be little incentive for responses to occur; while those that made the good submission are incentivised to defend their submission (because they don't want to lose their stake), if more than one person has made the submission then there is incentive to just wait for other people to defend the submission (and not pay gas) and still claim the rewards at the end. 
So, the fundamental question is how large the reward is. The reward is being paid for by slashed stakes (if a submission you made is found invalid, you lose `MIN_STAKE`), so …

Reward users for responding during dispute

---

contracts/colony/Colony.sol
contracts/colony/ColonyStorage.sol
contracts/colonyNetwork/ColonyNetwork.sol
contracts/extensions/FundingQueue.sol
contracts/extensions/OneTxPayment.sol
helpers/constants.js
helpers/test-data-generator.js
helpers/test-helper.js
test-gas-costs/gasCosts.js
test/contracts-network/colony-expenditure.js
test/contracts-network/colony-funding.js
test/contracts-network/colony-payment.js
test/contracts-network/colony-permissions.js
test/contracts-network/colony-recovery.js
test/contracts-network/colony-reward-payouts.js
test/contracts-network/colony-staking.js
test/contracts-network/colony-task.js
test/contracts-network/colony.js
test/contracts-network/meta-colony.js
test/contracts-network/reputation-update.js
test/contracts-network/token-locking.js
test/extensions/funding-queue.js
test/extensions/one-tx-payment.js
test/reputation-system/client-calculations.js
test/reputation-system/dispute-resolution-misbehaviour.js
test/reputation-system/disputes-over-child-reputation.js
test/reputation-system/happy-paths.js
test/reputation-system/root-hash-submissions.js

Taking DLP actions (see #553) requires submitting a "domain proof" of the form (`permissionDomainId, childSkillIndex, domainId`). These three inputs allow us to verify, in constant time, that both a) the user has the permission needed to take the action, and b) the domain of action is in the inheritance path of the domain of permission. There was one hiccup -- if `permissionDomainId` and `domainId` were the same (i.e. a user was taking an action in the same domain where they had the permission, a common occurrence), then the semantics of `childSkillIndex` became murky -- since children are 0-indexed, `childSkillIndex = 0` meant the "first child" -- there was no value which represented "the domain itself".
Our initial solution was to say, "alright, when `permissionDomainId == domainId`, we …

UINT256_MAX in Domain Proofs

---

.circleci/config.yml
test/reputation-system/dispute-resolution-misbehaviour.js
test/reputation-system/happy-paths.js

As part of trying to make our tests better (because they have started randomly failing on Circle right now which is really cramping our style), I decided to take a look at some of the heavier tests in the hope that by making some tests lighter, Circle would be happier.
Far and away the biggest / most intensive tests are some of the reputation ones with many clients, with single tests taking nearly 30 minutes on Circle - clearly dominating the reputation coverage test runs. In these tests, many (up to fourteen) reputation miners are created, and they all process the reputation log generated for that test. While for some of these tests, we do need this many miners, this log was four times longer than it needed to be for the tests to work, as we created a task (and four reputation log …

Use payments rather than tasks in reputation tests where appropriate

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/IColony.sol
docs/_Interface_IColony.md
test/contracts-network/colony-permissions.js

Prerequisite for #644, #717
Introduce functionality allowing Arbitrators to emit reputation penalties:
- `emitDomainReputationPenalty`, which requires a domain proof, and
- `emitSkillReputationPenalty `, which does not, but is restricted to root arbitrators.
In both cases the given `int256` value must be less than or equal to 0.

Arbitration Reputation Penalties

---

helpers/test-data-generator.js
helpers/test-helper.js
test/contracts-network/colony-recovery.js
test/contracts-network/colony.js
test/contracts-network/meta-colony.js

Been seeing the `before(Each)` for some tests failing repeatedly on Circle for taking too long, so decided to take a crack at improving them.
The tests in question often set up a whole new set of resolvers, which were taking more time than necessary when most tests use the same shortcut of using the `colonyNetwork` deployed during migrations, so where possible I did the same.
The one case where the same couldn't be done was the metaColony specific tests, because the metacolony attached to that `colonyNetwork` might have detritus from previous tests. So I have reworked the `setupColonyNetwork` so that it reuses the resolvers, at least, to speed that up. Given that the resolvers are now reused between all tests, I've also added the `restoreSubdomainLimit` function which is called in the …

Improve before(each) speed for some tests

---

truffle.js

If we're just working on the dapp, we don't really care about docker compilation as it seems to work quite fine without it. This is in lieu of making it easier for people to run a version of the dapp stack for development.
Could there be any problems related to this? Which `solc` version is used when docker is disabled? Does the user have to install that manually?

Add option to disable docker if desired

---

packages/reputation-miner/ReputationMinerClient.js

If we restart when the miner is out of gas, we end up in a restart loop, because it's almost certainly still out of gas a few seconds later. This PR means that it just sits patiently until it is manually restarted (presumably, after it has been sent some ether).

Never restart if miner out of gas

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/IMetaColony.sol
contracts/colonyNetwork/ColonyNetwork.sol
contracts/colonyNetwork/ColonyNetworkMining.sol
contracts/colonyNetwork/ColonyNetworkStorage.sol
contracts/colonyNetwork/IColonyNetwork.sol
contracts/reputationMiningCycle/ReputationMiningCycle.sol
contracts/tokenLocking/ITokenLocking.sol
helpers/test-helper.js
test/contracts-network/meta-colony.js
test/reputation-system/root-hash-submissions.js

CLNY will be issued via three mechanisms:
* CoinMachine
* A stipend for the metacolony to pay for tasks
* Rewards for reputation miners.
Coinmachine is being dealt with in #835; this PR deals with the other two mechanisms.
Set via `setAnnualMetaColonyStipend`. An absolute value, given that none of these mechanisms react to each other - we trust the metacolony to set the values appropriately. This function is permissioned, but the `issueMetaColonyStipend` that awards the stipend can be called by anyone, as often as is desired, which will result in the appropriate pro-rata'd amount being awarded.
Set via `setReputationMiningCycleReward` on the metacolony. This reward will be split between all entries that were submitted for the reputation hash that was ultimately accepted. The natural place …

Add CLNY issuance control / automation mechanisms

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/ColonyExpenditure.sol
contracts/colony/IColony.sol
docs/_Interface_IColony.md
docs/_Interface_IColonyNetwork.md
docs/_Interface_IMetaColony.md
docs/_Interface_ITokenLocking.md
test/contracts-network/colony-expenditure.js

Part of #80 and related issues
Depends on #771
Add support for Arbitration state changes!
Specifically, this introduces an `internal` function `executeStateChange` which takes a base storage slot and applies a series of operations (concatenating mapping keys, adding struct offsets, and performing hashes) to generate the storage slot of a variable to be modified, and then updates the value of that variable. This internal function is called by the public `setExpenditureState`, which authenticates the user and uses an `expenditureId` to determine the base storage slot. This approach necessary to ensure that users cannot make unauthorized changes (which we could not do if, for example, users could pass storage slots directly).

Arbitration State Changes

---

migrations/2_deploy_contracts.js

For local development the dapp people would like to have the `CoinMachineFactory` contract deployed when running the migration locally.

Deploy CoinMachineFactory on local migration

---

docs/_Interface_IColonyNetwork.md
docs/_Interface_IReputationMiningCycle.md
package.json

Not sure why, but this stopped working, even handing it directly to `globby`, the underlying package used by `solidity-coverage`. The 'positive' glob seems to still work but will need extra upkeep if we add more folders.

Change glob choosing tests to run under coverage

---

contracts/colony/ColonyStorage.sol

This PR fixes `validGlobalSkill()` modifier which is defined in a file that does not use the `ABIEncoderV2` pragma but calls a function that returns a struct, which is a V2 feature. This should not even compile.
It happens to work only by accident - the compiler is missing a check against it and it happens to be a special case that hits the path in the code where nothing explicitly fails. Specifically, all the files where the modifier is used do use `ABIEncoderV2` and the compiler (erroneously) assumes that the user wanted it enabled for the modifier definition too. In many other cases this just causes Internal Compiler Error instead. See https://github.com/ethereum/solidity/issues/8379 for details.
I'm currently working on adding the missing check …

Missing ABIEncoderV2 pragma in ColonyStorage

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/ColonyRoles.sol
contracts/colony/IColony.sol
docs/_Interface_IColony.md
test/contracts-network/colony-permissions.js
test/extensions/one-tx-payment.js

Closes #878
Removes the `_setTo` argument and updates the user's permissions to match the given `bytes32`.

Update setUserRoles to add and remove roles simultaneously

---

contracts/extensions/ColonyExtension.sol
migrations/9_setup_extensions.js
test-smoke/colony-storage-consistent.js

After a call with Chris about developing the extension manager, a couple of minor things came up that will help him. One is to install the extensions when the migrations are run, and the other is a minor functional change, making the `deprecated` boolean available via `getDeprecated`.

Make extension manager development easier for app

---

.circleci/config.yml

[See the discussion here](https://discuss.circleci.com/t/updated-authenticate-with-docker-to-avoid-impact-of-nov-1st-rate-limits/37567/46).
I *think* this works (we no longer get the 'not authenticated' message on Circle), but it's one of those things we won't know for sure until Docker flips the switch at the start of the month...

Authenticate with Docker Hub when building

---

.circleci/config.yml

[More CircleCI updates required](https://discuss.circleci.com/t/old-linux-machine-image-remote-docker-deprecation/37572?mkt_tok=eyJpIjoiTkRsaU1URXhZMlkyTURVNSIsInQiOiJlQ3NFTk9wZnhFWUdFZ1VKMlcrNnZENzlRMFRvS0J3OXBwemkwVmNaa0ZQR0xnbXloQTFhb2JVRTd1Q0FJZkt1RUFVTUMzMVZrbjBGNGJ6U0R5MVNRNFhJOWdvRXpJQlwvMDVRZ2toSXBnUThyWk10eUZQamtxZzB2dmxURktqR0wifQ%3D%3D)

Specify docker image for CircleCI

---

docs/_Interface_IColonyNetwork.md
docs/_Interface_IReputationMiningCycle.md
scripts/docgen.js

This has annoyed me enough again for me to take another crack at it. The script now sorts functions by the whole signature, which should have a unique ordering.
Stretch goal in the future: come up with a way to mark deprecated functions and always have them after the 'real' one, regardless of the signature, but for now this'll do unless someone else feels strongly about it :stuck_out_tongue:

Try and stop our docs flitting around

---

contracts/extensions/OneTxPayment.sol
docs/_Interface_IColonyNetwork.md
test/extensions/coin-machine.js
test/extensions/one-tx-payment.js

An exploratory PR for reducing the gas costs associated with making one-transaction payments.
| Iteration | Gas Cost | % Change |
|---------|----------|------------|
| Baseline | 728475 | --- |
| Baseline w/o Skill | 534130 | -27% |
| Baseline w/ Payment delete | 642582 | -12% |
| Refactor | 726804 | -0% |
| Refactor w/o Skill | 532459 | -27% |
| Refactor w/o Payments | 817814 | +12% |
| Refactor w/o Payments & Skill | 598809 | -18% |
| Refactor w/ new FundingPot | 715110 | -2% |
| Refactor w/ Payment delete | 640911 | -12% |
| Refactor w/ new FundingPot & Payment delete | 651677 | -11% (?) |
Ultimately, we are going to leave this functionality mostly alone for now, and only merge the refactor without any other gas optimizations.

OneTxPayment Refactor

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/ColonyStorage.sol
contracts/colony/ColonyTask.sol
contracts/colony/IColony.sol
contracts/colonyNetwork/ColonyNetworkExtensions.sol
contracts/extensions/CoinMachine.sol
contracts/extensions/ColonyExtension.sol
contracts/extensions/FundingQueue.sol
contracts/extensions/OneTxPayment.sol
contracts/extensions/VotingReputation.sol
contracts/testHelpers/TestExtensions.sol
docs/_Interface_IColony.md
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-network-extensions.js
test/contracts-network/colony.js
test/extensions/coin-machine.js
test/extensions/funding-queue.js
test/extensions/one-tx-payment.js
test/extensions/voting-rep.js

Closes #808
~Depends on #881~
~Depends on #870~
Following the discussion in #881 , we will add an `identifier()` function to every extension, which returns its `bytes32` identifier. This can be used to verify that an address is a network-managed extension, allowing us to prevent colonies making arbitrary transactions to these extensions.

Add support for arbitrary transactions

---

test/extensions/one-tx-payment.js

Explanation:
```
"0xa1">"0xb1"
false
"0xa1">"0xB1"
true
```

Correctly order addresses in OneTxPayment tests

---

packages/reputation-miner/ReputationMiner.js
test/reputation-system/client-core-functionality.js

Previously, the addresses were in... some unknown order. The UI would like to be able to display addresses in order of reputation, so let's sort them here rather than having the app request each reputation in turn.

Order addresses by total reputation in oracle endpoint

---

test/reputation-system/client-core-functionality.js

Currently, both of these URLs work. ColonyJS is switching from using one to the other, so let's make sure we don't break either anytime soon.

Test with/without trailing slash for reputation oracle endpoint

---

contracts/colony/ColonyRoles.sol
test/contracts-network/colony-permissions.js

`setUserRoles` emitted an event for every role, even if it didn't change. This change only emits the events necessary and as a bonus, saves us gas (as `setRole` is also only called when necessary) if fewer than all-but-one roles are being set.

Only emit necessary events from setUserRoles

---

.eslintrc
contracts/common/ContractRecovery.sol
contracts/common/ContractRecoveryDataTypes.sol
helpers/test-helper.js
package.json
test/contracts-network/colony-network.js
test/contracts-network/colony-recovery.js
test/contracts-network/colony-task-work-rating.js
test/contracts-network/colony-task.js
test/extensions/coin-machine.js
test/extensions/voting-rep.js

Based on the designs for the recovery mode screens, we need these events, so I've added them.
While writing the tests it also became apparent that we were not rigorously testing our events. So I've improved `expectEvent` to check the parameters passed by the event as well, and updated all relevant tests (we probably need more, but not in this PR).

Add needed events to recovery mode; Improve event tests

---

contracts/colony/Colony.sol
helpers/constants.js
test-gas-costs/gasCosts.js
test-smoke/colony-storage-consistent.js
yarn.lock

With more integration with the app team happening, this has now caught out multiple people, so I'm proposing we move to incrementing the version number immediately after a release. This should mean app people are more easily to just pull from our `develop` to see how things are going.
I recall a conversation I had with Chris a long time ago about this, and was on the side of 'only update immediately before a release', which was where we settled. Perhaps it's time for a change though. Thoughts?

Bump colony contract version number

---

contracts/extensions/CoinMachine.sol
contracts/extensions/ColonyExtension.sol
contracts/extensions/FundingQueue.sol
contracts/extensions/OneTxPayment.sol
contracts/extensions/TokenSupplier.sol
contracts/extensions/VotingReputation.sol
contracts/testHelpers/RequireExecuteCall.sol
contracts/testHelpers/TestExtensions.sol
scripts/check-recovery.js
scripts/check-storage.js
test/extensions/coin-machine.js
test/extensions/token-supplier.js
test/extensions/voting-rep.js

Closes #25 
Depends on #876 for the extension identifier lookup.
Simple extension to manage a colony's token supply. Allows root users to call `setTokenSupplyCeiling` and `setTokenIssuanceRate`, most likely via a Voting extension.
This PR also includes a mild refactor of the `ColonyExtension` to include more shared functionality.
```
3.5.1 Token management
While root users can mint tokens at-will, in many cases it will be desirable to mediate this ability
via an extension contract. Here we describe such an extension.
Token generation and initial supply
When the extension is deployed, the TokenSupplyCeiling and the TokenIssuanceRate are set.
The former is the total number of colony tokens that will be created and the latter is the rate at
which they become available to the root domain to …
```

Add TokenSupplier

---

contracts/extensions/CoinMachine.sol
test-smoke/colony-storage-consistent.js
test/contracts-network/colony.js
test/extensions/coin-machine.js

Includes the ability to cap the total number of tokens sold by a CoinMachine instance, as an initialisation argument.

Add maxTotal to cap total tokens available

---

helpers/constants.js
test/extensions/voting-rep.js

Occasionally, [such as in the last merge](https://app.circleci.com/pipelines/github/JoinColony/colonyNetwork/2894/workflows/c99d5d45-b49a-4b33-bf9a-04eb512d4a5b/jobs/14718), `web3.utils.soliditySha3` throws a bit of a wobbly. What happens is that `shortId.generate()` generates a string that starts `0x` and `web3.utils.soliditySha3` tries to interpret this as a `bytes`, but the subsequent characters are taken from the whole alphabet, and at least one is therefore almost certainly invalid, causing a test failure.
By using the optional, explicit, syntax for `soliditySha3`, in this scenario, even when the string starts `0x`, it is interpreted as a string.

Make sure SoliditySHA3 knows shortIDs are strings

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/ColonyFunding.sol
contracts/colony/IMetaColony.sol
contracts/colonyNetwork/ColonyNetwork.sol
contracts/colonyNetwork/ColonyNetworkDataTypes.sol
contracts/colonyNetwork/ColonyNetworkStorage.sol
contracts/colonyNetwork/IColonyNetwork.sol
docs/_Interface_IColonyNetwork.md
docs/_Interface_IMetaColony.md
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-funding.js
test/contracts-network/meta-colony.js

Closes #903
Adds a `payoutWhitelist` mapping to the Colony Network, configurable from the Metacolony. Used to determine if a token fee should be sent to auction or directly to the Metacolony.
The intention is to whitelist stablecoins, but who knows!

Add payoutWhitelist to ColonyNetwork

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/ColonyDataTypes.sol
contracts/colony/IColony.sol
contracts/colonyNetwork/ColonyNetwork.sol
contracts/colonyNetwork/ColonyNetworkDataTypes.sol
contracts/colonyNetwork/IColonyNetwork.sol
contracts/extensions/OneTxPayment.sol
contracts/extensions/TokenSupplier.sol
docs/_Interface_IColony.md
docs/_Interface_IColonyNetwork.md
helpers/constants.js
helpers/test-data-generator.js
helpers/test-helper.js
test-gas-costs/gasCosts.js
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-network.js
test/contracts-network/colony-reward-payouts.js
test/contracts-network/colony-token-integrations.js
test/contracts-network/colony.js
test/contracts-network/router-resolver.js
test/extensions/one-tx-payment.js

Work on the Universal Action Creator is to begin soon, so Raul and I had a call to figure out what the contracts have to change or add in order for that to work. Some of that work is taking place in #882, and this PR is intended to contain the remainder. The resulting additional work can broadly be split in to two categories.
The type of screens we're thinking of look like this (once an action has been created):
The example here is moving funds, but in principle this applies to all actions in the UAC. This type of screen will be navigated to via a path that involves the transaction id. The app will get the transaction in question, and attempt to work out what is going on in it. There are four possibilities 
1. The transaction doesn't exist
2. The transaction exists, but isn't mined yet
3. …

Add further events and functions required by app

---

contracts/colony/Colony.sol
contracts/colony/ColonyDataTypes.sol
contracts/colony/IColony.sol
contracts/extensions/VotingReputation.sol
docs/_Interface_IColony.md
test-smoke/colony-storage-consistent.js
test/contracts-network/colony.js

Closes #877
This PR adds support for transaction annotations -- arbitrary strings which provide additional metadata about a transaction. These annotations can be plaintext, or some other structure (such as JSON).
Annotations are emitted via the `annotateTransaction` function, which is public:
```
function annotateTransaction(bytes32 _txHash, string memory _metadata) public stoppable {
emit Annotation(_txHash, msg.sender, _metadata);
}
```
In principle, anyone can add an annotation to any transaction, via an additional transaction.
Currently, the ability to emit annotations doesn't distinguish between any sort of type. Specifically, if annotations can be used to emit descriptions of transactions, as well as _comments_ on transactions, how can we distinguish a comment from the initial …

Add support for Annotations

---

.gitignore
contracts/colony/ColonyDataTypes.sol
contracts/colony/ColonyFunding.sol
contracts/colony/ColonyPayment.sol
contracts/extensions/ColonyExtension.sol
contracts/extensions/OneTxPayment.sol
migrations/3_setup_colony_network.js
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-payment.js
test/extensions/one-tx-payment.js

This branch is the one Raul and I were using to get The Graph working with the contracts / the dev environment, so merging this is sort of obligatory. There's a cherry-picked commit from #911 and some other changes.
`OneTxPaymentMade` event gets `agent` (like many things are going to), I add some events to the payment lifecycle. I added a getter to extensions so that we can work out what colony they're from. Raul added functionality to a migration that writes out the colonynetwork address to a file, which gets used by the graph dev environment to set itself up programmatically.

OneTxPayment event changes

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/ColonyDataTypes.sol
contracts/colony/IColony.sol
docs/_Interface_IColony.md
test-smoke/colony-storage-consistent.js
test/contracts-network/colony.js

Closes #910.
I've added the two burn transaction function signatures we have on the token we provide to the 'forbidden' list of transactions, though I'm wondering if we need to take a different approach to this. Maybe preventing arbitrary transactions to a contract that (appears to be) an ERC20 that the colony has a balance in, or something? I've had to add `transferFrom` too despite arguing against that last time we looked at this, because in some ERC20 implementations (including the one the token we provide uses) you don't have to give yourself permission to `transferFrom` from yourself. That's pretty annoying, because there is a legitimate reason for a colony to want to be able to call `transferFrom`. Are we going to have to inspect a 'transferFrom` transaction further? This is …

Prevent burning of tokens by colony without appropriate bookkeeping

---

.solcover.js
.solcover.reputation.js
contracts/colony/Colony.sol
contracts/testHelpers/PreviousVersion.sol
migrations/8_setup_meta_colony.js
test-smoke/colony-storage-consistent.js

Previously, resolvers were registered as previous versions, but `.version()` was still the current version number.  This makes them respond accurately to `version`, at least, which means that relevant UI development is possible.

Have previous version resolvers respond accurately

---

contracts/colony/Colony.sol
contracts/colony/ColonyDataTypes.sol
contracts/colony/ColonyExpenditure.sol
contracts/colony/ColonyFunding.sol
contracts/colony/ColonyPayment.sol
contracts/colony/ColonyRoles.sol
contracts/colony/ColonyTask.sol
contracts/common/ContractRecovery.sol
contracts/common/ContractRecoveryDataTypes.sol
contracts/testHelpers/NoLimitSubdomains.sol
helpers/test-helper.js
test/contracts-network/colony-network.js
test/contracts-network/colony-payment.js
test/contracts-network/colony-recovery.js
test/contracts-network/colony-task-work-rating.js
test/contracts-network/colony-task.js
test/contracts-network/colony.js

Explanation / reasoning for events here can be split up:
We just didn't have events you would ordinarily expect. `PaymentFinalized` and things. So I've added them.
Mostly `agent` i.e. `msg.sender` for the event. There's no other clean way to get this as far as I can see if we're restricting ourselves to events. We _might_ be able to get clever here with TheGraph's call handlers, and not need these in most cases. Note that `FundingPotAdded` doesn't get one, because there is always another event emitted with it, and similarly the events related to signed changes to tasks don't get them, because those are triggered by the contract making an external call to itself, so would always give the colony address. To work around that, I've added `TaskChangedViaSignatures` emitting the addresses that …

Events for the event god

---

scripts/deployUnmockedColonyVersions.js

For some of the work @alicjakujawa has been doing, she needed to be able to easily deploy old versions of the contracts. The kludge that we have in the migrations was inadequate (see #916) because while those versions claimed to be old versions, they were actually version 5 contracts. That meant that events and so forth had an unexpected number of arguments (especially after #911) and so colonyJS would error out, making the development of the frontend impossible in this scenario.
This script checks out old versions as appropriate and deploys them to the existing network deployment found at the address in `etherrouter-address.json` (introduced in [this commit](https://github.com/JoinColony/colonyNetwork/commit/adf8b3e995cb3cbba4631cf09086d49a5cfdb8a8) with little fanfare at the time)).

Add script to deploy 'true' old versions of the contracts

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/ColonyDataTypes.sol
contracts/colony/IColony.sol
contracts/common/ERC20Extended.sol
helpers/test-data-generator.js
test-smoke/colony-storage-consistent.js
test/contracts-network/colony.js

In order for 'unlock token' to appear as an action in the frontend, there needs to be an event for it to key off of. The token is already deployed, so we can't alter is there, so I've added a function to the colony that calls `unlock` on the token. To work on the frontend we'll have to give the colony `owner`ship of the token, but arguably we should have been doing that anyway.
I had to steal my changes in `test-data-generator` from #907 to write the test, so they're here too.

Add function for a colony to unlock its own token, if owner

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/ColonyFunding.sol
contracts/colony/IColony.sol
docs/_Interface_IColony.md
helpers/constants.js
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-permissions.js

Closes #920 
This PR adds two new root-level functions: `emitDomainReputationReward` and `emitSkillReputationReward`, which do what they say on the tin.

Add reputation rewards

---

.solcover.js
.solcover.reputation.js
contracts/colony/Colony.sol
contracts/colony/ColonyFunding.sol
contracts/colony/ColonyStorage.sol
contracts/colony/IColony.sol
contracts/testHelpers/RequireExecuteCall.sol
contracts/testHelpers/TestExtensions.sol
contracts/tokenLocking/TokenLocking.sol
contracts/tokenLocking/TokenLockingDataTypes.sol
contracts/tokenLocking/TokenLockingStorage.sol
docs/_Interface_IColony.md
helpers/test-helper.js
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-network-extensions.js
test/contracts-network/colony-reward-payouts.js
test/contracts-network/colony.js
test/contracts-network/token-locking.js
test/extensions/token-supplier.js

Closes #921 
Supports #915, allowing extensions (here, `VotingToken`) to lock & unlock user's tokens.

Extension token locking

---

contracts/colonyNetwork/ColonyNetworkMining.sol
helpers/test-helper.js
test-chainid/chainid-dependent-behaviour.js

If we've bridged CLNY, burning the bridged token does nothing to the supply on mainnet, and the bridge will just hold the tokens for eternity (I think?). For now, send the CLNY to the metacolony. We can decide to unbridge and 'truly' burn down the line, if we like.

Do not burn CLNY on Xdai during mining

---

contracts/colony/Colony.sol
contracts/colony/ColonyRoles.sol
helpers/constants.js
scripts/deployUnmockedColonyVersions.js
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-network.js
test/contracts-network/colony-permissions.js

Could be a worse crop, all things considered...
1. We were not correctly tracking the recovery role count when using `setUserRoles`. This fixes that. The consequences of this are frustrating, and are going to be dealt with on the frontend to a limited extent. Basically, the frontend will prevent people upgrading unless there is exactly one person with the recovery role. It can tell this from events, and not from `numRecoveryRoles`, which isn't incremented when using `setUserRoles`, which is all the frontend uses. `numRecoveryRoles` will then be correct, and the users can upgrade and re-award the recovery roles as they see fit.
If someone upgrades without doing that, by interacting directly with the contracts, then not even recovery mode can save them, as `numRecoveryRoles` is protected, …

Fix first issues arising from actual use

---

packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js

Doing two things here:
1. Remove all ganache-specific functionality from the miner. Ganache seem to have finally got their gas estimation up to snuff (or rather, I finally noticed that they did [nearly two years ago](https://github.com/trufflesuite/ganache-cli/releases/tag/v6.4.2-beta.0)), so can rip this out. This was why the miner was having grief in the real world - [this line](https://github.com/JoinColony/colonyNetwork/compare/develop...maint/miner-gas-price#diff-0a992c98d4c940fcc61183e5a53e2df4edbaa11fdab2eb89f3621ee7a8622ec2L590) needed changing going from [Ethers v4 to v5](https://docs.ethers.io/v5/migration/ethers-v4/) but wasn't tested, because all of our tests run against Ganache.
2. If connected to Xdai, only use a gas price of 1Gwei rather than the mainnet gas prices.

Minor real-world based changed to reputation miner

---

contracts/colonyNetwork/ColonyNetwork.sol
test/contracts-network/reputation-update.js

In the reputation tree, reputation for an address in a skill is stored at the key generated from the concatenation of the colony address, the skill id, and the address that holds the reputation. We also need to store the total reputation in a skill in a colony. This is stored in the same tree, but at a key generated from the concatenation of the colony address, the skill id, and the zero address.
With the introduction of expenditures, and more obviously the ability to award and slash reputation owned by arbitrary addresses, we accidentally added the ability for colonies to mess around with the zero-address reputation, which will cause votes and rewards to behave in unexpected ways. I believe a colony can only mess things up for themselves (at least while we're the only miners... I haven't …

Fix bug in reputation mining around the zero address

---

packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/adapters/console.js
packages/reputation-miner/bin/index.js

While helping Olga with motions and disputes, which requires running the miner locally in a dev context, we ran across several things that needed to be configurable to make life as easy as possible. The app is using `feat/miner-fixes-backported` for now, as we've bumped the version number on the contracts but no corresponding colonyJS release exists, but we should have these fixes in the `develop` branch for when there is.
* Make the port the oracle responds on configurable.
* Add an option for the number of blocks to wait before ingesting a new reputation state. 
* Make `fromBlock=1` work for syncing, rather than having to judiciously choose the first block where there were two reputation mining contracts.
* Make `minerAddress` on the command line explicitly a string to avoid it being …

Add new convenience functionality to the miner

---

contracts/colony/ColonyStorage.sol
contracts/colonyNetwork/ColonyNetworkMining.sol
helpers/test-helper.js
test-chainid/chainid-dependent-behaviour.js
test/contracts-network/colony.js

Two unrelated changes, but both small so I thought I'd bundle them up.
* Jack reported [a large list of incoming transactions](https://www.notion.so/colony/Metacolony-incoming-fees-are-all-denominated-in-CLNY-and-from-the-same-address-8d27401478b6436785852b33812338e2) in the metacolony. These are from the xDai implementation of the `burnUnneededRewards` function, which even if there are no rewards, went ahead and did a 0-value transfer anyway. We shortcircuit the 0 case now, which is good for gas, and good for the app. To test this, I also refactored the helper functions around testing for the presence / lack of presence of an event in a transaction.
* When we added expenditures and payments, bootstrapping got left behind. This PR also prevents bootstrapping if a payment or an expenditure …

Slight mining improvement and bootstrap correction

---

contracts/colony/Colony.sol
contracts/colony/ColonyFunding.sol
contracts/colony/ColonyStorage.sol
contracts/colony/IColony.sol
docs/_Interface_IColony.md
package.json
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-arbitrary-transactions.js
test/contracts-network/colony.js

Okay, this is a first pass at this ready for feedback. I'm not completely happy with merging this yet (might be able to extend this idea to other 'forbidden' transactions), but happy enough for it to start being reviewed. 
Basically, this introduces some more internal accounting so that when a colony `approve`s another contract to take its tokens via the very common ERC20 interface, we only allow tokens to be removed from the root ~~address~~ domain. Tokens may be taken, but the internal bookkeeping won't update until another approve transaction to the same address is made, or any user calls the `updateApprovalAmount` function.

First pass at allowing arbitrary approve transactions

---

helpers/test-helper.js
migrations/8_setup_meta_colony.js
test-smoke/colony-storage-consistent.js
test/reputation-system/client-sync-functionality.js

Staking loads of CLNY in the migration during setup was causing issues with the app dev environment when the miner tried to submit more entries but blocktime was fast-forwarded at the same time. Easiest solution was to stake only the minimum amount of stake.

Only use required stake in migration

---

contracts/extensions/VotingReputation.sol
test/extensions/voting-rep.js

If no-one stakes on a side, and we attempt to query staker rewards on that side, `getStakerReward` errors out. This is because it divides by zero. This doesn't affect anything on the contracts (if no-one staked, then no-one can claim for that side, so the fact that it would divide by zero is irrelevant), but this proved annoying for the frontend team. Dividing by zero is something that we shouldn't do anyway, so let's just return 0 in this scenario (which will always be correct).

Make getStakerReward behaviour consistent

---

.gitmodules
contracts/extensions/FundingQueue.sol
contracts/extensions/VotingReputation.sol
test-smoke/colony-storage-consistent.js
test/extensions/coin-machine.js
test/extensions/funding-queue.js
test/extensions/voting-rep.js
test/reputation-system/root-hash-submissions.js

This PR does two things
1. Fixes a bug where if a motion was escalated, but not staked fully, incorrect amounts of stake were returned to users (as `requiredStake` was used, rather than the amount that was actually staked), resulting in some users not being able to claim their stake.
2. Fixes a bug where if multiple people staked, not everyone would be able to claim their rewards in some circumstances. This was because the WAD-based calculations would round up, so e.g. if everyone staked 1/6th of the required value, their stakes would be rounded to 0.166...67 of the required value, slightly more than they had actually staked. I have taken this round-up functionality of the WAD calculation and dealt with it with extreme prejudice, and it now always rounds down, in line with the rest of …

Fix maths bugs in ReputationVoting (and potentially elsewhere)

---

contracts/extensions/VotingReputation.sol
test-smoke/colony-storage-consistent.js
test/extensions/voting-rep.js

These changes mean that more of the reward pool will be paid out - essentially, the pool is split (notionally) between all those who voted, rather than all of those who could have voted. Note that you are still required to reveal your vote to receive the rewards, so it remains possible for much of the pool to not be paid out if many people who voted do not reveal their vote for whatever reason.
I've also added a new function called `getVoterRewardRange` which can be used to see what the potential payout for a user will be should they choose to vote and then reveal.

Change how rewards are calculated for vote revealers

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/ColonyFunding.sol
contracts/colony/IColony.sol
contracts/extensions/VotingReputation.sol
docs/_Interface_IColony.md
helpers/test-data-generator.js
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-arbitrary-transactions.js
test/contracts-network/colony-expenditure.js
test/contracts-network/colony-funding.js
test/contracts-network/colony-payment.js
test/contracts-network/colony-permissions.js
test/contracts-network/colony-reward-payouts.js
test/contracts-network/colony-staking.js
test/contracts-network/colony-task.js
test/contracts-network/colony.js
test/contracts-network/reputation-update.js
test/contracts-network/token-locking.js
test/extensions/voting-rep.js
test/reputation-system/dispute-resolution-misbehaviour.js
test/reputation-system/root-hash-submissions.js

This is my take at fixing up `moveFundsBetweenPots` so that what movement of funds are allowed is consistent regardless of whether the function is being executed directly or a motion has been made.
I tried a couple of other ways, but there just simply isn't enough information provided in the combination of the existing action and the existing motion creation function. You have to prove:
The domain I have the permission in is a parent of the 'fromPot' domain
The domain I have the permission in is a parent of the 'toPot' domain
The domain the vote is taking place in is a parent of the 'fromPot' domain
The domain the vote is taking place in is a parent of the 'toPot' domain
But we only have three proofs, between `createMotion` and the action if we create special functions to extract the …

Permission moveFundsBetweenPots properly for voting

---

contracts/extensions/OneTxPayment.sol
test-smoke/colony-storage-consistent.js
test/extensions/one-tx-payment.js

After #949, with the addition of `getCapabilityRoles` to extensions, we had to bump the version of all extensions that are currently deployed. This has tripped us up in QA with `oneTxPayment`, which I'm bumping here before deploying a new version of. The deployment of `VotingReputation` was bumped already, and nothing else is deployed, so I think this is all that's needed. We really need to figure out a better way of tracking this sort of thing though, for both ours and the frontend team's benefit.

Bump version on OneTxPayment

---

contracts/reputationMiningCycle/ReputationMiningCycleCommon.sol
contracts/reputationMiningCycle/ReputationMiningCycleRespond.sol
helpers/constants.js
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js

The 24 hour duration was hard coded in a fair number of places. This PR removes that dependency, and means that, going forward, changing the mining cycle duration will just involve replacing the `miningCycleResolver` address on the network contract, with no miner changes required.
This PR also drops us down to a 1 hour duration on the contracts side. Deployments wise, I will deploy a new version of the miner, which should work with the old cycle, and then deploy the new resolver to switch us to the one hour period once we see that's working.

Increase flexability miner shows towards mining cycle duration

---

contracts/extensions/VotingReputation.sol
test/extensions/voting-rep.js

In the drop-down for a colony's native token in the app, there are three classes of token. One of those classes is the number of tokens a user has staked. Currently, this is obtained by looking at all the `MotionStaked` events from the reputation voting extensions, and removing any that have a corresponding `MotionRewardClaimed` event, leaving only `MotionStaked` events that, presumably, correspond to unclaimed, staked tokens.
However, if someone has staked, and is getting nothing back (because they were on the losing side and suffered a 100%-0% defeat in the voting), we currently don't let them claim, which means no `MotionRewardClaimed` event is sent, and so it looks like those tokens are staked perpetually. And on some level, they are - they're just not getting them back.
This PR means …

Allow motion stakes to be claimed even if no reward coming

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/IColony.sol
contracts/extensions/VotingReputation.sol
contracts/tokenLocking/TokenLocking.sol
contracts/tokenLocking/TokenLockingDataTypes.sol
docs/_Interface_IColony.md
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-arbitrary-transactions.js
test/contracts-network/colony-staking.js
test/extensions/voting-rep.js

We were missing events for some function calls in TokenLocking. This adds them. Closes #957.
We were not checking that, in the case that the action domain and the voting domain were the same, that the supplied ChildSkillId was UINT256Max, which we do elsewhere. The only practical effect I can see right now was that motions-to-create-motions would be wrong, and that's a very niche case, but better to nip this one in the bud before it trips us up down the line.
Probably the biggest thing in this branch, but a pretty straightforward addition, as we've discussed - deprecating the old arbitrary transaction function and replacing it with something identical that loops over two arrays containing the target and the transaction data. Closes #933. The test is pretty basic - on reflection, perhaps …

A number (currently four) of smallish changes and improvements

---

contracts/extensions/CoinMachine.sol
contracts/extensions/ColonyExtension.sol
contracts/extensions/FundingQueue.sol
contracts/extensions/OneTxPayment.sol
contracts/extensions/VotingReputation.sol
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-arbitrary-transactions.js
test/extensions/coin-machine.js

Closes #952 
- Introduce a new initialisation parameter, `userLimitFraction`, which governs what % of the total sold amount any user can buy. If the total amount of tokens sold is less than `maxPerPeriod`, that value is used.
- Introduce `getUserLimit` which returns the total amount of tokens any given user can purchase, across many periods.
- Replace `getNumAvailable` with `getSellableTokens`, which does not take into account the token balance, only the remaining tokens in the period.
- Introduce `getMaxPurchase` which  returns the amount of tokens a user can purchase in the current period, taking into account all factors (token balance, user limits, and remaining tokens in the period)

Per-user Coin Machine limits

---

packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/bin/index.js

With the mining client out in the real world, and not just on QA, we encountered a couple of hiccups.
1. 1Gwei for gas on Xdai is no longer always enough. So introduce querying the blockscout endpoint to figure out what an appropriate gas price is. In addition, we now go for 'average' rather than 'safeLow' to help guard against a sudden change in gas price. The Blockscout endpoint (for xdai) and the Etherscan endpoint for mainnet are annoyingly different - there's a factor of 10, and some of the gas labels are different, but I've tried to accommodate for the (relevant) differences.
2. Introduce a new argument for the miner, `--providerAddress`, that allows an arbitrary RPC endpoint to be specified. This was because as it was, it was impossible to point the miner at e.g. a Quicknode …

Mining client updates due to the real world

---

packages/reputation-miner/ReputationMinerClient.js

As we enter the 'real world' with more and more use of the app, we're discovering things about the miner and oracle. There way the miner was set up, if it was queried before it had come up, it crashed and refused to respond to future requests. By moving the server creation to after all other initialisation processes have been completed, we avoid this issue.
Note this is going in to `master` - this fix is already deployed to the nodes we're running.

Only bring up oracle once initialisation complete

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/ColonyDataTypes.sol
contracts/colony/ColonyExpenditure.sol
contracts/colony/ColonyFunding.sol
contracts/colony/ColonyStorage.sol
contracts/colony/IColony.sol
contracts/extensions/EvaluatedExpenditure.sol
contracts/extensions/VotingReputation.sol
docs/_Interface_IColony.md
migrations/9_setup_extensions.js
scripts/check-recovery.js
scripts/check-storage.js
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-expenditure.js
test/extensions/evaluated-expenditures.js

Closes #950 
- Add an optional `Locked` state where the owner can no longer change values.
- Add a new `Active` pseudo-state, consisting of either `Draft` or `Locked`.
- Restricted editing and cancellation to `Draft`, allow to transfer and finalize from `Active`.
- Add utility functions to set recipients, skills, claimDelays, and payouts in batches.
- Add ability to emit metadata for expenditures.
- Allow the owner to edit the payout modifiers, in the `Draft` state.
- Introduce an extension, `EvaluatedExpenditures`, which allows the owner to edit the payout modifiers in the `Locked` state.

Add new Expenditure functionality

---

packages/reputation-miner/ReputationMinerClient.js

Been working on running multiple miners on QA. Had an issue where multiple miners would work, but only for one cycle. After correctly submitting the first time, one of the (two) miners would just not submit in any subsequent cycles. They would after a restart, though. The reason was this line - which is correct, but in the wrong place.
In the original position, it meant that `submissionIndex`, which tracks how far through the possible submission array the client has submitted this cycle, was only reset for the client that submitted the `confirmHash` transaction. That's obviously incorrect, and should be reset when the cycle completes and the active mining cycle contract address changes - as at the start of a new cycle, no-one has submitted anything.
This is going in to `master`, as it is …

Correctly track whether miner has submitted in cycle

---

contracts/extensions/VotingReputation.sol
test-smoke/colony-storage-consistent.js
test/extensions/voting-rep.js

While we've been messing around with the gas estimation / buffer process on the frontend, it actually doesn't solve an underlying problem. A bad actor could, in theory, finalize a motion with exactly the right amount of gas that means the motion fails its execution but the finalize transaction succeeds. 
I believe this is the 'path of least resistance' to fix the issue. The frontend will require no changes, and a 'proper' solution can be incorporated down the road when the frontend team have bandwidth to change the flow in the frontend (e.g. why can't users claim their tokens once its finalizable? With this solution, in the event of a motion that's corresponding transaction is now failing, users will have to wait a week to be able to reclaim)

Cannot confirm failing motion before a week passed

---

contracts/colony/Colony.sol
contracts/colony/ColonyDataTypes.sol
test/contracts-network/colony-permissions.js

Actions need events for the frontend to work properly, so we need to add them to these functions which the frontend team is developing against.
We believe that using the same event for all of these is fine, context (i.e. the skill id and the amount being positive/negative) should allow them to be distinguished.
Not wild about `customReputationUpdate` as a name, open to suggestions.

Add events for reputation award/smite

---

contracts/colony/ColonyFunding.sol
contracts/colony/ColonyPayment.sol
contracts/colony/ColonyStorage.sol
contracts/colony/ColonyTask.sol
test/contracts-network/colony-expenditure.js
test/contracts-network/colony-network-extensions.js
test/contracts-network/colony-payment.js
test/contracts-network/colony-task.js

Closes #991 (when it's done).
Currently, this just has some failing tests!

Change how extensions receive tokens and reputation

---

.circleci/config.yml
contracts/colony/Colony.sol
helpers/constants.js
package.json
scripts/versioningCheck.sh
test-smoke/colony-storage-consistent.js

It's post-release, so to help with front-end dev we bump the version of the colony contract. I've also added a script that checks if a version should have been bumped and whether it has to help prevent things like #990 from happening again.

Bump colony version and add version check script

---

packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/bin/index.js

The best laid plans...
[It turns out](https://github.com/ethers-io/ethers.js/discussions/1960) that the fallback provider in Ethers does not support the `blockTag` override, which is fine when everything is working, but is a problem if the service falls behind/restarts and tries to sync. So remove it for now. Note that this means that we're only using one provider (all providers past the first that are passed on the command line are ignored).

Do not use Fallback provider for now in miner/oracle

---

contracts/extensions/CoinMachine.sol
contracts/extensions/EvaluatedExpenditure.sol
contracts/extensions/FundingQueue.sol
contracts/extensions/OneTxPayment.sol
contracts/extensions/TokenSupplier.sol
contracts/extensions/VotingReputation.sol
contracts/extensions/Whitelist.sol
scripts/versioningCheck.sh
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-arbitrary-transactions.js

The version check script for extensions was wrong - when #962 was rebased, should have thrown a big wobbly. This fixes it, and increments all the versions that should have been at the time.

Fix version check script, bump needed versions

---

contracts/extensions/CoinMachine.sol
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-arbitrary-transactions.js
test/extensions/coin-machine.js

In light of [colonyDapp#2995](https://github.com/JoinColony/colonyDapp/issues/2995), the behaviour we understood was desired to be implemented was not actually desired.
The user limit is now enforced against the total number of tokens already sold plus those that are still to be sold that have already been given to coinmachine. This means that a user can, if the max sold per period allows, buy their entire allowance in one transaction at the start of the sale.
This means that, if a sale is terminated early, some users may have more than their allowance. This has been deemed acceptable.

Change how CoinMachine limits are enforced

---

scripts/provision-token-contracts.sh

Working out the kinks w.r.t. having bumped colonyToken to a new version, specifically how we import the pinned build files.
Merging into master to fix that build, which we can then back-merge into develop.

Work with updated colonyToken repo

---

migrations/8_setup_meta_colony.js
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-expenditure.js
test/contracts-network/colony-network-extensions.js
test/contracts-network/colony-network-recovery.js
test/contracts-network/colony-payment.js
test/contracts-network/colony-task.js
test/contracts-network/reputation-basic-functionality.js
test/contracts-network/reputation-update.js
test/contracts-network/token-locking.js
test/extensions/coin-machine.js
test/extensions/evaluated-expenditures.js
test/extensions/funding-queue.js
test/extensions/one-tx-payment.js
test/extensions/token-supplier.js
test/extensions/voting-rep.js
test/extensions/whitelist.js
test/reputation-system/client-sync-functionality.js

Speed up our test suite by removing redundant deployments & transactions, specifically the redundant network & metacolony deployments at the beginning of test suites (truffle's snapshotting feature appears to bring us back to the correct state automatically).
Non-rigorous profiling suggests that the tests are indeed faster, modulo any endogenous effect caused by Circle's infrastructure. See [original](https://app.circleci.com/pipelines/github/JoinColony/colonyNetwork/4011/workflows/460eccb6-82fc-4c5b-bb84-dbdb488baa8b/jobs/20286) and [improved](https://app.circleci.com/pipelines/github/JoinColony/colonyNetwork/4030/workflows/33d61557-f29e-4e70-94be-b09458fd299e/jobs/20400) build times.

Faster tests

---

packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/bin/index.js
test/reputation-system/reputation-mining-client/client-auto-functionality.js

Adds:
* Some extra logging
* Appropriately waits for transactions during disputes
* More timeout resilience
* Copes with blocks that do not advance the dispute process
Should incorporate #1013 or vice-versa.

Miner client updates as real world imperfect

---

contracts/colonyNetwork/ColonyNetworkMining.sol
contracts/colonyNetwork/ColonyNetworkStorage.sol
contracts/colonyNetwork/IColonyNetwork.sol
contracts/reputationMiningCycle/ReputationMiningCycle.sol
contracts/reputationMiningCycle/ReputationMiningCycleBinarySearch.sol
contracts/reputationMiningCycle/ReputationMiningCycleCommon.sol
contracts/reputationMiningCycle/ReputationMiningCycleRespond.sol
docs/_Interface_IColonyNetwork.md
helpers/test-helper.js
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/test/ReputationMinerTestWrapper.js
test-chainid/chainid-dependent-behaviour.js
test-gas-costs/gasCosts.js
test-smoke/colony-storage-consistent.js
test/contracts-network/reputation-basic-functionality.js
test/extensions/funding-queue.js
test/extensions/voting-rep.js
test/reputation-system/dispute-resolution-misbehaviour.js
test/reputation-system/disputes-over-child-reputation.js
test/reputation-system/happy-paths.js
test/reputation-system/root-hash-submissions.js
test/reputation-system/types-of-disagreement.js

Closes #1002 
Draft status, as not ready to merge, but after feedback.
Implements what Daniel and I vaguely talked about a while ago. Basically, everything stays the same, but instead of using `msg.sender` during mining, we instead call a function that either returns `msg.sender` (i.e. the fallback case should be the existing functionality) or, if a delegation has been awarded to `msg.sender`, returns the address they are allowed to mine on behalf of.

Delegated mining

---

contracts/colonyNetwork/ColonyNetworkMining.sol
contracts/reputationMiningCycle/ReputationMiningCycle.sol
contracts/reputationMiningCycle/ReputationMiningCycleCommon.sol
packages/reputation-miner/ReputationMinerClient.js
test/reputation-system/root-hash-submissions.js

Two sort-of-related updates: 
* When a miner is punished, the stake was removed from their Obligation in TokenLocking, but not from the mapping `miningStakes` on colonyNetwork. This PR now removes it from both.
* When querying a miner's stake in the contracts and the client, we mostly used `getObligation` on tokenLocking (which is why the above error wasn't caught by our tests), looking at the obligation they had to the colonyNetwork contract in CLNY tokens. While these numbers have to be the same currently, there's no guarantee of that being the case in the future. This change future-proofs us should a new feature change this.
This PR is based against `master`, and I would intend to do a release and deployment once merged.

Fix bookkeeping and querying around mining stakes

---

.gitignore
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/bin/index.js
test/reputation-system/reputation-mining-client/client-auto-functionality.js

Two (mostly) unrelated improvements:
* When syncing past cycles, no need to make the justification tree - they're historical, the time for disputes has passed, so no need to prepare for how we might respond to a dispute. This could be better; some of the lifting to work out keys/values is still done, it's just that the tree that the values are added to performs no-ops and returns nothing, rather than actually building the tree, and so will return quicker than generating the tree and associated proofs. I did is this way because it was easier than picking apart all the bits that generate the justification tree, which are a bit scattered.
* Fast-resume if we've made a submission to the cycle. When we generate the next reputation state and save it to the DB, I also save the data required to …

Miner (hopefully) faster sync, faster startup if submission made

---

contracts/extensions/CoinMachine.sol
helpers/test-helper.js
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
test-smoke/colony-storage-consistent.js
test/reputation-system/reputation-mining-client/client-auto-functionality.js

~_NB based on #1020 so cannot be merged until that is. Can be reviewed, however_~
A variety of fixes here:
* The message to refill an address with Ether was not taking in to account delegated mining.
* The mysterious-errors-overnight error, I think, is because by default Nethermind refuses transactions with a gas price lower than 1.1Gwei; I think this is a consequence of EIP1559, but not 100% sure. When gas is higher, it's not seen, but I _think_ that overnight, gas drops below 1.1Gwei according to the Blockscout oracle, which we then use and our node rejects. Didn't want to overly tinker with the node to change it, given it's in production, and accommodating the defaults seems reasonable, anyway.
* If we had been delayed replying to a challenge, we'd invalidate our opponent before …

Fix further wrinkles in the mining client

---

packages/reputation-miner/package.json
yarn.lock

This adds support for the latest node LTS version 16.14.0

Upgrade apicache to v1.6.3

---

helpers/test-helper.js
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
test/reputation-system/client-core-functionality.js
test/reputation-system/client-sync-functionality.js
test/reputation-system/reputation-mining-client/client-auto-functionality.js

Several improvements here:
We tried syncing from scratch on QA and ran in to difficulty; I wasn't confident I hadn't just done a load of messing around on QA at some point, so assumed that the sync was good.
When trying to sync up production from scratch, where I was confident that we didn't have such issues, we ran in to problems again. I've tracked them down to a negative reputation update, and the origin skill key being incorrectly worked out against the _latest_ reputation update log, rather than the _historical_ reputation update log that we're trying to sync against.
~~Leaving this as a draft for now, as I've not successfully sync'd production yet, so we might need further changes, but it's looking promising:~~
Production sync'd from scratch successfully, so will be taking this out …

Fix miner sync and improve oracle performance

---

contracts/colony/Colony.sol
contracts/colony/ColonyDataTypes.sol
contracts/extensions/CoinMachine.sol

Updating CoinMachine's `TokensBought` event to emit the token address, and the `TokenUnlocked` event to include the agent. Also bumping CoinMachine's version to 5.

Two new events to support frontend

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/ColonyDataTypes.sol
contracts/colony/IColony.sol
test-smoke/colony-storage-consistent.js
test/contracts-network/colony.js

Based on conversations around [this issue](https://github.com/JoinColony/colonyDapp/issues/3335) I've added a new function that can be used by the dapp and expected to emit (the IPFS hash of) a delta, rather than a complete blob, when interacting with the colony metadata. The structure is entirely up to the dapp team, we're totally agnostic here (as we are with the existing colony metadata event).
Another option would be to keep using the existing event, but for deltas and whole blobs, but by adding this event it's much easier for the dapp team to develop against. 
By having both, we allow essentially a 'checkpointing' system to be used if the list of changes gets very long (resulting in long load times as the entire edit history is loaded from IPFS). We expect the rough flow in the dapp …

Add MetadataDelta event and function

---

package.json
scripts/start-reputation-oracle.js

I added this script to make it easier to start the reputation oracle for development purposes.
It gets the ganache accounts from the RPC node and the `etherrouter-address` from the corresponding json file.

Add dev script to easily start reputation oracle

---

contracts/colony/IColony.sol
contracts/colony/IMetaColony.sol
contracts/colonyNetwork/ColonyNetwork.sol
contracts/colonyNetwork/ColonyNetworkDeployer.sol
contracts/colonyNetwork/IColonyNetwork.sol
contracts/extensions/VotingReputation.sol
contracts/tokenLocking/ITokenLocking.sol
docs/_Interface_IColony.md
docs/_Interface_IColonyNetwork.md
docs/_Interface_IMetaColony.md
docs/_Interface_ITokenLocking.md
scripts/versioningCheck.sh

Closes #1035 
I also took the liberty to fix some of the NatSpec warnings we got when running build:docs.

Replace DEPRECATED with @deprecated

---

packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
test/reputation-system/client-sync-functionality.js

Adds a `/latestState` endpoint to the oracle, that downloads an SQLLite file that only contains the most recent (confirmed) hash.
In production, planning on putting this behind a fairly long Cloudflare cache (e.g. a day); it might end up not being the latestState, but it'll be a recent one (the last day or so, if the cache is that long), and will be easy(ish) to sync from there. 
Because of dealing with two databases, I refactored `createDB`, making it static and taking a database as an argument.

Add endpoint to oracle to facilitate fast-sync

---

test/reputation-system/client-sync-functionality.js

For whatever reason, we've started seeing [this](https://app.circleci.com/pipelines/github/JoinColony/colonyNetwork/4637/workflows/71d7a592-2dd8-4538-b05c-1f7703cd66fd/jobs/24656) error on multiple builds; this missing await is the culprit.

Add missing await to miner sync test

---

contracts/extensions/CoinMachine.sol
test-smoke/colony-storage-consistent.js
test/extensions/coin-machine.js

Porting the fix for https://github.com/JoinColony/coinMachine/issues/81 into this repo

Fix CoinMachine token accounting bug

---

packages/reputation-miner/ReputationMiner.js

When I made the `noProof` endpoint, I removed the logic around building the tree, as it wasn't needed. But I could have also removed the bit where it loads all reputations in the state from the database! So I've done that. Similarly, the proof endpoint will now not load all reputations just to check if the requested reputation does not exist.

Improve noProof oracle endpoint and fast-failure of proof endpoint

---

packages/metatransaction-broadcaster/MetatransactionBroadcaster.js
test/packages/metaTransactionBroadcaster.js

[Some spotty tests](https://app.circleci.com/pipelines/github/JoinColony/colonyNetwork/4687/workflows/40ffdd4e-f7c0-4622-b067-f542948f33c3/jobs/25046) came down to some behaviour here, where the oracle took a long time to responsd, and on thinking about it it did raise a potential issue with the broadcaster, so have decided to change its behaviour slightly (already cleared with the frontend). By including the gas limit with `estimateGas`, we return as quickly as possible. We lose information about whether the transaction fails or is too expensive, but I think that's fine to prevent people deliberately trying metatransactions that use a lot of gas to slow down / DoS the oracle (which is still possible, just harder).

Make metatransaction broadcaster estimateGas call stricter

---

package.json
test-smoke/colony-storage-consistent.js
truffle.js
yarn.lock

When we did #1052, we upgraded to the new `ganache`, but we clung on to `ganache-core` for the smoke tests. This was because the [internals of the provider were no longer available](https://github.com/trufflesuite/ganache/issues/3076), but the latest release of ganache has provided a mechanism (`eth_getProof`) to get the state hash again. 
Unfortunately this does mean that the state hashes change for this upgrade (see the issue in the ganache repo for the details), but should behave as before going forward.

Remove ganache-core

---

contracts/extensions/VotingReputation.sol
test-smoke/colony-storage-consistent.js
test/extensions/voting-rep.js

Closes #1068.
Not happy with the ternary, would very much like a function with a more understandable if statement, but can't come up with a semantic name for that function beyond `finalizableOrFinalized`. Please suggest something!
Should the 'special action' be longer than just a signature? Obviously it's all meaningless, but...

Add support for decisions that take no action

---

packages/metatransaction-broadcaster/Dockerfile
packages/metatransaction-broadcaster/ExtendedNonceManager.js
packages/metatransaction-broadcaster/MetatransactionBroadcaster.js
packages/metatransaction-broadcaster/package.json
packages/reputation-miner/Dockerfile
test/extensions/voting-rep.js
test/packages/metaTransactionBroadcaster.js
yarn.lock

Based on #1070 (as this branch is being used by the frontend team), so no merging for now.
The main issue with the metatransaction broadcaster in the real world is to do with nonces for the account doing the broadcasting. With the current (committed, though not deployed) implementation, two requests for a metatransaction at the same time would end up with the same nonce, and one wouldn't be accepted. This is obviously bad, so I started using the experimental [NonceManager](https://docs.ethers.io/v5/api/experimental/#experimental-noncemanager) from Ethers, which gives us finer control over nonces. Basically, it signs transactions with sequential nonces as requests come in, regardless of what the RPC node it is connected to tells it.
There are issues with this - if the nonce gets …

Make the metatransaction broadcaster more robust

---

helpers/test-helper.js
packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/test/ReputationMinerLongTransactionMined.js
test/reputation-system/reputation-mining-client/client-auto-functionality.js

A recent incident revealed the reputation miner was a bit brittle. It submitted a new reputation hash, but the account being submitted from had (very nearly) run out of xdai, so the transaction was not able to be mined, and just sat pending in the pool with the client `await`ing it. When I topped up the miner, the transaction was mined, and the miner continued, but had missed several cycles and so ended up out-of-sync. This PR is intended to fix that issue, by having the miner check that the on-chain accepted state is the one it expects before applying a reputation update log and continuing to mine.
While I was in there, I took the opportunity to abstract some test logic that was repeated in the relevant tests.

Make miner slightly more cautious about state

---

.circleci/config.yml
.gitignore
packages/metatransaction-broadcaster/Dockerfile

I found some forgotten `yarn` references that sneaked in between two rebase cycles. Here's the fix for them.

`npm` migration hotfixes

---

.solcover.extensions.js
.solcover.reputation.js
.solcover.upgrade.js

We've seen [this issue](https://app.circleci.com/pipelines/github/JoinColony/colonyNetwork/4931/workflows/7cd8361c-b366-4c33-ac6f-5bf6b809a315/jobs/27125) in a [lot of builds](https://app.circleci.com/pipelines/github/JoinColony/colonyNetwork/4921/workflows/2487d6f6-097f-434e-8eba-4f62c470529d/jobs/26996) lately. It was intermittent, though, and so tough to pin down. ~~I was also unable to reproduce locally. It ended up being due to [this issue](https://github.com/gotwarlost/istanbul/pull/940) now that we're on Node 14 (and I'm attributing the inablility to reproduce locally due to `node`/`npm` version weirdness I've got going on locally).~~
~~I ended up forking `istanbul-combine` to use a fixed `istanbul` under the hood, which seems to solve the issue.~~
~~Unfortunately, the resulting …

Use self-consistent coverage configurations for separate runs

---

helpers/test-helper.js
test/extensions/staked-expenditure.js

Looks like we got away with this one - nothing was overlooked in this repository, except one test where we [decided to remove the functionality it tested](https://github.com/JoinColony/colonyNetwork/pull/1045#discussion_r922224613)

Fix incorrect refactor of checkErrorRevert

---

contracts/extensions/StreamingPayments.sol
test/extensions/streaming-payments.js

There's a bug in Streaming Payments that my multicall work uncovered. This PR fixes it.
EDIT: I think that function really should be expecting the expenditure id, but it's much more gas efficient like this.

Fix streaming payment extension

---

scripts/versioningCheck.sh

The latest release now uses `npm` not yarn, so we don't have dance around quite so many houses with the version check script (and, indeed, trying to do so broke the builds).

Update versioning check script

---

contracts/extensions/ColonyExtension.sol
contracts/extensions/FundingQueue.sol
contracts/extensions/StakedExpenditure.sol
contracts/extensions/votingReputation/VotingReputation.sol
contracts/testHelpers/VotingReputationMisaligned.sol
test-smoke/colony-storage-consistent.js
test/extensions/funding-queue.js
test/extensions/staked-expenditure.js
test/extensions/voting-rep.js

Checking reputation proofs is generally useful functionality. Rather than have extensions re-implement, let's provide a common function.

Move checkReputation to ColonyExtension

---

contracts/colony/Colony.sol
contracts/colony/ColonyArbitraryTransaction.sol
contracts/colony/ColonyDataTypes.sol
helpers/constants.js
helpers/test-helper.js
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-arbitrary-transactions.js

We try to make sure that every call has an associated event, and arbitrary transactions not having one has finally come up as an issue in the frontend.
Only tricky thing here was improving `eventMatchArgs` to accommodate bytes.

Add event for arbitrary transactions

---

contracts/metaTxToken/MetaTxToken.sol
helpers/test-data-generator.js

Strictly, MetaTxToken was not [EIP 2612 compliant](https://eips.ethereum.org/EIPS/eip-2612) as it did not have the `nonces` getter. This has finally tripped someone up, so adding it so that it can percolate through the stack at some point for new deployments, at least.

Add nonces public getter to MetaTxToken to actually be EIP2612 compliant

---

contracts/colony/Colony.sol
contracts/colony/ColonyTask.sol
test/contracts-network/colony-task.js

ColonyTask was missing the check on the return from `ecrecover`, which returns 0 for an invalid signature, which, in the case of some roles not being set for a task, allowed an invalid signature to be used to call functions on the task.

Add check for ecrecover in ColonyTask

---

packages/metatransaction-broadcaster/Dockerfile
packages/metatransaction-broadcaster/MetatransactionBroadcaster.js
packages/package-utils/updateGasEstimate.js
test/packages/metaTransactionBroadcaster.js

Closes #1111 . We want people using the safe-control feature to not be obliged to pay for the bridging transaction on the Gnosis Chain side, so have whitelisted the two (currently known / cared about) bridge contracts, and allowed calls to the arbitrary transactions functions on a colony to call exactly `requireToPassMessage` on those contracts and still be eligible for using our metatransaction broadcaster.
Also fixes an untracked bug where, if the gas-price oracle used returned certain values, a non-integer would be passed to hexlify which would error. That should now no longer be possible, regardless of what value is returned by the oracle.
Based on #1113 so no merging until that is merged.

Fix MTX broadcaster intermittent bug; pay for bridge transactions

---

contracts/colony/Colony.sol

When we deployed ELWSS, according to my logs, it seems as if did not deploy a new ColonyNetwork. I assume this was because, at first glance, ColonyNetwork had not changed in the `ColonyNetwork*` files and so I didn't think it was necessary. But ColonyAuthority had changed, introducing three functions, which ColonyNetwork deploys.
As far as I can tell, any colonies created from ELWSS to ELWSS3 do not have a role permitted to call these three functions. One of these is required for Safe Control, and so we have to deploy a new version that colonies can upgrade to that fixes this functionality for those missing.
This is a script I've used to investigate the extent of the issue. I believe that this only happened for the ELWSS deployment, and no others, but I would appreciate some sanity …

Make sure colonies have roles associated with functions introduced in v8

---

contracts/colony/Colony.sol
contracts/colony/ColonyArbitraryTransaction.sol
contracts/colony/ColonyExpenditure.sol
contracts/colony/ColonyFunding.sol
contracts/colony/ColonyRewards.sol
contracts/colony/ColonyTask.sol
contracts/colonyNetwork/ColonyNetwork.sol
contracts/colonyNetwork/ColonyNetworkAuction.sol
contracts/colonyNetwork/ColonyNetworkMining.sol
contracts/extensions/CoinMachine.sol
contracts/extensions/EvaluatedExpenditure.sol
contracts/extensions/FundingQueue.sol
contracts/extensions/OneTxPayment.sol
contracts/extensions/StreamingPayments.sol
contracts/extensions/TokenSupplier.sol
contracts/extensions/votingReputation/VotingReputation.sol
contracts/extensions/votingReputation/VotingReputationMisalignedRecovery.sol
contracts/metaTxToken/DSTokenBaseMeta.sol
contracts/metaTxToken/MetaTxToken.sol
contracts/reputationMiningCycle/ReputationMiningCycle.sol
contracts/reputationMiningCycle/ReputationMiningCycleCommon.sol
contracts/reputationMiningCycle/ReputationMiningCycleRespond.sol
contracts/testHelpers/ToggleableToken.sol
contracts/testHelpers/VotingReputationMisaligned.sol
contracts/tokenLocking/TokenLocking.sol

These are no longer needed with the Solidity upgrade, and in #1053 we agreed would be removed in a separate PR.
There's a new slither release that flagged a few new things which I've dealt with as I saw appropriate.

Remove uses of add/sub/mul

---

contracts/extensions/OneTxPayment.sol
contracts/extensions/votingReputation/VotingReputation.sol
test-gas-costs/gasCosts.js

[Gas cost data](https://docs.google.com/spreadsheets/d/16deqpdLbZMhiSjdfRyJUd1GgPA0yakoP29_Sl-Uakqs/edit#gid=0)
Looking at these data, and considering current patterns of app usage, I would say that the following functions would most benefit from gas optimization:
- `OneTxPayment.makePayment`
- `VotingReputation.stakeMotion`
- `VotingReputation.claimReward`
- `VotingReputation.revealVote`
- `VotingReputation.submitVote`
After analysis, the biggest change here comes from removing the setting of `SUBMIT_END` and `REVEAL_END` timestamps in `VotingReputation` prior to the stakes being set. Previously, they had been redundantly set twice.

Gas reductions

---

contracts/extensions/votingReputation/VotingReputation.sol
test/extensions/voting-rep.js

Mitigates the bug introduced in #1101, whereby if no reputation was present in a domain, a motion could still be created and would immediately become finalizable (though would not execute, as equal - zero - votes had been revealed for each side). Previously, the motion would go through the usual voting and reveal lifecycle, though without actions being able to be taken (as no reputatation exists).
While it could be argued this is desirable behaviour, it happens in a very non-standard way (with relevant timestamps being 0, and therefore in the past), it's better to prevent such useless motions from being created in the first place, which is what this PR is intending to do.

Prevent creation of motions with 0 reputation in domain

---

docs/guides/reputation-mining-client.md
docs/guides/reputation-mining.md

Adds the reputation mining guide from the deprecated gitbook page, adjusted for Docusaurus.

Add reputation mining guide from gitbook

---

contracts/colony/ColonyFunding.sol
test/contracts-network/colony-expenditure.js

The `setExpenditurePayouts` logic is incorrect in the core contracts. When multiple values were set with the same call, the funding pot `payouts` property would not be updated / set correctly. 
The updated/added test fail without the contracts changes, demonstrating the issue.
I don't believe we need to take any actions in terms of checking for 'wrong' expenditures - they're not used in the frontend (yet - development of expenditures surfaced this issue), and the consequences are 'only' that in the case of expenditures with multiple payouts, some payouts will need a new expenditure made. Funds are incorrectly returned to the domain containing the expenditure, so they can be used to pay out again via another expenditure.

Fix setExpenditurePayouts logic

---

contracts/extensions/StakedExpenditure.sol
docs/interfaces/extensions/stakedexpenditure.md
test-smoke/colony-storage-consistent.js
test/extensions/staked-expenditure.js

The Staked Expenditure extension broke some assumptions that have been made elsewhere in the stack, so bringing it in line. We should try and stick to these going forwards:
* Extensions that need to be initialised should use `initialise`, even if only setting one parameter - and this should emit the `ExtensionInitialised` event.
* `initialise` should be callable exactly once (and therefore `extensionInitialised` emitted exactly once).
* Other functions can then be used to adjust parameters 'in flight'.
I checked other extensions, and they seem to follow these restrictions, so just this one that needed updating.

Make initialise consistent on extensions

---

packages/reputation-miner/ReputationMinerClient.js
test/reputation-system/reputation-mining-client/client-auto-functionality.js

So after #1156, we were meant to be done with the flickery 'losing a race shouldn't prevent a miner from continuing' test. But it turns out, that there [are still dragons out there](https://app.circleci.com/pipelines/github/JoinColony/colonyNetwork/5686/workflows/87900da6-0395-481a-9366-84b658575004/jobs/34341). So, what's going on here? Prior to that PR being merged, I ran that test repeatedly for 12 hours, continuously, and had it pass every time, having had failures within 10 minutes prior to my changes.
While there were issues with the test itself that were fixed in that PR, on CI it is never run alone, but as part of a suite. And what I think I've pinned down was happening here is as follows:
* The previous test completes, and the `afterEach` runs. This is meant to `.close` the …

Fix flickery test when run with other tests

---

contracts/colony/ColonyDataTypes.sol
contracts/colony/ColonyFunding.sol
test/contracts-network/colony-expenditure.js

From @jakubcolony 
> I think I'll need to store whether a payout has been already claimed or not, to be able to determine whether there's any more payouts to claim from the UI. I thought about listening to the PayoutClaimed event in block-ingestor and then checking whether the funding pot ID belongs to an expenditure. However, this event doesn't contain information on which slot has been claimed, just the token address and the amount, which I don't think is enough to uniquely identify the claimed payout.
>
> I suppose I could call the getExpenditureSlotPayout every time I want to check their claimed status but caching it is a more preferable solution. Do you have any ideas on how that could be done? Could we possibly have another expenditure specific event, say ExpenditurePayoutClaimed, …

Add ExpenditurePayoutClaimed event

---

contracts/extensions/StakedExpenditure.sol
test/extensions/staked-expenditure.js

This is something that the block ingestor wants to be able to track, and I think adding the flag to the event is the only way to do it infallibly.

Add punish flag to StakedExpenditure cancel event

---

contracts/extensions/StakedExpenditure.sol
test/extensions/staked-expenditure.js

#1166 stopped the `ExpenditureCancelled` event being emitted when `CancelAndReclaimStake` was called - this restores the `ExpenditureCancelled` event as it was, an introduced an `ExpenditureStakerPunished` event.
I've also taken the opportunity to add an `agent` to our events where I thought it was appropriate - in particular, this brings the `ExpenditureCancelled` event in line with the `ExpenditureCancelled` event on the core contracts.

Restore ExpenditureCancelled event on CancelAndReclaim

---

contracts/colonyNetwork/ColonyNetworkDeployer.sol
test/contracts-network/colony-network.js

`createColonyForFrontend` is finally being used, but doesn't allow tokens that are locked to be activated. This fixes that oversight on our part.

createColonyForFrontend should allow activating locked tokens

---

packages/package-utils/getFeeData.js

Seems like there are still scenarios where the values returned by  `getFeeData` from Ethers was not sufficient to allow a transaction to be broadcast, so upping the `maxFeePerGas` to accommodate for large jumps in the base fee when blocks are full.
Non-contracts, so happy for this to be merged even with the freeze for the release.

Do not trust ethers getFeeData completely

---

packages/metatransaction-broadcaster/MetatransactionBroadcaster.js
packages/package-utils/getFeeData.js
test/packages/metaTransactionBroadcaster.js

While running down a bug that turned out to be an issue with which transactions were being sent by the front-end, I wrote some more tests. Seemed like a waste to not include them after writing them.
My additions in #1192 only affected unknown chains, which doesn't actually help with production. Added the same 'wiggle room' to when we are on a known chain.

Extra tests and extra gas for the metatransaction broadcaster

---

.circleci/config.yml

The version of docker we use on Circle has [been deprecated](https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/50176), so to avoid our builds intermittently failing over the next year, and then failing permanently before the end of it, we need to bump the version.

Bump docker version for CircleCI

---

contracts/colony/Colony.sol
contracts/colony/ColonyAuthority.sol
contracts/colony/ColonyExpenditure.sol
contracts/colony/IColony.sol
docs/interfaces/icolony.md
helpers/constants.js
scripts/deployOldUpgradeableVersion.js
test-gas-costs/gasCosts.js
test-smoke/colony-storage-consistent.js
test/contracts-network/colony-expenditure.js
test/contracts-network/colony-recovery.js
test/contracts-network/colony.js
test/contracts-network/meta-colony.js
test/extensions/one-tx-payment.js

cancelExpenditureViaArbitration

---

.solcover.js
hardhat.config.js
helpers/test-helper.js
packages/reputation-miner/patricia-test.js
scripts/deployOldUpgradeableVersion.js
test-gas-costs/gasCosts.js
test-system/end-to-end.js
test/contracts-network/colony-network-recovery.js
test/contracts-network/colony-reward-payouts.js
test/contracts-network/token-locking.js
test/cross-chain/cross-chain.js
test/extensions/voting-rep.js
test/packages/metaTransactionBroadcaster.js
test/reputation-system/client-calculations.js
test/reputation-system/client-core-functionality.js
test/reputation-system/client-sync-functionality.js
test/reputation-system/dispute-resolution-misbehaviour.js
test/reputation-system/disputes-over-child-reputation.js
test/reputation-system/happy-paths.js
test/reputation-system/reputation-mining-client/client-auto-functionality.js
test/reputation-system/root-hash-submissions.js
test/reputation-system/types-of-disagreement.js
test/truffle-fixture.js

Coverage ports are under our control now, so there's absolutely no reason to use port 8555 for coverage and 8545 when we're not under coverage. This PR puts everything on 8545 for the primary provider, regardless of coverage status.
I believe some of our test suite, after the move to hardhat, is going to break once the next release is properly made on GitHub, however (which we should do, given the release has actually happened in a practical sense). However, that's not something for this PR.

Normalize coverage ports

---

contracts/extensions/StreamingPayments.sol
test/extensions/streaming-payments.js

Additional events after discussing with Jakub about requirements for the implementation of streaming payments.
Currently a draft, not to be merged, until we've straightened everything out with the Arbitrum deployment branches, but will unblock development on the CDApp side until then.

Add additional events for StreamingPayments

---

packages/reputation-miner/ReputationMiner.js
test/reputation-system/happy-paths.js

In this test, we replaced `goodClient` with a client that used the solidity patricia tree. All subsequent tests then used it, which I think has been causing intermittent issues in CI. Given I don't think this was a deliberate (tests affecting how each other run is bad, after all), I've stopped that from happening.
Of course, it _should_ work, but I think running that down should be separate. Indeed, arguably the priority should be to work out how to remove `ganache`, and then make whatever that replacement is sufficiently performant enough for the tests to work if the soldity trie is in use, but I don't think it's possible to drop-in `hardhat` as a replacement the way we've used `ganache` here.
The important piece of functionality around the solidity tree is to make sure it gives the same …

Do not clobber goodClient in tests

---

.circleci/config.yml
contracts/colony/Colony.sol
helpers/constants.js
helpers/test-helper.js
scripts/versioningCheck.sh
test/contracts-network/colony-expenditure.js
test/contracts-network/colony.js
test/contracts-network/meta-colony.js
test/extensions/one-tx-payment.js

One of the pieces of cruft we hadn't cleaned up from the Arbitrum release was that we hadn't actually released `imwss` on GitHub, which meant that our versioning check was doing so against `hmwss`. The two main consequences of that were:
* Version bumping scripts were being overly generous (i.e. changes since `imwss` were passed if the version was bumped in `hmwss`
* With the release, our checks broke because the latest release has now moved from `truffle` to `hardhat`
As a result of 1, we missed a required version bump in #1259, but it doesn't appear any others.
This PR intends to fix these issues. Arguably the most meaningful change is an indirect result of the release though, which is how I'm treating upgrades in tests. For historical behaviour, I'm assuming that doing an upgrade from …

Update versioning check scripts

---

.circleci/config.yml
contracts/reputationMiningCycle/ReputationMiningCycle.sol
package.json
packages/package-utils/package.json
packages/package-utils/retryProvider.js
packages/reputation-miner/ReputationMiner.js
packages/reputation-miner/ReputationMinerClient.js
packages/reputation-miner/bin/index.js
pnpm-lock.yaml
test/reputation-system/client-core-functionality.js
test/reputation-system/reputation-mining-client/client-auto-functionality.js

After the merge of #1254, we got a big improvement in the time our tests take to run, but that improvement came at a cost of the suite as a whole becoming unreliable, as race conditions that could previously be ignored reared their ugly head. This PR fixes two tests, and seems to get us back to stability - four out of five builds on Circle of this branch were green, with the fifth failing due to a 502 HTTP error from Github during the build (see those builds [here](https://app.circleci.com/pipelines/github/JoinColony/colonyNetwork?branch=maint%2Fspotty-tests)), which hardly seems like something we can blame ourselves for.
Two tests were touched here. The first was the test around the oracle syncing with the reputation state correctly. With a faster hardhat, sometimes the `oracleUpdated` …

Improve test reliability

---

helpers/test-helper.js
scripts/deployOldUpgradeableVersion.js
test-smoke/colony-storage-consistent.js
test-upgrade/colony-upgrade.js
test/contracts-network/colony-network-auction.js
test/contracts-network/colony-network-recovery.js
test/contracts-network/colony-network.js

Replace the custom storage editing via `ContractEditing` with calls to ` hardhat_setStorageAt`. We are still dependent on `ContractEditing` functionality in the Ganache-based tests, as the special opcode is not available.

Introduce hardhat_setStorageAt

---

scripts/deployOldUpgradeableVersion.js

Turns out this was actually needed, not #1275. Cherry-picked in to #1144 as well.
Shouldn't need updating unless we add or remove implementation contracts. Uses `develop`, and increments the version number before deploying.
Example use:
```
deployNext=require("./scripts/deployOldUpgradeableVersion.js").deployNextColonyVersion
cn = await artifacts.require("IColonyNetwork").at("0x777760996135F0791E2e1a74aFAa060711197777")
await deployNext(cn)
```

Add a script to deploy 'next' version of colony

---

contracts/extensions/votingReputation/VotingReputationStorage.sol
helpers/test-helper.js
scripts/versioningCheck.sh
test/extensions/voting-rep.js

@chmanie 's eagle-eyes noted that it was suspicious that `votingReputation` had not had its version bumped, but every other extension had. He was right, we should have done as part of #1248 (at least).
I've reworked a fair chunk of the version check script, simply because some of it didn't work. Bash if statements remain a real blind spot for me, but this [seems to work](https://app.circleci.com/pipelines/github/JoinColony/colonyNetwork/6926/workflows/8d73248f-8b45-4025-8675-066842bc98dc/jobs/53997?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary).
In summary:
* Fix iteration over `extensions` directory by including subdirectories
* Fix bash if statement
* Remove 'depends on' logic - I think maybe this was a leftover from when we …

Fix version check script

---

packages/metatransaction-broadcaster/package.json
packages/package-utils/package.json
pnpm-lock.yaml

When ExtendedNonceManager moved, the dependency should have moved with it.
Not sure why this didn't get caught by linting, as it was flagged in my editor once I opened it, but that's not a question for now.

Move experimental ethers dependency with ExtendedNonceManager
